/**********************************************************************

	--- Qt Architect generated file ---

	File: CityFiltersData.h
	Last generated: Sun Apr 11 14:11:05 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CityFiltersData_included
#define CityFiltersData_included

#include <qdialog.h>
#include <qpushbt.h>
#include <qradiobt.h>

class CityFiltersData : public QDialog
{
    Q_OBJECT

public:

    CityFiltersData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CityFiltersData();

public slots:


protected slots:

    virtual void applyFilters();
    virtual void applyAndExit();
    virtual void cancelFilters();

protected:
    QRadioButton* activeOnlyButton;
    QRadioButton* inactiveOnlyButton;
    QRadioButton* bothButton;
    QPushButton* cancelButton;
    QPushButton* applyButton;
    QPushButton* okayButton;

};

#endif // CityFiltersData_included
