/**********************************************************************

	--- Qt Architect generated file ---

	File: HTMLReportData.h
	Last generated: Tue May 9 15:06:15 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef HTMLReportData_included
#define HTMLReportData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qcombobox.h>
#include "qtextview.h"
#include "calendar.h"

class HTMLReportData : public QWidget
{
    Q_OBJECT

public:

    HTMLReportData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~HTMLReportData();

    public slots:

    virtual void graphReport() =0;
    virtual void printReport() =0;
    virtual void emailReport() =0;

    protected slots:

    virtual void closeReport() =0;
    virtual void editFilters() =0;
    virtual void refreshReport() =0;
    virtual void dateRangeSelected(const QString&) =0;
    virtual void userButtonClickedInt() =0;

    protected:

    QLabel *startDateLabel;
    QLabel *endDateLabel;
    QPushButton *generateButton;
    QPushButton *closeButton;
    QPushButton *emailButton;
    QPushButton *printButton;
    QPushButton *graphButton;
    QPushButton *filterButton;
    QComboBox *dateList;
    QPushButton *userButton;
    DateInput *startDateCal;
    DateInput *endDateCal;
    QTextView *body;
};

#endif // HTMLReportData_included
