/**********************************************************************

	--- Qt Architect generated file ---

	File: ModemSummaryFiltersData.cpp
	Last generated: Thu Oct 7 17:04:57 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "ModemSummaryFiltersData.h"

#define Inherited QWidget

#include <qbttngrp.h>
#include <qpushbt.h>

ModemSummaryFiltersData::ModemSummaryFiltersData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* qtarch_ServerGroup;
	qtarch_ServerGroup = new QButtonGroup( this, "ServerGroup" );
	qtarch_ServerGroup->setGeometry( 5, 5, 180, 90 );
	qtarch_ServerGroup->setMinimumSize( 180, 90 );
	qtarch_ServerGroup->setMaximumSize( 180, 90 );
	qtarch_ServerGroup->setFocusPolicy( QWidget::NoFocus );
	qtarch_ServerGroup->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ServerGroup->setFrameStyle( 49 );
	qtarch_ServerGroup->setTitle( "Terminal Servers" );
	qtarch_ServerGroup->setAlignment( 1 );

	allServersButton = new QRadioButton( qtarch_ServerGroup, "AllServersButton" );
	allServersButton->setGeometry( 5, 18, 170, 25 );
	allServersButton->setMinimumSize( 0, 25 );
	allServersButton->setMaximumSize( 32767, 25 );
	connect( allServersButton, SIGNAL(clicked()), SLOT(allServersSelected()) );
	allServersButton->setFocusPolicy( QWidget::TabFocus );
	allServersButton->setBackgroundMode( QWidget::PaletteBackground );
	allServersButton->setText( "All Terminal Servers" );
	allServersButton->setAutoRepeat( FALSE );
	allServersButton->setAutoResize( FALSE );
	allServersButton->setChecked( TRUE );

	selectedServers = new QRadioButton( qtarch_ServerGroup, "SelectedServersButton" );
	selectedServers->setGeometry( 5, 48, 170, 25 );
	selectedServers->setMinimumSize( 0, 25 );
	selectedServers->setMaximumSize( 32767, 25 );
	connect( selectedServers, SIGNAL(clicked()), SLOT(selectedServersSelected()) );
	selectedServers->setFocusPolicy( QWidget::TabFocus );
	selectedServers->setBackgroundMode( QWidget::PaletteBackground );
	selectedServers->setText( "Selected Servers Only" );
	selectedServers->setAutoRepeat( FALSE );
	selectedServers->setAutoResize( FALSE );

	serverList = new QListView( this, "ServerList" );
	serverList->setGeometry( 190, 5, 196, 175 );
	serverList->setMinimumSize( 0, 0 );
	serverList->setMaximumSize( 32767, 32767 );
	connect( serverList, SIGNAL(selectionChanged()), SLOT(listSelectionChanged()) );
	serverList->setFocusPolicy( QWidget::TabFocus );
	serverList->setBackgroundMode( QWidget::PaletteBackground );
	serverList->setResizePolicy( QScrollView::Manual );
	serverList->setVScrollBarMode( QScrollView::Auto );
	serverList->setHScrollBarMode( QScrollView::Auto );
	serverList->setTreeStepSize( 20 );
	serverList->setMultiSelection( TRUE );
	serverList->setAllColumnsShowFocus( FALSE );
	serverList->setItemMargin( 1 );
	serverList->setRootIsDecorated( FALSE );
	serverList->addColumn( "Terminal Servers", -1 );
	serverList->setColumnWidthMode( 0, QListView::Maximum );
	serverList->setColumnAlignment( 0, 1 );

	QPushButton* qtarch_ApplyButton;
	qtarch_ApplyButton = new QPushButton( this, "ApplyButton" );
	qtarch_ApplyButton->setGeometry( 151, 185, 75, 30 );
	qtarch_ApplyButton->setMinimumSize( 75, 30 );
	qtarch_ApplyButton->setMaximumSize( 75, 30 );
	connect( qtarch_ApplyButton, SIGNAL(clicked()), SLOT(applyFilters()) );
	qtarch_ApplyButton->setFocusPolicy( QWidget::TabFocus );
	qtarch_ApplyButton->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ApplyButton->setText( "&Apply" );
	qtarch_ApplyButton->setAutoRepeat( FALSE );
	qtarch_ApplyButton->setAutoResize( FALSE );

	okayButton = new QPushButton( this, "OkayButton" );
	okayButton->setGeometry( 231, 185, 75, 30 );
	okayButton->setMinimumSize( 75, 30 );
	okayButton->setMaximumSize( 75, 30 );
	connect( okayButton, SIGNAL(clicked()), SLOT(applyAndExit()) );
	okayButton->setFocusPolicy( QWidget::TabFocus );
	okayButton->setBackgroundMode( QWidget::PaletteBackground );
	okayButton->setText( "&Ok" );
	okayButton->setAutoRepeat( FALSE );
	okayButton->setAutoResize( FALSE );

	cancelButton = new QPushButton( this, "CancelButton" );
	cancelButton->setGeometry( 311, 185, 75, 30 );
	cancelButton->setMinimumSize( 75, 30 );
	cancelButton->setMaximumSize( 75, 30 );
	connect( cancelButton, SIGNAL(clicked()), SLOT(cancelFilters()) );
	cancelButton->setFocusPolicy( QWidget::TabFocus );
	cancelButton->setBackgroundMode( QWidget::PaletteBackground );
	cancelButton->setText( "&Cancel" );
	cancelButton->setAutoRepeat( FALSE );
	cancelButton->setAutoResize( FALSE );

	qtarch_ServerGroup->insert( allServersButton );
	qtarch_ServerGroup->insert( selectedServers );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QBoxLayout* qtarch_layout_1_1 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 1 );
	qtarch_layout_1_1->addStrut( 0 );
	qtarch_layout_1_1->addWidget( qtarch_ServerGroup, 1, 9 );
	QGridLayout* qtarch_layout_1_1_1 = new QGridLayout( qtarch_ServerGroup, 4, 1, 5, 5, NULL );
	qtarch_layout_1_1_1->addColSpacing( 0, 5 );
	qtarch_layout_1_1_1->setColStretch( 0, 1 );
	qtarch_layout_1_1_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_1_1->setRowStretch( 0, 1 );
	qtarch_layout_1_1_1->addRowSpacing( 1, 0 );
	qtarch_layout_1_1_1->setRowStretch( 1, 0 );
	qtarch_layout_1_1_1->addWidget( allServersButton, 1, 0, 36 );
	qtarch_layout_1_1_1->addRowSpacing( 2, 0 );
	qtarch_layout_1_1_1->setRowStretch( 2, 0 );
	qtarch_layout_1_1_1->addWidget( selectedServers, 2, 0, 36 );
	qtarch_layout_1_1_1->addRowSpacing( 3, 0 );
	qtarch_layout_1_1_1->setRowStretch( 3, 1 );
	qtarch_layout_1_1->addWidget( serverList, 1, 36 );
	QGridLayout* qtarch_layout_1_2 = new QGridLayout( 1, 4, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 0 );
	qtarch_layout_1_2->addColSpacing( 0, 5 );
	qtarch_layout_1_2->setColStretch( 0, 1 );
	qtarch_layout_1_2->addColSpacing( 1, 5 );
	qtarch_layout_1_2->setColStretch( 1, 0 );
	qtarch_layout_1_2->addColSpacing( 2, 5 );
	qtarch_layout_1_2->setColStretch( 2, 0 );
	qtarch_layout_1_2->addColSpacing( 3, 5 );
	qtarch_layout_1_2->setColStretch( 3, 0 );
	qtarch_layout_1_2->addRowSpacing( 0, 0 );
	qtarch_layout_1_2->setRowStretch( 0, 0 );
	qtarch_layout_1_2->addWidget( qtarch_ApplyButton, 0, 1, 34 );
	qtarch_layout_1_2->addWidget( okayButton, 0, 2, 34 );
	qtarch_layout_1_2->addWidget( cancelButton, 0, 3, 34 );
	resize( 391,220 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


ModemSummaryFiltersData::~ModemSummaryFiltersData()
{
}
void ModemSummaryFiltersData::allServersSelected()
{
}
void ModemSummaryFiltersData::selectedServersSelected()
{
}
void ModemSummaryFiltersData::listSelectionChanged()
{
}
void ModemSummaryFiltersData::applyFilters()
{
}
void ModemSummaryFiltersData::applyAndExit()
{
}
void ModemSummaryFiltersData::cancelFilters()
{
}
