/**********************************************************************

	--- Qt Architect generated file ---

	File: ModemSummaryFiltersData.h
	Last generated: Thu Oct 7 17:04:57 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef ModemSummaryFiltersData_included
#define ModemSummaryFiltersData_included

#include <qwidget.h>
#include <qlistview.h>
#include <qpushbt.h>
#include <qradiobt.h>

class ModemSummaryFiltersData : public QWidget
{
    Q_OBJECT

public:

    ModemSummaryFiltersData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~ModemSummaryFiltersData();

public slots:


protected slots:

    virtual void selectedServersSelected();
    virtual void applyFilters();
    virtual void listSelectionChanged();
    virtual void applyAndExit();
    virtual void cancelFilters();
    virtual void allServersSelected();

protected:
    QRadioButton* allServersButton;
    QRadioButton* selectedServers;
    QListView* serverList;
    QPushButton* okayButton;
    QPushButton* cancelButton;

};

#endif // ModemSummaryFiltersData_included
