/**********************************************************************

	--- Qt Architect generated file ---

	File: UsersOnlineFiltersData.cpp
	Last generated: Fri Oct 1 13:51:20 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "UsersOnlineFiltersData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qbttngrp.h>
#include <qpushbt.h>

UsersOnlineFiltersData::UsersOnlineFiltersData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QButtonGroup* qtarch_ServerGroup;
	qtarch_ServerGroup = new QButtonGroup( this, "ServerGroup" );
	qtarch_ServerGroup->setGeometry( 5, 40, 180, 90 );
	qtarch_ServerGroup->setMinimumSize( 180, 90 );
	qtarch_ServerGroup->setMaximumSize( 180, 90 );
	qtarch_ServerGroup->setFocusPolicy( QWidget::NoFocus );
	qtarch_ServerGroup->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ServerGroup->setFrameStyle( 49 );
	qtarch_ServerGroup->setTitle( "Terminal Servers" );
	qtarch_ServerGroup->setAlignment( 1 );

	QLabel* qtarch_DateLabel;
	qtarch_DateLabel = new QLabel( this, "DateLabel" );
	qtarch_DateLabel->setGeometry( 5, 5, 80, 30 );
	qtarch_DateLabel->setMinimumSize( 80, 30 );
	qtarch_DateLabel->setMaximumSize( 80, 30 );
	qtarch_DateLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_DateLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_DateLabel->setText( "Date:" );
	qtarch_DateLabel->setAlignment( 290 );
	qtarch_DateLabel->setMargin( -1 );

	dateParent = new QLabel( this, "DateParent" );
	dateParent->setGeometry( 90, 5, 135, 30 );
	dateParent->setMinimumSize( 0, 30 );
	dateParent->setMaximumSize( 32767, 30 );
	dateParent->setFocusPolicy( QWidget::NoFocus );
	dateParent->setBackgroundMode( QWidget::PaletteBackground );
	dateParent->setText( "DateParent" );
	dateParent->setAlignment( 289 );
	dateParent->setMargin( -1 );

	QLabel* qtarch_TimeLabel;
	qtarch_TimeLabel = new QLabel( this, "TimeLabel" );
	qtarch_TimeLabel->setGeometry( 230, 5, 80, 30 );
	qtarch_TimeLabel->setMinimumSize( 80, 30 );
	qtarch_TimeLabel->setMaximumSize( 80, 30 );
	qtarch_TimeLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_TimeLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_TimeLabel->setText( "Time:" );
	qtarch_TimeLabel->setAlignment( 290 );
	qtarch_TimeLabel->setMargin( -1 );

	timeParent = new QLabel( this, "TimeParent" );
	timeParent->setGeometry( 315, 5, 135, 30 );
	timeParent->setMinimumSize( 0, 30 );
	timeParent->setMaximumSize( 32767, 30 );
	timeParent->setFocusPolicy( QWidget::NoFocus );
	timeParent->setBackgroundMode( QWidget::PaletteBackground );
	timeParent->setText( "TimeParent" );
	timeParent->setAlignment( 289 );
	timeParent->setMargin( -1 );

	allServersButton = new QRadioButton( qtarch_ServerGroup, "AllServersButton" );
	allServersButton->setGeometry( 5, 18, 170, 25 );
	allServersButton->setMinimumSize( 0, 25 );
	allServersButton->setMaximumSize( 32767, 25 );
	connect( allServersButton, SIGNAL(clicked()), SLOT(allServersSelected()) );
	allServersButton->setFocusPolicy( QWidget::TabFocus );
	allServersButton->setBackgroundMode( QWidget::PaletteBackground );
	allServersButton->setText( "All Terminal Servers" );
	allServersButton->setAutoRepeat( FALSE );
	allServersButton->setAutoResize( FALSE );
	allServersButton->setChecked( TRUE );

	selectedServers = new QRadioButton( qtarch_ServerGroup, "SelectedServersButton" );
	selectedServers->setGeometry( 5, 48, 170, 25 );
	selectedServers->setMinimumSize( 0, 25 );
	selectedServers->setMaximumSize( 32767, 25 );
	connect( selectedServers, SIGNAL(clicked()), SLOT(selectedServersSelected()) );
	selectedServers->setFocusPolicy( QWidget::TabFocus );
	selectedServers->setBackgroundMode( QWidget::PaletteBackground );
	selectedServers->setText( "Selected Servers Only" );
	selectedServers->setAutoRepeat( FALSE );
	selectedServers->setAutoResize( FALSE );

	serverList = new QListView( this, "ServerList" );
	serverList->setGeometry( 190, 40, 260, 205 );
	serverList->setMinimumSize( 0, 0 );
	serverList->setMaximumSize( 32767, 32767 );
	serverList->setFocusPolicy( QWidget::TabFocus );
	serverList->setBackgroundMode( QWidget::PaletteBackground );
	serverList->setResizePolicy( QScrollView::Manual );
	serverList->setVScrollBarMode( QScrollView::Auto );
	serverList->setHScrollBarMode( QScrollView::Auto );
	serverList->setTreeStepSize( 20 );
	serverList->setMultiSelection( FALSE );
	serverList->setAllColumnsShowFocus( FALSE );
	serverList->setItemMargin( 1 );
	serverList->setRootIsDecorated( FALSE );
	serverList->addColumn( "Terminal Servers", -1 );
	serverList->setColumnWidthMode( 0, QListView::Maximum );
	serverList->setColumnAlignment( 0, 1 );

	QPushButton* qtarch_ApplyButton;
	qtarch_ApplyButton = new QPushButton( this, "ApplyButton" );
	qtarch_ApplyButton->setGeometry( 215, 250, 75, 30 );
	qtarch_ApplyButton->setMinimumSize( 75, 30 );
	qtarch_ApplyButton->setMaximumSize( 75, 30 );
	connect( qtarch_ApplyButton, SIGNAL(clicked()), SLOT(applyFilters()) );
	qtarch_ApplyButton->setFocusPolicy( QWidget::TabFocus );
	qtarch_ApplyButton->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ApplyButton->setText( "&Apply" );
	qtarch_ApplyButton->setAutoRepeat( FALSE );
	qtarch_ApplyButton->setAutoResize( FALSE );

	okayButton = new QPushButton( this, "OkayButton" );
	okayButton->setGeometry( 295, 250, 75, 30 );
	okayButton->setMinimumSize( 75, 30 );
	okayButton->setMaximumSize( 75, 30 );
	connect( okayButton, SIGNAL(clicked()), SLOT(applyAndExit()) );
	okayButton->setFocusPolicy( QWidget::TabFocus );
	okayButton->setBackgroundMode( QWidget::PaletteBackground );
	okayButton->setText( "&Ok" );
	okayButton->setAutoRepeat( FALSE );
	okayButton->setAutoResize( FALSE );

	cancelButton = new QPushButton( this, "CancelButton" );
	cancelButton->setGeometry( 375, 250, 75, 30 );
	cancelButton->setMinimumSize( 75, 30 );
	cancelButton->setMaximumSize( 75, 30 );
	connect( cancelButton, SIGNAL(clicked()), SLOT(cancelFilters()) );
	cancelButton->setFocusPolicy( QWidget::TabFocus );
	cancelButton->setBackgroundMode( QWidget::PaletteBackground );
	cancelButton->setText( "&Cancel" );
	cancelButton->setAutoRepeat( FALSE );
	cancelButton->setAutoResize( FALSE );

	qtarch_ServerGroup->insert( allServersButton );
	qtarch_ServerGroup->insert( selectedServers );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QGridLayout* qtarch_layout_1_1 = new QGridLayout( 1, 4, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 0 );
	qtarch_layout_1_1->addColSpacing( 0, 5 );
	qtarch_layout_1_1->setColStretch( 0, 0 );
	qtarch_layout_1_1->addColSpacing( 1, 5 );
	qtarch_layout_1_1->setColStretch( 1, 1 );
	qtarch_layout_1_1->addColSpacing( 2, 5 );
	qtarch_layout_1_1->setColStretch( 2, 0 );
	qtarch_layout_1_1->addColSpacing( 3, 5 );
	qtarch_layout_1_1->setColStretch( 3, 1 );
	qtarch_layout_1_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_1->setRowStretch( 0, 0 );
	qtarch_layout_1_1->addWidget( qtarch_DateLabel, 0, 0, 36 );
	qtarch_layout_1_1->addWidget( dateParent, 0, 1, 36 );
	qtarch_layout_1_1->addWidget( qtarch_TimeLabel, 0, 2, 36 );
	qtarch_layout_1_1->addWidget( timeParent, 0, 3, 36 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 1 );
	qtarch_layout_1_2->addStrut( 0 );
	qtarch_layout_1_2->addWidget( qtarch_ServerGroup, 1, 9 );
	QGridLayout* qtarch_layout_1_2_1 = new QGridLayout( qtarch_ServerGroup, 4, 1, 5, 5, NULL );
	qtarch_layout_1_2_1->addColSpacing( 0, 5 );
	qtarch_layout_1_2_1->setColStretch( 0, 1 );
	qtarch_layout_1_2_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_2_1->setRowStretch( 0, 1 );
	qtarch_layout_1_2_1->addRowSpacing( 1, 0 );
	qtarch_layout_1_2_1->setRowStretch( 1, 0 );
	qtarch_layout_1_2_1->addWidget( allServersButton, 1, 0, 36 );
	qtarch_layout_1_2_1->addRowSpacing( 2, 0 );
	qtarch_layout_1_2_1->setRowStretch( 2, 0 );
	qtarch_layout_1_2_1->addWidget( selectedServers, 2, 0, 36 );
	qtarch_layout_1_2_1->addRowSpacing( 3, 0 );
	qtarch_layout_1_2_1->setRowStretch( 3, 1 );
	qtarch_layout_1_2->addWidget( serverList, 1, 36 );
	QGridLayout* qtarch_layout_1_3 = new QGridLayout( 1, 4, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_3, 0 );
	qtarch_layout_1_3->addColSpacing( 0, 5 );
	qtarch_layout_1_3->setColStretch( 0, 1 );
	qtarch_layout_1_3->addColSpacing( 1, 5 );
	qtarch_layout_1_3->setColStretch( 1, 0 );
	qtarch_layout_1_3->addColSpacing( 2, 5 );
	qtarch_layout_1_3->setColStretch( 2, 0 );
	qtarch_layout_1_3->addColSpacing( 3, 5 );
	qtarch_layout_1_3->setColStretch( 3, 0 );
	qtarch_layout_1_3->addRowSpacing( 0, 0 );
	qtarch_layout_1_3->setRowStretch( 0, 0 );
	qtarch_layout_1_3->addWidget( qtarch_ApplyButton, 0, 1, 34 );
	qtarch_layout_1_3->addWidget( okayButton, 0, 2, 34 );
	qtarch_layout_1_3->addWidget( cancelButton, 0, 3, 34 );
	resize( 455,285 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


UsersOnlineFiltersData::~UsersOnlineFiltersData()
{
}
void UsersOnlineFiltersData::allServersSelected()
{
}
void UsersOnlineFiltersData::selectedServersSelected()
{
}
void UsersOnlineFiltersData::applyFilters()
{
}
void UsersOnlineFiltersData::applyAndExit()
{
}
void UsersOnlineFiltersData::cancelFilters()
{
}
