/**********************************************************************

	--- Qt Architect generated file ---

	File: UsersOnlineFiltersData.h
	Last generated: Fri Oct 1 13:51:20 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef UsersOnlineFiltersData_included
#define UsersOnlineFiltersData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qlistview.h>
#include <qpushbt.h>
#include <qradiobt.h>

class UsersOnlineFiltersData : public QDialog
{
    Q_OBJECT

public:

    UsersOnlineFiltersData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~UsersOnlineFiltersData();

public slots:


protected slots:

    virtual void selectedServersSelected();
    virtual void applyFilters();
    virtual void applyAndExit();
    virtual void cancelFilters();
    virtual void allServersSelected();

protected:
    QLabel* dateParent;
    QLabel* timeParent;
    QRadioButton* allServersButton;
    QRadioButton* selectedServers;
    QListView* serverList;
    QPushButton* okayButton;
    QPushButton* cancelButton;

};

#endif // UsersOnlineFiltersData_included
