/**********************************************************************

	--- Dlgedit generated file ---

	File: CallBackVerifyData.h
	Last generated: Sun Nov 9 13:26:44 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef CallBackVerifyData_included
#define CallBackVerifyData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qlined.h>
#include <qradiobt.h>

class CallBackVerifyData : public QDialog
{
    Q_OBJECT

public:

    CallBackVerifyData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CallBackVerifyData();

public slots:


protected slots:


protected:
    QRadioButton* dayPhoneButton;
    QLabel* dayPhoneLabel;
    QRadioButton* evePhoneButton;
    QLabel* evePhoneLabel;
    QRadioButton* faxPhoneButton;
    QLabel* faxPhoneLabel;
    QRadioButton* altPhoneButton;
    QLabel* altPhoneLabel;
    QRadioButton* otherButton;
    QLineEdit* otherPhone;

};

#endif // CallBackVerifyData_included
