/**********************************************************************

	--- Dlgedit generated file ---

	File: CallBackVerifyData.cpp
	Last generated: Sun Nov 9 13:26:44 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#include "CallBackVerifyData.h"

#define Inherited QDialog

#include <qbttngrp.h>
#include <qlabel.h>
#include <qpushbt.h>

CallBackVerifyData::CallBackVerifyData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE )
{
	QLabel* tmpQLabel;
	tmpQLabel = new QLabel( this, "Label_1" );
	tmpQLabel->setGeometry( 20, 10, 360, 80 );
	tmpQLabel->setText( "Please select the number you are calling this user back at for verification purposes.  When you have finished calling them back, click the Verified button to save the customer record and proceed to creating logins for this customer." );
	tmpQLabel->setAlignment( 1313 );
	tmpQLabel->setMargin( -1 );

	dayPhoneButton = new QRadioButton( this, "RadioButton_1" );
	dayPhoneButton->setGeometry( 70, 120, 100, 20 );
	dayPhoneButton->setText( "&Day Phone" );
	dayPhoneButton->setAutoRepeat( FALSE );
	dayPhoneButton->setAutoResize( FALSE );
	dayPhoneButton->setChecked( TRUE );

	dayPhoneLabel = new QLabel( this, "Label_2" );
	dayPhoneLabel->setGeometry( 175, 120, 110, 20 );
	dayPhoneLabel->setText( "" );
	dayPhoneLabel->setAlignment( 289 );
	dayPhoneLabel->setMargin( -1 );

	evePhoneButton = new QRadioButton( this, "RadioButton_2" );
	evePhoneButton->setGeometry( 70, 140, 100, 20 );
	evePhoneButton->setText( "&Eve Phone" );
	evePhoneButton->setAutoRepeat( FALSE );
	evePhoneButton->setAutoResize( FALSE );

	evePhoneLabel = new QLabel( this, "Label_3" );
	evePhoneLabel->setGeometry( 175, 140, 110, 20 );
	evePhoneLabel->setText( "" );
	evePhoneLabel->setAlignment( 289 );
	evePhoneLabel->setMargin( -1 );

	faxPhoneButton = new QRadioButton( this, "RadioButton_3" );
	faxPhoneButton->setGeometry( 70, 160, 100, 20 );
	faxPhoneButton->setText( "&Fax Phone" );
	faxPhoneButton->setAutoRepeat( FALSE );
	faxPhoneButton->setAutoResize( FALSE );

	faxPhoneLabel = new QLabel( this, "Label_4" );
	faxPhoneLabel->setGeometry( 175, 160, 110, 20 );
	faxPhoneLabel->setText( "" );
	faxPhoneLabel->setAlignment( 289 );
	faxPhoneLabel->setMargin( -1 );

	altPhoneButton = new QRadioButton( this, "RadioButton_4" );
	altPhoneButton->setGeometry( 70, 180, 100, 20 );
	altPhoneButton->setText( "&Alt Phone" );
	altPhoneButton->setAutoRepeat( FALSE );
	altPhoneButton->setAutoResize( FALSE );

	altPhoneLabel = new QLabel( this, "Label_5" );
	altPhoneLabel->setGeometry( 175, 180, 110, 20 );
	altPhoneLabel->setText( "" );
	altPhoneLabel->setAlignment( 289 );
	altPhoneLabel->setMargin( -1 );

	otherButton = new QRadioButton( this, "RadioButton_5" );
	otherButton->setGeometry( 70, 200, 100, 20 );
	otherButton->setText( "&Other Phone" );
	otherButton->setAutoRepeat( FALSE );
	otherButton->setAutoResize( FALSE );

	otherPhone = new QLineEdit( this, "LineEdit_1" );
	otherPhone->setGeometry( 175, 200, 110, 20 );
	otherPhone->setText( "" );
	otherPhone->setMaxLength( 30 );
	otherPhone->setEchoMode( QLineEdit::Normal );
	otherPhone->setFrame( TRUE );

	QPushButton* tmpQPushButton;
	tmpQPushButton = new QPushButton( this, "PushButton_1" );
	tmpQPushButton->setGeometry( 175, 250, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(accept()) );
	tmpQPushButton->setText( "&Verified" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	tmpQPushButton = new QPushButton( this, "PushButton_2" );
	tmpQPushButton->setGeometry( 290, 250, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(reject()) );
	tmpQPushButton->setText( "&Cancel" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	QButtonGroup* tmpQButtonGroup;
	tmpQButtonGroup = new QButtonGroup( this, "ButtonGroup_1" );
	tmpQButtonGroup->setGeometry( 60, 100, 280, 130 );
	tmpQButtonGroup->setFrameStyle( 49 );
	tmpQButtonGroup->setTitle( "Phone Numbers" );
	tmpQButtonGroup->setAlignment( 1 );
	tmpQButtonGroup->insert( dayPhoneButton );
	tmpQButtonGroup->insert( evePhoneButton );
	tmpQButtonGroup->insert( faxPhoneButton );
	tmpQButtonGroup->insert( altPhoneButton );
	tmpQButtonGroup->insert( otherButton );
	tmpQButtonGroup->lower();

	resize( 400, 300 );
}


CallBackVerifyData::~CallBackVerifyData()
{
}
