/**********************************************************************

	--- Qt Architect generated file ---

	File: ChangeBillingCycleData.h
	Last generated: Tue Feb 22 18:44:36 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef ChangeBillingCycleData_included
#define ChangeBillingCycleData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qcombobox.h>
#include <qlineedit.h>

class ChangeBillingCycleData : public QDialog
{
    Q_OBJECT

public:

    ChangeBillingCycleData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~ChangeBillingCycleData();

    protected slots:

    virtual void cancelBillingCycleChange() =0;
    virtual void saveBillingCycleChange() =0;

    protected:

    QComboBox *cycleList;
    QLineEdit *effectiveDate;
    QPushButton *saveButton;
    QPushButton *cancelButton;
    QLabel *customerLabel;
};

#endif // ChangeBillingCycleData_included
