/**********************************************************************

	--- Qt Architect generated file ---

	File: ChangeRatePlanData.cpp
	Last generated: Thu Jul 23 19:19:55 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "ChangeRatePlanData.h"

#define Inherited QDialog

#include <qlabel.h>

ChangeRatePlanData::ChangeRatePlanData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QLabel* dlgedit_Label_1;
	dlgedit_Label_1 = new QLabel( this, "Label_1" );
	dlgedit_Label_1->setGeometry( 10, 45, 100, 25 );
	dlgedit_Label_1->setMinimumSize( 10, 10 );
	dlgedit_Label_1->setMaximumSize( 32767, 32767 );
	dlgedit_Label_1->setText( "New Rate Plan:" );
	dlgedit_Label_1->setAlignment( 290 );
	dlgedit_Label_1->setMargin( -1 );

	ratePlanList = new QComboBox( FALSE, this, "ComboBox_1" );
	ratePlanList->setGeometry( 115, 45, 195, 25 );
	ratePlanList->setMinimumSize( 10, 10 );
	ratePlanList->setMaximumSize( 32767, 32767 );
	ratePlanList->setSizeLimit( 10 );
	ratePlanList->setAutoResize( FALSE );

	QLabel* dlgedit_Label_2;
	dlgedit_Label_2 = new QLabel( this, "Label_2" );
	dlgedit_Label_2->setGeometry( 10, 75, 100, 25 );
	dlgedit_Label_2->setMinimumSize( 10, 10 );
	dlgedit_Label_2->setMaximumSize( 32767, 32767 );
	dlgedit_Label_2->setText( "Effective date:" );
	dlgedit_Label_2->setAlignment( 290 );
	dlgedit_Label_2->setMargin( -1 );

	effectiveDate = new QLineEdit( this, "LineEdit_1" );
	effectiveDate->setGeometry( 115, 75, 110, 25 );
	effectiveDate->setMinimumSize( 10, 10 );
	effectiveDate->setMaximumSize( 32767, 32767 );
	effectiveDate->setText( "" );
	effectiveDate->setMaxLength( 10 );
	effectiveDate->setEchoMode( QLineEdit::Normal );
	effectiveDate->setFrame( TRUE );

	saveButton = new QPushButton( this, "PushButton_1" );
	saveButton->setGeometry( 90, 115, 100, 30 );
	saveButton->setMinimumSize( 10, 10 );
	saveButton->setMaximumSize( 32767, 32767 );
	connect( saveButton, SIGNAL(clicked()), SLOT(saveRatePlanChange()) );
	saveButton->setText( "&Save" );
	saveButton->setAutoRepeat( FALSE );
	saveButton->setAutoResize( FALSE );

	cancelButton = new QPushButton( this, "PushButton_2" );
	cancelButton->setGeometry( 205, 115, 100, 30 );
	cancelButton->setMinimumSize( 10, 10 );
	cancelButton->setMaximumSize( 32767, 32767 );
	connect( cancelButton, SIGNAL(clicked()), SLOT(cancelRatePlanChange()) );
	cancelButton->setText( "&Cancel" );
	cancelButton->setAutoRepeat( FALSE );
	cancelButton->setAutoResize( FALSE );

	QLabel* dlgedit_Label_3;
	dlgedit_Label_3 = new QLabel( this, "Label_3" );
	dlgedit_Label_3->setGeometry( 10, 10, 100, 20 );
	dlgedit_Label_3->setMinimumSize( 10, 10 );
	dlgedit_Label_3->setMaximumSize( 32767, 32767 );
	dlgedit_Label_3->setText( "Customer:" );
	dlgedit_Label_3->setAlignment( 290 );
	dlgedit_Label_3->setMargin( -1 );

	customerLabel = new QLabel( this, "Label_4" );
	customerLabel->setGeometry( 115, 10, 265, 20 );
	customerLabel->setMinimumSize( 10, 10 );
	customerLabel->setMaximumSize( 32767, 32767 );
	customerLabel->setText( "" );
	customerLabel->setAlignment( 289 );
	customerLabel->setMargin( -1 );

	resize( 400,170 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


ChangeRatePlanData::~ChangeRatePlanData()
{
}
void ChangeRatePlanData::saveRatePlanChange()
{
}
void ChangeRatePlanData::cancelRatePlanChange()
{
}
