/**********************************************************************

	--- Qt Architect generated file ---

	File: ChangePasswordData.cpp
	Last generated: Fri May 22 18:34:36 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "ChangePasswordData.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qpushbt.h>

ChangePasswordData::ChangePasswordData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QLabel* dlgedit_Label_1;
	dlgedit_Label_1 = new QLabel( this, "Label_1" );
	dlgedit_Label_1->setGeometry( 10, 10, 95, 20 );
	dlgedit_Label_1->setMinimumSize( 10, 10 );
	dlgedit_Label_1->setMaximumSize( 32767, 32767 );
	dlgedit_Label_1->setText( "Customer ID:" );
	dlgedit_Label_1->setAlignment( 290 );
	dlgedit_Label_1->setMargin( -1 );

	QLabel* dlgedit_Label_2;
	dlgedit_Label_2 = new QLabel( this, "Label_2" );
	dlgedit_Label_2->setGeometry( 5, 30, 100, 20 );
	dlgedit_Label_2->setMinimumSize( 10, 10 );
	dlgedit_Label_2->setMaximumSize( 32767, 32767 );
	dlgedit_Label_2->setText( "Customer Name:" );
	dlgedit_Label_2->setAlignment( 290 );
	dlgedit_Label_2->setMargin( -1 );

	QLabel* dlgedit_Label_3;
	dlgedit_Label_3 = new QLabel( this, "Label_3" );
	dlgedit_Label_3->setGeometry( 5, 50, 100, 20 );
	dlgedit_Label_3->setMinimumSize( 10, 10 );
	dlgedit_Label_3->setMaximumSize( 32767, 32767 );
	dlgedit_Label_3->setText( "Contact Name:" );
	dlgedit_Label_3->setAlignment( 290 );
	dlgedit_Label_3->setMargin( -1 );

	QLabel* dlgedit_Label_4;
	dlgedit_Label_4 = new QLabel( this, "Label_4" );
	dlgedit_Label_4->setGeometry( 5, 70, 100, 20 );
	dlgedit_Label_4->setMinimumSize( 10, 10 );
	dlgedit_Label_4->setMaximumSize( 32767, 32767 );
	dlgedit_Label_4->setText( "Login ID:" );
	dlgedit_Label_4->setAlignment( 290 );
	dlgedit_Label_4->setMargin( -1 );

	QLabel* dlgedit_Label_5;
	dlgedit_Label_5 = new QLabel( this, "Label_5" );
	dlgedit_Label_5->setGeometry( 5, 125, 100, 20 );
	dlgedit_Label_5->setMinimumSize( 10, 10 );
	dlgedit_Label_5->setMaximumSize( 32767, 32767 );
	dlgedit_Label_5->setText( "New Password:" );
	dlgedit_Label_5->setAlignment( 290 );
	dlgedit_Label_5->setMargin( -1 );

	customerIDLabel = new QLabel( this, "Label_6" );
	customerIDLabel->setGeometry( 110, 10, 270, 20 );
	customerIDLabel->setMinimumSize( 10, 10 );
	customerIDLabel->setMaximumSize( 32767, 32767 );
	customerIDLabel->setText( "" );
	customerIDLabel->setAlignment( 289 );
	customerIDLabel->setMargin( -1 );

	customerNameLabel = new QLabel( this, "Label_7" );
	customerNameLabel->setGeometry( 110, 30, 270, 20 );
	customerNameLabel->setMinimumSize( 10, 10 );
	customerNameLabel->setMaximumSize( 32767, 32767 );
	customerNameLabel->setText( "" );
	customerNameLabel->setAlignment( 289 );
	customerNameLabel->setMargin( -1 );

	contactNameLabel = new QLabel( this, "Label_8" );
	contactNameLabel->setGeometry( 110, 50, 270, 20 );
	contactNameLabel->setMinimumSize( 10, 10 );
	contactNameLabel->setMaximumSize( 32767, 32767 );
	contactNameLabel->setText( "" );
	contactNameLabel->setAlignment( 289 );
	contactNameLabel->setMargin( -1 );

	loginIDLabel = new QLabel( this, "Label_9" );
	loginIDLabel->setGeometry( 110, 70, 270, 20 );
	loginIDLabel->setMinimumSize( 10, 10 );
	loginIDLabel->setMaximumSize( 32767, 32767 );
	loginIDLabel->setText( "" );
	loginIDLabel->setAlignment( 289 );
	loginIDLabel->setMargin( -1 );

	QLabel* dlgedit_Label_10;
	dlgedit_Label_10 = new QLabel( this, "Label_10" );
	dlgedit_Label_10->setGeometry( 5, 90, 100, 20 );
	dlgedit_Label_10->setMinimumSize( 10, 10 );
	dlgedit_Label_10->setMaximumSize( 32767, 32767 );
	dlgedit_Label_10->setText( "Login Type:" );
	dlgedit_Label_10->setAlignment( 290 );
	dlgedit_Label_10->setMargin( -1 );

	loginTypeLabel = new QLabel( this, "Label_11" );
	loginTypeLabel->setGeometry( 110, 90, 270, 20 );
	loginTypeLabel->setMinimumSize( 10, 10 );
	loginTypeLabel->setMaximumSize( 32767, 32767 );
	loginTypeLabel->setText( "" );
	loginTypeLabel->setAlignment( 289 );
	loginTypeLabel->setMargin( -1 );

	newPassword = new QLineEdit( this, "LineEdit_1" );
	newPassword->setGeometry( 110, 125, 100, 20 );
	newPassword->setMinimumSize( 10, 10 );
	newPassword->setMaximumSize( 32767, 32767 );
	newPassword->setText( "" );
	newPassword->setMaxLength( 8 );
	newPassword->setEchoMode( QLineEdit::Normal );
	newPassword->setFrame( TRUE );

	generateButton = new QPushButton( this, "PushButton_1" );
	generateButton->setGeometry( 280, 120, 100, 30 );
	generateButton->setMinimumSize( 10, 10 );
	generateButton->setMaximumSize( 32767, 32767 );
	connect( generateButton, SIGNAL(clicked()), SLOT(generatePassword()) );
	generateButton->setText( "&Generate" );
	generateButton->setAutoRepeat( FALSE );
	generateButton->setAutoResize( FALSE );

	QPushButton* dlgedit_PushButton_2;
	dlgedit_PushButton_2 = new QPushButton( this, "PushButton_2" );
	dlgedit_PushButton_2->setGeometry( 170, 170, 100, 30 );
	dlgedit_PushButton_2->setMinimumSize( 10, 10 );
	dlgedit_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_2, SIGNAL(clicked()), SLOT(savePassword()) );
	dlgedit_PushButton_2->setText( "&Save" );
	dlgedit_PushButton_2->setAutoRepeat( FALSE );
	dlgedit_PushButton_2->setAutoResize( FALSE );

	QPushButton* dlgedit_PushButton_3;
	dlgedit_PushButton_3 = new QPushButton( this, "PushButton_3" );
	dlgedit_PushButton_3->setGeometry( 280, 170, 100, 30 );
	dlgedit_PushButton_3->setMinimumSize( 10, 10 );
	dlgedit_PushButton_3->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_3, SIGNAL(clicked()), SLOT(cancelPassword()) );
	dlgedit_PushButton_3->setText( "&Cancel" );
	dlgedit_PushButton_3->setAutoRepeat( FALSE );
	dlgedit_PushButton_3->setAutoResize( FALSE );

	resize( 400,220 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


ChangePasswordData::~ChangePasswordData()
{
}
void ChangePasswordData::generatePassword()
{
}
void ChangePasswordData::savePassword()
{
}
void ChangePasswordData::cancelPassword()
{
}
