/**********************************************************************

	--- Qt Architect generated file ---

	File: ChangeBillingCycleData.cpp
	Last generated: Tue Feb 22 18:44:36 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "ChangeBillingCycleData.h"

#include <qlabel.h>

ChangeBillingCycleData::ChangeBillingCycleData(QWidget *parent, const char *name)
                       : QDialog(parent, name, TRUE, 0)
{
    QLabel *qtarch_Label_1 = new QLabel(this, "Label_1");
    qtarch_Label_1->setGeometry(5, 45, 110, 25);
    qtarch_Label_1->setMinimumSize(10, 10);
    qtarch_Label_1->setMaximumSize(32767, 32767);
    qtarch_Label_1->setFocusPolicy(QWidget::NoFocus);
    qtarch_Label_1->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_Label_1->setFrameStyle( 0 );
    qtarch_Label_1->setLineWidth( 1 );
    qtarch_Label_1->setMidLineWidth( 0 );
    qtarch_Label_1->QFrame::setMargin( -1 );
    qtarch_Label_1->setText( "New Billing Cycle:" );
    qtarch_Label_1->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_Label_1->setMargin( -1 );

    cycleList = new QComboBox(FALSE, this, "ComboBox_1");
    cycleList->setGeometry(120, 45, 195, 25);
    cycleList->setMinimumSize(10, 10);
    cycleList->setMaximumSize(32767, 32767);
    cycleList->setFocusPolicy(QWidget::StrongFocus);
    cycleList->setBackgroundMode(QWidget::NoBackground);
    cycleList->setSizeLimit( 10 );
    cycleList->setAutoResize( FALSE );
    cycleList->setMaxCount( 2147483647 );
    cycleList->setAutoCompletion( FALSE );

    QLabel *qtarch_Label_2 = new QLabel(this, "Label_2");
    qtarch_Label_2->setGeometry(10, 75, 105, 25);
    qtarch_Label_2->setMinimumSize(10, 10);
    qtarch_Label_2->setMaximumSize(32767, 32767);
    qtarch_Label_2->setFocusPolicy(QWidget::NoFocus);
    qtarch_Label_2->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_Label_2->setFrameStyle( 0 );
    qtarch_Label_2->setLineWidth( 1 );
    qtarch_Label_2->setMidLineWidth( 0 );
    qtarch_Label_2->QFrame::setMargin( -1 );
    qtarch_Label_2->setText( "Effective date:" );
    qtarch_Label_2->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_Label_2->setMargin( -1 );

    effectiveDate = new QLineEdit(this, "LineEdit_1");
    effectiveDate->setGeometry(120, 75, 110, 25);
    effectiveDate->setMinimumSize(10, 10);
    effectiveDate->setMaximumSize(32767, 32767);
    effectiveDate->setFocusPolicy(QWidget::StrongFocus);
    effectiveDate->setBackgroundMode(QWidget::PaletteBase);
    effectiveDate->setText( "" );
    effectiveDate->setMaxLength( 10 );
    effectiveDate->setFrame( QLineEdit::Normal );
    effectiveDate->setFrame( TRUE );
    effectiveDate->setAlignment( AlignLeft );

    saveButton = new QPushButton(this, "PushButton_1");
    saveButton->setGeometry(90, 115, 100, 30);
    saveButton->setMinimumSize(10, 10);
    saveButton->setMaximumSize(32767, 32767);
    saveButton->setFocusPolicy(QWidget::TabFocus);
    saveButton->setBackgroundMode(QWidget::PaletteButton);
    saveButton->setText( "&Save" );
    saveButton->setAutoRepeat( FALSE );
    saveButton->setAutoResize( FALSE );
    saveButton->setToggleButton( FALSE );
    saveButton->setDefault( FALSE );
    saveButton->setAutoDefault( FALSE );
    saveButton->setIsMenuButton( FALSE );
    connect(saveButton, SIGNAL(clicked()), SLOT(saveBillingCycleChange()));

    cancelButton = new QPushButton(this, "PushButton_2");
    cancelButton->setGeometry(205, 115, 100, 30);
    cancelButton->setMinimumSize(10, 10);
    cancelButton->setMaximumSize(32767, 32767);
    cancelButton->setFocusPolicy(QWidget::TabFocus);
    cancelButton->setBackgroundMode(QWidget::PaletteButton);
    cancelButton->setText( "&Cancel" );
    cancelButton->setAutoRepeat( FALSE );
    cancelButton->setAutoResize( FALSE );
    cancelButton->setToggleButton( FALSE );
    cancelButton->setDefault( FALSE );
    cancelButton->setAutoDefault( FALSE );
    cancelButton->setIsMenuButton( FALSE );
    connect(cancelButton, SIGNAL(clicked()), SLOT(cancelBillingCycleChange()));

    QLabel *qtarch_Label_3 = new QLabel(this, "Label_3");
    qtarch_Label_3->setGeometry(15, 10, 100, 20);
    qtarch_Label_3->setMinimumSize(10, 10);
    qtarch_Label_3->setMaximumSize(32767, 32767);
    qtarch_Label_3->setFocusPolicy(QWidget::NoFocus);
    qtarch_Label_3->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_Label_3->setFrameStyle( 0 );
    qtarch_Label_3->setLineWidth( 1 );
    qtarch_Label_3->setMidLineWidth( 0 );
    qtarch_Label_3->QFrame::setMargin( -1 );
    qtarch_Label_3->setText( "Customer:" );
    qtarch_Label_3->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_Label_3->setMargin( -1 );

    customerLabel = new QLabel(this, "Label_4");
    customerLabel->setGeometry(120, 10, 265, 20);
    customerLabel->setMinimumSize(10, 10);
    customerLabel->setMaximumSize(32767, 32767);
    customerLabel->setFocusPolicy(QWidget::NoFocus);
    customerLabel->setBackgroundMode(QWidget::PaletteBackground);
    customerLabel->setFrameStyle( 0 );
    customerLabel->setLineWidth( 1 );
    customerLabel->setMidLineWidth( 0 );
    customerLabel->QFrame::setMargin( -1 );
    customerLabel->setText( "" );
    customerLabel->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    customerLabel->setMargin( -1 );

    resize(400,170);
    setMinimumSize(400, 170);
    setMaximumSize(400, 170);
}

ChangeBillingCycleData::~ChangeBillingCycleData()
{
}
