/**********************************************************************

	--- Qt Architect generated file ---

	File: CustCallDetailData.h
	Last generated: Wed May 12 15:47:16 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CustCallDetailData_included
#define CustCallDetailData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qpushbt.h>
#include <qmultilineedit.h>

class CustCallDetailData : public QWidget
{
    Q_OBJECT

public:

    CustCallDetailData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CustCallDetailData();

public slots:


protected slots:

    virtual void nextCall();
    virtual void previousCall();
    virtual void closeClicked();

protected:
    QLabel* titleLabel;
    QLabel* callDate;
    QLabel* callStartTime;
    QLabel* stopDate;
    QLabel* stopTime;
    QLabel* callDuration;
    QLabel* callType;
    QLabel* takenBy;
    QLabel* loginID;
    QLabel* category;
    QLabel* topic;
    QMultiLineEdit* solution;
    QLabel* callNumber;
    QPushButton* previousButton;
    QPushButton* nextButton;

};

#endif // CustCallDetailData_included
