/**********************************************************************

	--- Qt Architect generated file ---

	File: CustChargeEditData.h
	Last generated: Sat May 6 10:31:27 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CustChargeEditData_included
#define CustChargeEditData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qcheckbox.h>
#include <qcombobox.h>
#include <qmultilinedit.h>
#include "calendar.h"
#include <qlineedit.h>

class CustChargeEditData : public QWidget
{
    Q_OBJECT

public:

    CustChargeEditData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~CustChargeEditData();

    protected slots:

    virtual void cancelPressed() =0;
    virtual void itemChanged(int) =0;
    virtual void priceChanged(const QString&) =0;
    virtual void saveCharge() =0;
    virtual void quantityChanged(const QString&) =0;

    protected:

    QLabel *custNameLabel;
    QComboBox *loginList;
    QComboBox *itemList;
    QLineEdit *quantity;
    QLineEdit *price;
    QLabel *ratePlanLabel;
    QLabel *cycleLabel;
    QLineEdit *units;
    QLabel *totalCharge;
    QCheckBox *taxable;
    QMultiLineEdit *memo;
    DateInput *chargeDate;
    DateInput *startDate;
    DateInput *stopDate;
};

#endif // CustChargeEditData_included
