/**********************************************************************

	--- Qt Architect generated file ---

	File: CustomerPickerData.h
	Last generated: Wed May 12 18:57:07 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CustomerPickerData_included
#define CustomerPickerData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qlistview.h>
#include <qpushbt.h>
#include <qlined.h>

class CustomerPickerData : public QWidget
{
    Q_OBJECT

public:

    CustomerPickerData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CustomerPickerData();

public slots:


protected slots:

    virtual void listQueryS();
    virtual void itemSelChanged(QListViewItem*);
    virtual void clearQuery();
    virtual void itemDoubleClicked(QListViewItem*);
    virtual void itemEnterHit(QListViewItem*);

protected:
    QLabel* queryLabel;
    QLineEdit* listQuery;
    QPushButton* clearButton;
    QListView* list;

};

#endif // CustomerPickerData_included
