/**********************************************************************

	--- Qt Architect generated file ---

	File: CustomerPickerData.cpp
	Last generated: Wed May 12 18:57:07 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "CustomerPickerData.h"

#define Inherited QWidget


CustomerPickerData::CustomerPickerData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	queryLabel = new QLabel( this, "QueryLabel" );
	queryLabel->setGeometry( 5, 5, 60, 20 );
	queryLabel->setMinimumSize( 60, 20 );
	queryLabel->setMaximumSize( 60, 20 );
	queryLabel->setFocusPolicy( QWidget::NoFocus );
	queryLabel->setBackgroundMode( QWidget::PaletteBackground );
	queryLabel->setText( "&Query:" );
	queryLabel->setAlignment( 290 );
	queryLabel->setMargin( -1 );

	listQuery = new QLineEdit( this, "QueryEntry" );
	listQuery->setGeometry( 65, 5, 295, 20 );
	listQuery->setMinimumSize( 40, 20 );
	listQuery->setMaximumSize( 32767, 20 );
	connect( listQuery, SIGNAL(returnPressed()), SLOT(listQueryS()) );
	listQuery->setFocusPolicy( QWidget::StrongFocus );
	listQuery->setBackgroundMode( QWidget::PaletteBase );
	listQuery->setText( "" );
	listQuery->setMaxLength( 32767 );
	listQuery->setEchoMode( QLineEdit::Normal );
	listQuery->setFrame( TRUE );

	clearButton = new QPushButton( this, "ClearButton" );
	clearButton->setGeometry( 360, 5, 60, 20 );
	clearButton->setMinimumSize( 60, 20 );
	clearButton->setMaximumSize( 60, 20 );
	connect( clearButton, SIGNAL(clicked()), SLOT(clearQuery()) );
	clearButton->setFocusPolicy( QWidget::TabFocus );
	clearButton->setBackgroundMode( QWidget::PaletteBackground );
	clearButton->setText( "C&lear" );
	clearButton->setAutoRepeat( FALSE );
	clearButton->setAutoResize( FALSE );

	list = new QListView( this, "List" );
	list->setGeometry( 5, 25, 415, 240 );
	list->setMinimumSize( 100, 50 );
	list->setMaximumSize( 32767, 32767 );
	connect( list, SIGNAL(currentChanged(QListViewItem*)), SLOT(itemSelChanged(QListViewItem*)) );
	connect( list, SIGNAL(doubleClicked(QListViewItem*)), SLOT(itemDoubleClicked(QListViewItem*)) );
	connect( list, SIGNAL(returnPressed(QListViewItem*)), SLOT(itemEnterHit(QListViewItem*)) );
	list->setFocusPolicy( QWidget::TabFocus );
	list->setBackgroundMode( QWidget::PaletteBackground );
	list->setResizePolicy( QScrollView::Manual );
	list->setVScrollBarMode( QScrollView::Auto );
	list->setHScrollBarMode( QScrollView::Auto );
	list->setTreeStepSize( 20 );
	list->setMultiSelection( FALSE );
	list->setAllColumnsShowFocus( TRUE );
	list->setItemMargin( 1 );
	list->setRootIsDecorated( TRUE );
	list->addColumn( "Customer Name", -1 );
	list->setColumnWidthMode( 0, QListView::Maximum );
	list->setColumnAlignment( 0, 1 );
	list->addColumn( "Cust ID", -1 );
	list->setColumnWidthMode( 1, QListView::Maximum );
	list->setColumnAlignment( 1, 1 );
	list->addColumn( "Login ID", -1 );
	list->setColumnWidthMode( 2, QListView::Maximum );
	list->setColumnAlignment( 2, 1 );
	list->addColumn( "Balance", -1 );
	list->setColumnWidthMode( 3, QListView::Maximum );
	list->setColumnAlignment( 3, 2 );
	list->addColumn( "A", -1 );
	list->setColumnWidthMode( 4, QListView::Maximum );
	list->setColumnAlignment( 4, 4 );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 0, NULL );
	qtarch_layout_1->addStrut( 0 );
	QGridLayout* qtarch_layout_1_1 = new QGridLayout( 1, 3, 0, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 0 );
	qtarch_layout_1_1->addColSpacing( 0, 5 );
	qtarch_layout_1_1->setColStretch( 0, 0 );
	qtarch_layout_1_1->addColSpacing( 1, 5 );
	qtarch_layout_1_1->setColStretch( 1, 1 );
	qtarch_layout_1_1->addColSpacing( 2, 5 );
	qtarch_layout_1_1->setColStretch( 2, 0 );
	qtarch_layout_1_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_1->setRowStretch( 0, 1 );
	qtarch_layout_1_1->addWidget( queryLabel, 0, 0, 33 );
	qtarch_layout_1_1->addWidget( listQuery, 0, 1, 33 );
	qtarch_layout_1_1->addWidget( clearButton, 0, 2, 34 );
	qtarch_layout_1->addWidget( list, 1, 33 );
	resize( 425,270 );
	setMinimumSize( 50, 50 );
	setMaximumSize( 32767, 32767 );
}


CustomerPickerData::~CustomerPickerData()
{
}
void CustomerPickerData::listQueryS()
{
}
void CustomerPickerData::clearQuery()
{
}
void CustomerPickerData::itemSelChanged(QListViewItem*)
{
}
void CustomerPickerData::itemDoubleClicked(QListViewItem*)
{
}
void CustomerPickerData::itemEnterHit(QListViewItem*)
{
}
