/**********************************************************************

	--- Qt Architect generated file ---

	File: CustChargeEditData.cpp
	Last generated: Sat May 6 10:31:27 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "CustChargeEditData.h"

#include <qlabel.h>
#include <qpushbutton.h>

CustChargeEditData::CustChargeEditData(QWidget *parent, const char *name)
                   : QWidget(parent, name, 0)
{
    QLabel *qtarch_CustomerIDLabel1 = new QLabel(this, "CustomerIDLabel1");
    qtarch_CustomerIDLabel1->setGeometry(5, 5, 70, 13);
    qtarch_CustomerIDLabel1->setMinimumSize(0, 0);
    qtarch_CustomerIDLabel1->setMaximumSize(32767, 32767);
    qtarch_CustomerIDLabel1->setFocusPolicy(QWidget::NoFocus);
    qtarch_CustomerIDLabel1->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_CustomerIDLabel1->setFrameStyle( 0 );
    qtarch_CustomerIDLabel1->setLineWidth( 1 );
    qtarch_CustomerIDLabel1->setMidLineWidth( 0 );
    qtarch_CustomerIDLabel1->QFrame::setMargin( -1 );
    qtarch_CustomerIDLabel1->setText( "Customer ID:" );
    qtarch_CustomerIDLabel1->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_CustomerIDLabel1->setMargin( -1 );

    custNameLabel = new QLabel(this, "CustomerNameLabel");
    custNameLabel->setGeometry(80, 5, 184, 13);
    custNameLabel->setMinimumSize(0, 0);
    custNameLabel->setMaximumSize(32767, 32767);
    custNameLabel->setFocusPolicy(QWidget::NoFocus);
    custNameLabel->setBackgroundMode(QWidget::PaletteBackground);
    custNameLabel->setFrameStyle( 0 );
    custNameLabel->setLineWidth( 1 );
    custNameLabel->setMidLineWidth( 0 );
    custNameLabel->QFrame::setMargin( -1 );
    custNameLabel->setText( "" );
    custNameLabel->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    custNameLabel->setMargin( -1 );

    QLabel *qtarch_LoginIDLabel = new QLabel(this, "LoginIDLabel");
    qtarch_LoginIDLabel->setGeometry(5, 51, 73, 25);
    qtarch_LoginIDLabel->setMinimumSize(0, 0);
    qtarch_LoginIDLabel->setMaximumSize(32767, 32767);
    qtarch_LoginIDLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_LoginIDLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_LoginIDLabel->setFrameStyle( 0 );
    qtarch_LoginIDLabel->setLineWidth( 1 );
    qtarch_LoginIDLabel->setMidLineWidth( 0 );
    qtarch_LoginIDLabel->QFrame::setMargin( -1 );
    qtarch_LoginIDLabel->setText( "Login ID:" );
    qtarch_LoginIDLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_LoginIDLabel->setMargin( -1 );

    QLabel *qtarch_SpacerBar = new QLabel(this, "SpacerBar");
    qtarch_SpacerBar->setGeometry(5, 41, 525, 5);
    qtarch_SpacerBar->setMinimumSize(10, 5);
    qtarch_SpacerBar->setMaximumSize(32767, 5);
    qtarch_SpacerBar->setFocusPolicy(QWidget::NoFocus);
    qtarch_SpacerBar->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_SpacerBar->setFrameStyle( 20 );
    qtarch_SpacerBar->setLineWidth( 1 );
    qtarch_SpacerBar->setMidLineWidth( 0 );
    qtarch_SpacerBar->QFrame::setMargin( -1 );
    qtarch_SpacerBar->setText( "" );
    qtarch_SpacerBar->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    qtarch_SpacerBar->setMargin( -1 );

    loginList = new QComboBox(FALSE, this, "LoginIDList");
    loginList->setGeometry(83, 51, 182, 25);
    loginList->setMinimumSize(0, 0);
    loginList->setMaximumSize(32767, 32767);
    loginList->setFocusPolicy(QWidget::StrongFocus);
    loginList->setBackgroundMode(QWidget::PaletteBackground);
    loginList->setSizeLimit( 10 );
    loginList->setAutoResize( FALSE );
    loginList->setMaxCount( 2147483647 );
    loginList->setAutoCompletion( FALSE );

    QLabel *qtarch_TransDateLabel = new QLabel(this, "TransDateLabel");
    qtarch_TransDateLabel->setGeometry(5, 81, 73, 25);
    qtarch_TransDateLabel->setMinimumSize(0, 0);
    qtarch_TransDateLabel->setMaximumSize(32767, 32767);
    qtarch_TransDateLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_TransDateLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_TransDateLabel->setFrameStyle( 0 );
    qtarch_TransDateLabel->setLineWidth( 1 );
    qtarch_TransDateLabel->setMidLineWidth( 0 );
    qtarch_TransDateLabel->QFrame::setMargin( -1 );
    qtarch_TransDateLabel->setText( "Charge Date:" );
    qtarch_TransDateLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_TransDateLabel->setMargin( -1 );

    QLabel *qtarch_ItemIDLabel = new QLabel(this, "ItemIDLabel");
    qtarch_ItemIDLabel->setGeometry(270, 81, 74, 25);
    qtarch_ItemIDLabel->setMinimumSize(0, 0);
    qtarch_ItemIDLabel->setMaximumSize(32767, 32767);
    qtarch_ItemIDLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_ItemIDLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_ItemIDLabel->setFrameStyle( 0 );
    qtarch_ItemIDLabel->setLineWidth( 1 );
    qtarch_ItemIDLabel->setMidLineWidth( 0 );
    qtarch_ItemIDLabel->QFrame::setMargin( -1 );
    qtarch_ItemIDLabel->setText( "Item ID:" );
    qtarch_ItemIDLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_ItemIDLabel->setMargin( -1 );

    itemList = new QComboBox(FALSE, this, "ItemIDList");
    itemList->setGeometry(349, 81, 181, 25);
    itemList->setMinimumSize(0, 0);
    itemList->setMaximumSize(32767, 32767);
    itemList->setFocusPolicy(QWidget::StrongFocus);
    itemList->setBackgroundMode(QWidget::PaletteBackground);
    itemList->setSizeLimit( 10 );
    itemList->setAutoResize( FALSE );
    itemList->setMaxCount( 2147483647 );
    itemList->setAutoCompletion( FALSE );
    connect(itemList, SIGNAL(activated(int)), SLOT(itemChanged(int)));

    QLabel *qtarch_QuantityLabel = new QLabel(this, "QuantityLabel");
    qtarch_QuantityLabel->setGeometry(5, 141, 73, 22);
    qtarch_QuantityLabel->setMinimumSize(0, 0);
    qtarch_QuantityLabel->setMaximumSize(32767, 32767);
    qtarch_QuantityLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_QuantityLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_QuantityLabel->setFrameStyle( 0 );
    qtarch_QuantityLabel->setLineWidth( 1 );
    qtarch_QuantityLabel->setMidLineWidth( 0 );
    qtarch_QuantityLabel->QFrame::setMargin( -1 );
    qtarch_QuantityLabel->setText( "Quantity:" );
    qtarch_QuantityLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_QuantityLabel->setMargin( -1 );

    quantity = new QLineEdit(this, "Quantity");
    quantity->setGeometry(83, 141, 182, 22);
    quantity->setMinimumSize(0, 0);
    quantity->setMaximumSize(32767, 32767);
    quantity->setFocusPolicy(QWidget::StrongFocus);
    quantity->setBackgroundMode(QWidget::PaletteBase);
    quantity->setText( "" );
    quantity->setMaxLength( 5 );
    quantity->setFrame( QLineEdit::Normal );
    quantity->setFrame( TRUE );
    quantity->setAlignment( AlignLeft );
    connect(quantity, SIGNAL(textChanged(const QString&)), SLOT(quantityChanged(const QString&)));

    QLabel *qtarch_PriceLabel = new QLabel(this, "PriceLabel");
    qtarch_PriceLabel->setGeometry(349, 141, 66, 22);
    qtarch_PriceLabel->setMinimumSize(0, 0);
    qtarch_PriceLabel->setMaximumSize(32767, 32767);
    qtarch_PriceLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_PriceLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_PriceLabel->setFrameStyle( 0 );
    qtarch_PriceLabel->setLineWidth( 1 );
    qtarch_PriceLabel->setMidLineWidth( 0 );
    qtarch_PriceLabel->QFrame::setMargin( -1 );
    qtarch_PriceLabel->setText( "Price:" );
    qtarch_PriceLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_PriceLabel->setMargin( -1 );

    price = new QLineEdit(this, "Price");
    price->setGeometry(420, 141, 110, 22);
    price->setMinimumSize(0, 0);
    price->setMaximumSize(32767, 32767);
    price->setFocusPolicy(QWidget::StrongFocus);
    price->setBackgroundMode(QWidget::PaletteBase);
    price->setText( "" );
    price->setMaxLength( 32767 );
    price->setFrame( QLineEdit::Normal );
    price->setFrame( TRUE );
    price->setAlignment( AlignLeft );
    connect(price, SIGNAL(textChanged(const QString&)), SLOT(priceChanged(const QString&)));

    QLabel *qtarch_RatePlanLabel = new QLabel(this, "RatePlanLabel");
    qtarch_RatePlanLabel->setGeometry(5, 23, 70, 13);
    qtarch_RatePlanLabel->setMinimumSize(0, 0);
    qtarch_RatePlanLabel->setMaximumSize(32767, 32767);
    qtarch_RatePlanLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_RatePlanLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_RatePlanLabel->setFrameStyle( 0 );
    qtarch_RatePlanLabel->setLineWidth( 1 );
    qtarch_RatePlanLabel->setMidLineWidth( 0 );
    qtarch_RatePlanLabel->QFrame::setMargin( -1 );
    qtarch_RatePlanLabel->setText( "Rate Plan:" );
    qtarch_RatePlanLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_RatePlanLabel->setMargin( -1 );

    QLabel *qtarch_BillingCycleLabel = new QLabel(this, "BillingCycleLabel");
    qtarch_BillingCycleLabel->setGeometry(269, 23, 73, 13);
    qtarch_BillingCycleLabel->setMinimumSize(0, 0);
    qtarch_BillingCycleLabel->setMaximumSize(32767, 32767);
    qtarch_BillingCycleLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_BillingCycleLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_BillingCycleLabel->setFrameStyle( 0 );
    qtarch_BillingCycleLabel->setLineWidth( 1 );
    qtarch_BillingCycleLabel->setMidLineWidth( 0 );
    qtarch_BillingCycleLabel->QFrame::setMargin( -1 );
    qtarch_BillingCycleLabel->setText( "Billing Cycle:" );
    qtarch_BillingCycleLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_BillingCycleLabel->setMargin( -1 );

    ratePlanLabel = new QLabel(this, "RatePlan");
    ratePlanLabel->setGeometry(80, 23, 184, 13);
    ratePlanLabel->setMinimumSize(0, 0);
    ratePlanLabel->setMaximumSize(32767, 32767);
    ratePlanLabel->setFocusPolicy(QWidget::NoFocus);
    ratePlanLabel->setBackgroundMode(QWidget::PaletteBackground);
    ratePlanLabel->setFrameStyle( 0 );
    ratePlanLabel->setLineWidth( 1 );
    ratePlanLabel->setMidLineWidth( 0 );
    ratePlanLabel->QFrame::setMargin( -1 );
    ratePlanLabel->setText( "" );
    ratePlanLabel->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    ratePlanLabel->setMargin( -1 );

    cycleLabel = new QLabel(this, "BillingCycle");
    cycleLabel->setGeometry(347, 23, 183, 13);
    cycleLabel->setMinimumSize(0, 0);
    cycleLabel->setMaximumSize(32767, 32767);
    cycleLabel->setFocusPolicy(QWidget::NoFocus);
    cycleLabel->setBackgroundMode(QWidget::PaletteBackground);
    cycleLabel->setFrameStyle( 0 );
    cycleLabel->setLineWidth( 1 );
    cycleLabel->setMidLineWidth( 0 );
    cycleLabel->QFrame::setMargin( -1 );
    cycleLabel->setText( "" );
    cycleLabel->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    cycleLabel->setMargin( -1 );

    QLabel *qtarch_DescriptionLabel = new QLabel(this, "DescriptionLabel");
    qtarch_DescriptionLabel->setGeometry(5, 195, 65, 99);
    qtarch_DescriptionLabel->setMinimumSize(0, 0);
    qtarch_DescriptionLabel->setMaximumSize(32767, 32767);
    qtarch_DescriptionLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_DescriptionLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_DescriptionLabel->setFrameStyle( 0 );
    qtarch_DescriptionLabel->setLineWidth( 1 );
    qtarch_DescriptionLabel->setMidLineWidth( 0 );
    qtarch_DescriptionLabel->QFrame::setMargin( -1 );
    qtarch_DescriptionLabel->setText( "Description:" );
    qtarch_DescriptionLabel->setAlignment( AlignRight|AlignTop|ExpandTabs );
    qtarch_DescriptionLabel->setMargin( -1 );

    QLabel *qtarch_UnitsLabel = new QLabel(this, "UnitsLabel");
    qtarch_UnitsLabel->setGeometry(5, 168, 73, 22);
    qtarch_UnitsLabel->setMinimumSize(0, 0);
    qtarch_UnitsLabel->setMaximumSize(32767, 32767);
    qtarch_UnitsLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_UnitsLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_UnitsLabel->setFrameStyle( 0 );
    qtarch_UnitsLabel->setLineWidth( 1 );
    qtarch_UnitsLabel->setMidLineWidth( 0 );
    qtarch_UnitsLabel->QFrame::setMargin( -1 );
    qtarch_UnitsLabel->setText( "Units:" );
    qtarch_UnitsLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_UnitsLabel->setMargin( -1 );

    units = new QLineEdit(this, "Units");
    units->setGeometry(83, 168, 182, 22);
    units->setMinimumSize(0, 0);
    units->setMaximumSize(32767, 32767);
    units->setFocusPolicy(QWidget::StrongFocus);
    units->setBackgroundMode(QWidget::PaletteBase);
    units->setText( "" );
    units->setMaxLength( 16 );
    units->setFrame( QLineEdit::Normal );
    units->setFrame( TRUE );
    units->setAlignment( AlignLeft );

    QLabel *qtarch_TotalChargeLabel = new QLabel(this, "TotalChargeLabel");
    qtarch_TotalChargeLabel->setGeometry(270, 168, 74, 22);
    qtarch_TotalChargeLabel->setMinimumSize(0, 0);
    qtarch_TotalChargeLabel->setMaximumSize(32767, 32767);
    qtarch_TotalChargeLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_TotalChargeLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_TotalChargeLabel->setFrameStyle( 0 );
    qtarch_TotalChargeLabel->setLineWidth( 1 );
    qtarch_TotalChargeLabel->setMidLineWidth( 0 );
    qtarch_TotalChargeLabel->QFrame::setMargin( -1 );
    qtarch_TotalChargeLabel->setText( "Total Charge:" );
    qtarch_TotalChargeLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_TotalChargeLabel->setMargin( -1 );

    totalCharge = new QLabel(this, "TotalCharge");
    totalCharge->setGeometry(349, 168, 181, 22);
    totalCharge->setMinimumSize(0, 0);
    totalCharge->setMaximumSize(32767, 32767);
    totalCharge->setFocusPolicy(QWidget::NoFocus);
    totalCharge->setBackgroundMode(QWidget::PaletteBackground);
    totalCharge->setFrameStyle( 0 );
    totalCharge->setLineWidth( 1 );
    totalCharge->setMidLineWidth( 0 );
    totalCharge->QFrame::setMargin( -1 );
    totalCharge->setText( "" );
    totalCharge->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    totalCharge->setMargin( -1 );

    taxable = new QCheckBox(this, "TaxableBox");
    taxable->setGeometry(270, 142, 74, 19);
    taxable->setMinimumSize(0, 0);
    taxable->setMaximumSize(32767, 32767);
    taxable->setFocusPolicy(QWidget::TabFocus);
    taxable->setBackgroundMode(QWidget::PaletteBackground);
    taxable->setText( "Taxable" );
    taxable->setAutoRepeat( FALSE );
    taxable->setAutoResize( FALSE );
    taxable->setChecked( FALSE );

    memo = new QMultiLineEdit(this, "Description");
    memo->setGeometry(75, 195, 455, 99);
    memo->setMinimumSize(0, 0);
    memo->setMaximumSize(32767, 32767);
    memo->setFocusPolicy(QWidget::StrongFocus);
    memo->setBackgroundMode(QWidget::PaletteBase);
    memo->setFrameStyle( 51 );
    memo->setLineWidth( 2 );
    memo->setMidLineWidth( 0 );
    memo->QFrame::setMargin( 0 );
    memo->insertLine( "" );
    memo->setReadOnly( FALSE );
    memo->setOverwriteMode( FALSE );
    memo->setAutoUpdate( TRUE );

    QPushButton *qtarch_CancelButton = new QPushButton(this, "CancelButton");
    qtarch_CancelButton->setGeometry(457, 299, 73, 26);
    qtarch_CancelButton->setMinimumSize(0, 0);
    qtarch_CancelButton->setMaximumSize(32767, 32767);
    qtarch_CancelButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_CancelButton->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_CancelButton->setText( "&Cancel" );
    qtarch_CancelButton->setAutoRepeat( FALSE );
    qtarch_CancelButton->setAutoResize( FALSE );
    qtarch_CancelButton->setToggleButton( FALSE );
    qtarch_CancelButton->setDefault( FALSE );
    qtarch_CancelButton->setAutoDefault( FALSE );
    qtarch_CancelButton->setIsMenuButton( FALSE );
    connect(qtarch_CancelButton, SIGNAL(clicked()), SLOT(cancelPressed()));

    QPushButton *qtarch_SaveButton = new QPushButton(this, "SaveButton");
    qtarch_SaveButton->setGeometry(390, 299, 62, 26);
    qtarch_SaveButton->setMinimumSize(0, 0);
    qtarch_SaveButton->setMaximumSize(32767, 32767);
    qtarch_SaveButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_SaveButton->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_SaveButton->setText( "&Save" );
    qtarch_SaveButton->setAutoRepeat( FALSE );
    qtarch_SaveButton->setAutoResize( FALSE );
    qtarch_SaveButton->setToggleButton( FALSE );
    qtarch_SaveButton->setDefault( FALSE );
    qtarch_SaveButton->setAutoDefault( FALSE );
    qtarch_SaveButton->setIsMenuButton( FALSE );
    connect(qtarch_SaveButton, SIGNAL(clicked()), SLOT(saveCharge()));

    QLabel *qtarch_StartDateLabel = new QLabel(this, "StartDateLabel");
    qtarch_StartDateLabel->setGeometry(5, 111, 73, 25);
    qtarch_StartDateLabel->setMinimumSize(0, 0);
    qtarch_StartDateLabel->setMaximumSize(32767, 32767);
    qtarch_StartDateLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_StartDateLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_StartDateLabel->setFrameStyle( 0 );
    qtarch_StartDateLabel->setLineWidth( 1 );
    qtarch_StartDateLabel->setMidLineWidth( 0 );
    qtarch_StartDateLabel->QFrame::setMargin( -1 );
    qtarch_StartDateLabel->setText( "Start Date:" );
    qtarch_StartDateLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_StartDateLabel->setMargin( -1 );

    QLabel *qtarch_EndDateLabel = new QLabel(this, "EndDateLabel");
    qtarch_EndDateLabel->setGeometry(270, 111, 74, 25);
    qtarch_EndDateLabel->setMinimumSize(0, 0);
    qtarch_EndDateLabel->setMaximumSize(32767, 32767);
    qtarch_EndDateLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_EndDateLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_EndDateLabel->setFrameStyle( 0 );
    qtarch_EndDateLabel->setLineWidth( 1 );
    qtarch_EndDateLabel->setMidLineWidth( 0 );
    qtarch_EndDateLabel->QFrame::setMargin( -1 );
    qtarch_EndDateLabel->setText( "End Date:" );
    qtarch_EndDateLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_EndDateLabel->setMargin( -1 );

    chargeDate = new DateInput(this, "ChargeDate");
    chargeDate->setGeometry(83, 81, 182, 25);
    chargeDate->setMinimumSize(0, 25);
    chargeDate->setMaximumSize(32767, 32767);
    chargeDate->setFocusPolicy(QWidget::NoFocus);
    chargeDate->setBackgroundMode(QWidget::PaletteBackground);

    startDate = new DateInput(this, "StartDate");
    startDate->setGeometry(83, 111, 182, 25);
    startDate->setMinimumSize(0, 25);
    startDate->setMaximumSize(32767, 32767);
    startDate->setFocusPolicy(QWidget::NoFocus);
    startDate->setBackgroundMode(QWidget::PaletteBackground);

    stopDate = new DateInput(this, "StopDate");
    stopDate->setGeometry(349, 111, 181, 25);
    stopDate->setMinimumSize(0, 25);
    stopDate->setMaximumSize(32767, 32767);
    stopDate->setFocusPolicy(QWidget::NoFocus);
    stopDate->setBackgroundMode(QWidget::PaletteBackground);

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QGridLayout* qtarch_layout_1_1 = new QGridLayout( 2, 4, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 0 );
	qtarch_layout_1_1->addColSpacing( 0, 5 );
	qtarch_layout_1_1->setColStretch( 0, 0 );
	qtarch_layout_1_1->addColSpacing( 1, 5 );
	qtarch_layout_1_1->setColStretch( 1, 1 );
	qtarch_layout_1_1->addColSpacing( 2, 5 );
	qtarch_layout_1_1->setColStretch( 2, 0 );
	qtarch_layout_1_1->addColSpacing( 3, 5 );
	qtarch_layout_1_1->setColStretch( 3, 1 );
	qtarch_layout_1_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_1->setRowStretch( 0, 1 );
	qtarch_layout_1_1->addWidget( qtarch_CustomerIDLabel1, 0, 0, 0 );
	qtarch_layout_1_1->addWidget( custNameLabel, 0, 1, 0 );
	qtarch_layout_1_1->addRowSpacing( 1, 0 );
	qtarch_layout_1_1->setRowStretch( 1, 1 );
	qtarch_layout_1_1->addWidget( qtarch_RatePlanLabel, 1, 0, 0 );
	qtarch_layout_1_1->addWidget( ratePlanLabel, 1, 1, 0 );
	qtarch_layout_1_1->addWidget( qtarch_BillingCycleLabel, 1, 2, 0 );
	qtarch_layout_1_1->addWidget( cycleLabel, 1, 3, 0 );
	qtarch_layout_1->addWidget( qtarch_SpacerBar, 1, 0 );
	QGridLayout* qtarch_layout_1_3 = new QGridLayout( 5, 4, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_3, 0 );
	qtarch_layout_1_3->addColSpacing( 0, 5 );
	qtarch_layout_1_3->setColStretch( 0, 0 );
	qtarch_layout_1_3->addColSpacing( 1, 5 );
	qtarch_layout_1_3->setColStretch( 1, 1 );
	qtarch_layout_1_3->addColSpacing( 2, 5 );
	qtarch_layout_1_3->setColStretch( 2, 0 );
	qtarch_layout_1_3->addColSpacing( 3, 5 );
	qtarch_layout_1_3->setColStretch( 3, 1 );
	qtarch_layout_1_3->addRowSpacing( 0, 0 );
	qtarch_layout_1_3->setRowStretch( 0, 1 );
	qtarch_layout_1_3->addWidget( qtarch_LoginIDLabel, 0, 0, 0 );
	qtarch_layout_1_3->addWidget( loginList, 0, 1, 0 );
	qtarch_layout_1_3->addRowSpacing( 1, 0 );
	qtarch_layout_1_3->setRowStretch( 1, 1 );
	qtarch_layout_1_3->addWidget( qtarch_TransDateLabel, 1, 0, 0 );
	qtarch_layout_1_3->addWidget( chargeDate, 1, 1, 0 );
	qtarch_layout_1_3->addWidget( qtarch_ItemIDLabel, 1, 2, 0 );
	qtarch_layout_1_3->addWidget( itemList, 1, 3, 0 );
	qtarch_layout_1_3->addRowSpacing( 2, 0 );
	qtarch_layout_1_3->setRowStretch( 2, 1 );
	qtarch_layout_1_3->addWidget( qtarch_StartDateLabel, 2, 0, 0 );
	qtarch_layout_1_3->addWidget( startDate, 2, 1, 0 );
	qtarch_layout_1_3->addWidget( qtarch_EndDateLabel, 2, 2, 0 );
	qtarch_layout_1_3->addWidget( stopDate, 2, 3, 0 );
	qtarch_layout_1_3->addRowSpacing( 3, 0 );
	qtarch_layout_1_3->setRowStretch( 3, 1 );
	qtarch_layout_1_3->addWidget( qtarch_QuantityLabel, 3, 0, 0 );
	qtarch_layout_1_3->addWidget( quantity, 3, 1, 0 );
	qtarch_layout_1_3->addWidget( taxable, 3, 2, 0 );
	QBoxLayout* qtarch_layout_1_3_4_4 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1_3->addLayout( qtarch_layout_1_3_4_4, 3, 3 );
	qtarch_layout_1_3_4_4->addStrut( 0 );
	qtarch_layout_1_3_4_4->addWidget( qtarch_PriceLabel, 1, 0 );
	qtarch_layout_1_3_4_4->addWidget( price, 1, 0 );
	qtarch_layout_1_3->addRowSpacing( 4, 0 );
	qtarch_layout_1_3->setRowStretch( 4, 1 );
	qtarch_layout_1_3->addWidget( qtarch_UnitsLabel, 4, 0, 0 );
	qtarch_layout_1_3->addWidget( units, 4, 1, 0 );
	qtarch_layout_1_3->addWidget( qtarch_TotalChargeLabel, 4, 2, 0 );
	qtarch_layout_1_3->addWidget( totalCharge, 4, 3, 0 );
	QGridLayout* qtarch_layout_1_4 = new QGridLayout( 1, 2, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_4, 1 );
	qtarch_layout_1_4->addColSpacing( 0, 5 );
	qtarch_layout_1_4->setColStretch( 0, 0 );
	qtarch_layout_1_4->addColSpacing( 1, 5 );
	qtarch_layout_1_4->setColStretch( 1, 1 );
	qtarch_layout_1_4->addRowSpacing( 0, 0 );
	qtarch_layout_1_4->setRowStretch( 0, 1 );
	qtarch_layout_1_4->addWidget( qtarch_DescriptionLabel, 0, 0, 0 );
	qtarch_layout_1_4->addWidget( memo, 0, 1, 0 );
	QBoxLayout* qtarch_layout_1_5 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_5, 0 );
	qtarch_layout_1_5->addStrut( 0 );
	qtarch_layout_1_5->addStretch( 1 );
	qtarch_layout_1_5->addWidget( qtarch_SaveButton, 0, 0 );
	qtarch_layout_1_5->addWidget( qtarch_CancelButton, 0, 0 );
    resize(535,330);
    setMinimumSize(0, 0);
    setMaximumSize(32767, 32767);
}

CustChargeEditData::~CustChargeEditData()
{
}
