/**********************************************************************

	--- Qt Architect generated file ---

	File: CustCallDetailData.cpp
	Last generated: Wed May 12 15:47:16 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "CustCallDetailData.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qpushbt.h>

CustCallDetailData::CustCallDetailData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	titleLabel = new QLabel( this, "TitleLabel" );
	titleLabel->setGeometry( 5, 5, 495, 50 );
	titleLabel->setMinimumSize( 20, 50 );
	titleLabel->setMaximumSize( 32762, 50 );
	{
		QFont font( "helvetica", 12, 63, 0 );
		font.setStyleHint( (QFont::StyleHint)0 );
		//font.setCharSet( (QFont::CharSet)0 );
		titleLabel->setFont( font );
	}
	titleLabel->setFocusPolicy( QWidget::NoFocus );
	titleLabel->setBackgroundMode( QWidget::PaletteBackground );
	titleLabel->setText( "Customer Call Detail" );
	titleLabel->setAlignment( 292 );
	titleLabel->setMargin( -1 );

	QLabel* qtarch_CallDateLabel;
	qtarch_CallDateLabel = new QLabel( this, "CallDateLabel" );
	qtarch_CallDateLabel->setGeometry( 5, 81, 80, 20 );
	qtarch_CallDateLabel->setMinimumSize( 80, 20 );
	qtarch_CallDateLabel->setMaximumSize( 80, 20 );
	qtarch_CallDateLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_CallDateLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_CallDateLabel->setText( "Call Date:" );
	qtarch_CallDateLabel->setAlignment( 290 );
	qtarch_CallDateLabel->setMargin( -1 );

	callDate = new QLabel( this, "CallDate" );
	callDate->setGeometry( 86, 81, 140, 20 );
	callDate->setMinimumSize( 140, 20 );
	callDate->setMaximumSize( 140, 20 );
	callDate->setFocusPolicy( QWidget::NoFocus );
	callDate->setBackgroundMode( QWidget::PaletteBackground );
	callDate->setText( "WWW MMM 00, 0000" );
	callDate->setAlignment( 289 );
	callDate->setMargin( -1 );

	callStartTime = new QLabel( this, "CallStartTime" );
	callStartTime->setGeometry( 227, 81, 65, 20 );
	callStartTime->setMinimumSize( 65, 20 );
	callStartTime->setMaximumSize( 65, 20 );
	callStartTime->setFocusPolicy( QWidget::NoFocus );
	callStartTime->setBackgroundMode( QWidget::PaletteBackground );
	callStartTime->setText( "00:00:00" );
	callStartTime->setAlignment( 289 );
	callStartTime->setMargin( -1 );

	QLabel* qtarch_StopDateLabel;
	qtarch_StopDateLabel = new QLabel( this, "StopDateLabel" );
	qtarch_StopDateLabel->setGeometry( 5, 102, 80, 20 );
	qtarch_StopDateLabel->setMinimumSize( 80, 20 );
	qtarch_StopDateLabel->setMaximumSize( 80, 20 );
	qtarch_StopDateLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_StopDateLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_StopDateLabel->setText( "Stop Time:" );
	qtarch_StopDateLabel->setAlignment( 290 );
	qtarch_StopDateLabel->setMargin( -1 );

	stopDate = new QLabel( this, "StopDate" );
	stopDate->setGeometry( 86, 102, 140, 20 );
	stopDate->setMinimumSize( 140, 20 );
	stopDate->setMaximumSize( 140, 20 );
	stopDate->setFocusPolicy( QWidget::NoFocus );
	stopDate->setBackgroundMode( QWidget::PaletteBackground );
	stopDate->setText( "0000-00-00" );
	stopDate->setAlignment( 289 );
	stopDate->setMargin( -1 );

	stopTime = new QLabel( this, "StopTime" );
	stopTime->setGeometry( 227, 102, 65, 20 );
	stopTime->setMinimumSize( 65, 20 );
	stopTime->setMaximumSize( 65, 20 );
	stopTime->setFocusPolicy( QWidget::NoFocus );
	stopTime->setBackgroundMode( QWidget::PaletteBackground );
	stopTime->setText( "00:00:00" );
	stopTime->setAlignment( 289 );
	stopTime->setMargin( -1 );

	QLabel* qtarch_DurationLabel;
	qtarch_DurationLabel = new QLabel( this, "DurationLabel" );
	qtarch_DurationLabel->setGeometry( 334, 102, 80, 20 );
	qtarch_DurationLabel->setMinimumSize( 80, 20 );
	qtarch_DurationLabel->setMaximumSize( 80, 20 );
	qtarch_DurationLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_DurationLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_DurationLabel->setText( "Length:" );
	qtarch_DurationLabel->setAlignment( 290 );
	qtarch_DurationLabel->setMargin( -1 );

	callDuration = new QLabel( this, "Duration" );
	callDuration->setGeometry( 415, 102, 85, 20 );
	callDuration->setMinimumSize( 85, 20 );
	callDuration->setMaximumSize( 85, 20 );
	callDuration->setFocusPolicy( QWidget::NoFocus );
	callDuration->setBackgroundMode( QWidget::PaletteBackground );
	callDuration->setText( "00:00:00" );
	callDuration->setAlignment( 289 );
	callDuration->setMargin( -1 );

	QLabel* qtarch_CallTypeLabel;
	qtarch_CallTypeLabel = new QLabel( this, "CallTypeLabel" );
	qtarch_CallTypeLabel->setGeometry( 334, 81, 80, 20 );
	qtarch_CallTypeLabel->setMinimumSize( 80, 20 );
	qtarch_CallTypeLabel->setMaximumSize( 80, 20 );
	qtarch_CallTypeLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_CallTypeLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_CallTypeLabel->setText( "Call Type:" );
	qtarch_CallTypeLabel->setAlignment( 290 );
	qtarch_CallTypeLabel->setMargin( -1 );

	callType = new QLabel( this, "CallType" );
	callType->setGeometry( 415, 81, 85, 20 );
	callType->setMinimumSize( 85, 20 );
	callType->setMaximumSize( 85, 20 );
	callType->setFocusPolicy( QWidget::NoFocus );
	callType->setBackgroundMode( QWidget::PaletteBackground );
	callType->setText( "Incoming" );
	callType->setAlignment( 289 );
	callType->setMargin( -1 );

	QLabel* qtarch_Divider1;
	qtarch_Divider1 = new QLabel( this, "Divider1" );
	qtarch_Divider1->setGeometry( 5, 127, 495, 5 );
	qtarch_Divider1->setMinimumSize( 0, 5 );
	qtarch_Divider1->setMaximumSize( 32767, 5 );
	qtarch_Divider1->setFocusPolicy( QWidget::NoFocus );
	qtarch_Divider1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Divider1->setFrameStyle( 52 );
	qtarch_Divider1->setLineWidth( 2 );
	qtarch_Divider1->setText( "" );
	qtarch_Divider1->setAlignment( 292 );
	qtarch_Divider1->setMargin( -1 );

	QLabel* qtarch_TakeByLabel;
	qtarch_TakeByLabel = new QLabel( this, "TakeByLabel" );
	qtarch_TakeByLabel->setGeometry( 5, 60, 80, 20 );
	qtarch_TakeByLabel->setMinimumSize( 80, 20 );
	qtarch_TakeByLabel->setMaximumSize( 80, 20 );
	qtarch_TakeByLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_TakeByLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_TakeByLabel->setText( "Taken By:" );
	qtarch_TakeByLabel->setAlignment( 290 );
	qtarch_TakeByLabel->setMargin( -1 );

	takenBy = new QLabel( this, "TakenBy" );
	takenBy->setGeometry( 86, 60, 80, 20 );
	takenBy->setMinimumSize( 80, 20 );
	takenBy->setMaximumSize( 80, 20 );
	takenBy->setFocusPolicy( QWidget::NoFocus );
	takenBy->setBackgroundMode( QWidget::PaletteBackground );
	takenBy->setText( "operator" );
	takenBy->setAlignment( 289 );
	takenBy->setMargin( -1 );

	QLabel* qtarch_BlankSpacer1;
	qtarch_BlankSpacer1 = new QLabel( this, "BlankSpacer1" );
	qtarch_BlankSpacer1->setGeometry( 227, 60, 65, 20 );
	qtarch_BlankSpacer1->setMinimumSize( 65, 20 );
	qtarch_BlankSpacer1->setMaximumSize( 65, 20 );
	qtarch_BlankSpacer1->setFocusPolicy( QWidget::NoFocus );
	qtarch_BlankSpacer1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_BlankSpacer1->setText( "" );
	qtarch_BlankSpacer1->setAlignment( 292 );
	qtarch_BlankSpacer1->setMargin( -1 );

	QLabel* qtarch_UserLoginIDLabel;
	qtarch_UserLoginIDLabel = new QLabel( this, "UserLoginIDLabel" );
	qtarch_UserLoginIDLabel->setGeometry( 334, 60, 80, 20 );
	qtarch_UserLoginIDLabel->setMinimumSize( 80, 20 );
	qtarch_UserLoginIDLabel->setMaximumSize( 80, 20 );
	qtarch_UserLoginIDLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_UserLoginIDLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_UserLoginIDLabel->setText( "Login ID:" );
	qtarch_UserLoginIDLabel->setAlignment( 290 );
	qtarch_UserLoginIDLabel->setMargin( -1 );

	loginID = new QLabel( this, "LoginID" );
	loginID->setGeometry( 415, 60, 85, 20 );
	loginID->setMinimumSize( 85, 20 );
	loginID->setMaximumSize( 85, 20 );
	loginID->setFocusPolicy( QWidget::NoFocus );
	loginID->setBackgroundMode( QWidget::PaletteBackground );
	loginID->setText( "loginid" );
	loginID->setAlignment( 289 );
	loginID->setMargin( -1 );

	QLabel* qtarch_CategoryLabel;
	qtarch_CategoryLabel = new QLabel( this, "CategoryLabel" );
	qtarch_CategoryLabel->setGeometry( 5, 137, 80, 20 );
	qtarch_CategoryLabel->setMinimumSize( 80, 20 );
	qtarch_CategoryLabel->setMaximumSize( 80, 20 );
	qtarch_CategoryLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_CategoryLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_CategoryLabel->setText( "Category:" );
	qtarch_CategoryLabel->setAlignment( 290 );
	qtarch_CategoryLabel->setMargin( -1 );

	category = new QLabel( this, "Category" );
	category->setGeometry( 90, 137, 160, 20 );
	category->setMinimumSize( 0, 20 );
	category->setMaximumSize( 32767, 20 );
	category->setFocusPolicy( QWidget::NoFocus );
	category->setBackgroundMode( QWidget::PaletteBackground );
	category->setText( "Category" );
	category->setAlignment( 289 );
	category->setMargin( -1 );

	QLabel* qtarch_TopicLabel;
	qtarch_TopicLabel = new QLabel( this, "TopicLabel" );
	qtarch_TopicLabel->setGeometry( 255, 137, 80, 20 );
	qtarch_TopicLabel->setMinimumSize( 80, 20 );
	qtarch_TopicLabel->setMaximumSize( 80, 20 );
	qtarch_TopicLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_TopicLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_TopicLabel->setText( "Topic:" );
	qtarch_TopicLabel->setAlignment( 290 );
	qtarch_TopicLabel->setMargin( -1 );

	topic = new QLabel( this, "Topic" );
	topic->setGeometry( 340, 137, 160, 20 );
	topic->setMinimumSize( 0, 20 );
	topic->setMaximumSize( 32767, 20 );
	topic->setFocusPolicy( QWidget::NoFocus );
	topic->setBackgroundMode( QWidget::PaletteBackground );
	topic->setText( "Topic" );
	topic->setAlignment( 289 );
	topic->setMargin( -1 );

	solution = new QMultiLineEdit( this, "Solution" );
	solution->setGeometry( 5, 162, 495, 128 );
	solution->setMinimumSize( 0, 0 );
	solution->setMaximumSize( 32767, 32767 );
	solution->setFocusPolicy( QWidget::StrongFocus );
	solution->setBackgroundMode( QWidget::PaletteBase );
	solution->insertLine( "" );
	solution->setReadOnly( TRUE );
	solution->setOverwriteMode( FALSE );

	QLabel* qtarch_CallCountLabel;
	qtarch_CallCountLabel = new QLabel( this, "CallCountLabel" );
	qtarch_CallCountLabel->setGeometry( 5, 295, 80, 20 );
	qtarch_CallCountLabel->setMinimumSize( 80, 20 );
	qtarch_CallCountLabel->setMaximumSize( 80, 20 );
	qtarch_CallCountLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_CallCountLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_CallCountLabel->setText( "Call number " );
	qtarch_CallCountLabel->setAlignment( 290 );
	qtarch_CallCountLabel->setMargin( -1 );

	QPushButton* qtarch_CloseButton;
	qtarch_CloseButton = new QPushButton( this, "CloseButton" );
	qtarch_CloseButton->setGeometry( 430, 295, 70, 20 );
	qtarch_CloseButton->setMinimumSize( 70, 20 );
	qtarch_CloseButton->setMaximumSize( 70, 20 );
	connect( qtarch_CloseButton, SIGNAL(clicked()), SLOT(closeClicked()) );
	qtarch_CloseButton->setFocusPolicy( QWidget::TabFocus );
	qtarch_CloseButton->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_CloseButton->setText( "&Close" );
	qtarch_CloseButton->setAutoRepeat( FALSE );
	qtarch_CloseButton->setAutoResize( FALSE );

	callNumber = new QLabel( this, "CallNumber" );
	callNumber->setGeometry( 90, 295, 80, 20 );
	callNumber->setMinimumSize( 80, 20 );
	callNumber->setMaximumSize( 80, 20 );
	callNumber->setFocusPolicy( QWidget::NoFocus );
	callNumber->setBackgroundMode( QWidget::PaletteBackground );
	callNumber->setText( "x of x" );
	callNumber->setAlignment( 289 );
	callNumber->setMargin( -1 );

	previousButton = new QPushButton( this, "PrevButton" );
	previousButton->setGeometry( 228, 295, 70, 20 );
	previousButton->setMinimumSize( 70, 20 );
	previousButton->setMaximumSize( 70, 20 );
	connect( previousButton, SIGNAL(clicked()), SLOT(previousCall()) );
	previousButton->setFocusPolicy( QWidget::TabFocus );
	previousButton->setBackgroundMode( QWidget::PaletteBackground );
	previousButton->setText( "&Previous" );
	previousButton->setAutoRepeat( FALSE );
	previousButton->setAutoResize( FALSE );

	nextButton = new QPushButton( this, "NextButton" );
	nextButton->setGeometry( 303, 295, 70, 20 );
	nextButton->setMinimumSize( 70, 20 );
	nextButton->setMaximumSize( 70, 20 );
	connect( nextButton, SIGNAL(clicked()), SLOT(nextCall()) );
	nextButton->setFocusPolicy( QWidget::TabFocus );
	nextButton->setBackgroundMode( QWidget::PaletteBackground );
	nextButton->setText( "&Next" );
	nextButton->setAutoRepeat( FALSE );
	nextButton->setAutoResize( FALSE );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QGridLayout* qtarch_layout_1_1 = new QGridLayout( 1, 1, 1, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 0 );
	qtarch_layout_1_1->addColSpacing( 0, 5 );
	qtarch_layout_1_1->setColStretch( 0, 1 );
	qtarch_layout_1_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_1->setRowStretch( 0, 1 );
	qtarch_layout_1_1->addWidget( titleLabel, 0, 0, 36 );
	QGridLayout* qtarch_layout_1_2 = new QGridLayout( 3, 5, 1, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 0 );
	qtarch_layout_1_2->addColSpacing( 0, 5 );
	qtarch_layout_1_2->setColStretch( 0, 0 );
	qtarch_layout_1_2->addColSpacing( 1, 5 );
	qtarch_layout_1_2->setColStretch( 1, 0 );
	qtarch_layout_1_2->addColSpacing( 2, 5 );
	qtarch_layout_1_2->setColStretch( 2, 1 );
	qtarch_layout_1_2->addColSpacing( 3, 5 );
	qtarch_layout_1_2->setColStretch( 3, 1 );
	qtarch_layout_1_2->addColSpacing( 4, 5 );
	qtarch_layout_1_2->setColStretch( 4, 0 );
	qtarch_layout_1_2->addRowSpacing( 0, 0 );
	qtarch_layout_1_2->setRowStretch( 0, 1 );
	qtarch_layout_1_2->addWidget( qtarch_TakeByLabel, 0, 0, 33 );
	qtarch_layout_1_2->addWidget( takenBy, 0, 1, 33 );
	qtarch_layout_1_2->addWidget( qtarch_BlankSpacer1, 0, 2, 33 );
	qtarch_layout_1_2->addWidget( qtarch_UserLoginIDLabel, 0, 3, 34 );
	qtarch_layout_1_2->addWidget( loginID, 0, 4, 34 );
	qtarch_layout_1_2->addRowSpacing( 1, 0 );
	qtarch_layout_1_2->setRowStretch( 1, 1 );
	qtarch_layout_1_2->addWidget( qtarch_CallDateLabel, 1, 0, 33 );
	qtarch_layout_1_2->addWidget( callDate, 1, 1, 33 );
	qtarch_layout_1_2->addWidget( callStartTime, 1, 2, 33 );
	qtarch_layout_1_2->addWidget( qtarch_CallTypeLabel, 1, 3, 34 );
	qtarch_layout_1_2->addWidget( callType, 1, 4, 34 );
	qtarch_layout_1_2->addRowSpacing( 2, 0 );
	qtarch_layout_1_2->setRowStretch( 2, 1 );
	qtarch_layout_1_2->addWidget( qtarch_StopDateLabel, 2, 0, 33 );
	qtarch_layout_1_2->addWidget( stopDate, 2, 1, 33 );
	qtarch_layout_1_2->addWidget( stopTime, 2, 2, 33 );
	qtarch_layout_1_2->addWidget( qtarch_DurationLabel, 2, 3, 34 );
	qtarch_layout_1_2->addWidget( callDuration, 2, 4, 34 );
	QGridLayout* qtarch_layout_1_3 = new QGridLayout( 1, 1, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_3, 0 );
	qtarch_layout_1_3->addColSpacing( 0, 5 );
	qtarch_layout_1_3->setColStretch( 0, 1 );
	qtarch_layout_1_3->addRowSpacing( 0, 0 );
	qtarch_layout_1_3->setRowStretch( 0, 1 );
	qtarch_layout_1_3->addWidget( qtarch_Divider1, 0, 0, 36 );
	QGridLayout* qtarch_layout_1_4 = new QGridLayout( 1, 4, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_4, 0 );
	qtarch_layout_1_4->addColSpacing( 0, 5 );
	qtarch_layout_1_4->setColStretch( 0, 0 );
	qtarch_layout_1_4->addColSpacing( 1, 5 );
	qtarch_layout_1_4->setColStretch( 1, 1 );
	qtarch_layout_1_4->addColSpacing( 2, 5 );
	qtarch_layout_1_4->setColStretch( 2, 0 );
	qtarch_layout_1_4->addColSpacing( 3, 5 );
	qtarch_layout_1_4->setColStretch( 3, 1 );
	qtarch_layout_1_4->addRowSpacing( 0, 0 );
	qtarch_layout_1_4->setRowStretch( 0, 1 );
	qtarch_layout_1_4->addWidget( qtarch_CategoryLabel, 0, 0, 33 );
	qtarch_layout_1_4->addWidget( category, 0, 1, 33 );
	qtarch_layout_1_4->addWidget( qtarch_TopicLabel, 0, 2, 34 );
	qtarch_layout_1_4->addWidget( topic, 0, 3, 34 );
	qtarch_layout_1->addWidget( solution, 1, 36 );
	QGridLayout* qtarch_layout_1_6 = new QGridLayout( 1, 5, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_6, 0 );
	qtarch_layout_1_6->addColSpacing( 0, 5 );
	qtarch_layout_1_6->setColStretch( 0, 0 );
	qtarch_layout_1_6->addColSpacing( 1, 5 );
	qtarch_layout_1_6->setColStretch( 1, 1 );
	qtarch_layout_1_6->addColSpacing( 2, 5 );
	qtarch_layout_1_6->setColStretch( 2, 0 );
	qtarch_layout_1_6->addColSpacing( 3, 5 );
	qtarch_layout_1_6->setColStretch( 3, 0 );
	qtarch_layout_1_6->addColSpacing( 4, 5 );
	qtarch_layout_1_6->setColStretch( 4, 1 );
	qtarch_layout_1_6->addRowSpacing( 0, 5 );
	qtarch_layout_1_6->setRowStretch( 0, 1 );
	qtarch_layout_1_6->addWidget( qtarch_CallCountLabel, 0, 0, 33 );
	qtarch_layout_1_6->addWidget( callNumber, 0, 1, 33 );
	qtarch_layout_1_6->addWidget( previousButton, 0, 2, 36 );
	qtarch_layout_1_6->addWidget( nextButton, 0, 3, 36 );
	qtarch_layout_1_6->addWidget( qtarch_CloseButton, 0, 4, 34 );
	resize( 505,320 );
	setMinimumSize( 200, 200 );
	setMaximumSize( 32767, 32767 );
}


CustCallDetailData::~CustCallDetailData()
{
}
void CustCallDetailData::closeClicked()
{
}
void CustCallDetailData::previousCall()
{
}
void CustCallDetailData::nextCall()
{
}
