/**********************************************************************

	--- Qt Architect generated file ---

	File: DomainChecklistData.h
	Last generated: Mon Jun 29 14:09:00 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef DomainChecklistData_included
#define DomainChecklistData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qchkbox.h>
#include <qlined.h>
#include <qcombo.h>

class DomainChecklistData : public QWidget
{
    Q_OBJECT

public:

    DomainChecklistData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~DomainChecklistData();

public slots:


protected slots:

    virtual void saveClicked();
    virtual void updateClicked();
    virtual void cancelClicked();

protected:
    QLabel* customerID;
    QLabel* customerName;
    QLabel* domainName;
    QLabel* loginID;
    QCheckBox* hostmasterSubmit;
    QCheckBox* internicSubmit;
    QCheckBox* dnsDone;
    QCheckBox* mailDone;
    QCheckBox* vserverDone;
    QCheckBox* internicDone;
    QCheckBox* domainDone;
    QLabel* hostmastDate;
    QLabel* nicReqDate;
    QLabel* dnsDate;
    QLabel* mailDate;
    QLabel* vserverDate;
    QLabel* nicDoneDate;
    QLabel* doneDate;
    QComboBox* processList;
    QComboBox* serverList;
    QLineEdit* ipAddress;
    QLineEdit* nicBillID;
    QLineEdit* nicAdminID;

};

#endif // DomainChecklistData_included
