/**********************************************************************

	--- Qt Architect generated file ---

	File: DomainEditData.h
	Last generated: Tue Nov 3 15:12:03 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef DomainEditData_included
#define DomainEditData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qpushbt.h>
#include <qlined.h>
#include <qcombo.h>

class DomainEditData : public QWidget
{
    Q_OBJECT

public:

    DomainEditData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~DomainEditData();

public slots:


protected slots:

    virtual void cancelDomain();
    virtual void saveDomain();

protected:
    QComboBox* domainType;
    QComboBox* loginID;
    QLineEdit* domainName;
    QPushButton* saveButton;
    QLabel* customerID;
    QLabel* customerName;

};

#endif // DomainEditData_included
