/**********************************************************************

	--- Qt Architect generated file ---

	File: DomainChecklistData.cpp
	Last generated: Mon Jun 29 14:09:00 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "DomainChecklistData.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qpushbt.h>

DomainChecklistData::DomainChecklistData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QLabel* dlgedit_Label_1;
	dlgedit_Label_1 = new QLabel( this, "Label_1" );
	dlgedit_Label_1->setGeometry( 10, 10, 90, 20 );
	dlgedit_Label_1->setMinimumSize( 10, 10 );
	dlgedit_Label_1->setMaximumSize( 32767, 32767 );
	dlgedit_Label_1->setText( "Customer ID:" );
	dlgedit_Label_1->setAlignment( 290 );
	dlgedit_Label_1->setMargin( -1 );

	QLabel* dlgedit_Label_2;
	dlgedit_Label_2 = new QLabel( this, "Label_2" );
	dlgedit_Label_2->setGeometry( 5, 30, 95, 20 );
	dlgedit_Label_2->setMinimumSize( 10, 10 );
	dlgedit_Label_2->setMaximumSize( 32767, 32767 );
	dlgedit_Label_2->setText( "Customer Name:" );
	dlgedit_Label_2->setAlignment( 290 );
	dlgedit_Label_2->setMargin( -1 );

	customerID = new QLabel( this, "Label_6" );
	customerID->setGeometry( 105, 10, 70, 20 );
	customerID->setMinimumSize( 10, 10 );
	customerID->setMaximumSize( 32767, 32767 );
	customerID->setText( "" );
	customerID->setAlignment( 289 );
	customerID->setMargin( -1 );

	customerName = new QLabel( this, "Label_7" );
	customerName->setGeometry( 105, 30, 270, 20 );
	customerName->setMinimumSize( 10, 10 );
	customerName->setMaximumSize( 32767, 32767 );
	customerName->setText( "" );
	customerName->setAlignment( 289 );
	customerName->setMargin( -1 );

	QLabel* dlgedit_Label_8;
	dlgedit_Label_8 = new QLabel( this, "Label_8" );
	dlgedit_Label_8->setGeometry( 5, 50, 95, 20 );
	dlgedit_Label_8->setMinimumSize( 10, 10 );
	dlgedit_Label_8->setMaximumSize( 32767, 32767 );
	dlgedit_Label_8->setText( "Domain Name:" );
	dlgedit_Label_8->setAlignment( 290 );
	dlgedit_Label_8->setMargin( -1 );

	domainName = new QLabel( this, "Label_9" );
	domainName->setGeometry( 105, 50, 275, 20 );
	domainName->setMinimumSize( 10, 10 );
	domainName->setMaximumSize( 32767, 32767 );
	domainName->setText( "" );
	domainName->setAlignment( 289 );
	domainName->setMargin( -1 );

	QLabel* dlgedit_Label_10;
	dlgedit_Label_10 = new QLabel( this, "Label_10" );
	dlgedit_Label_10->setGeometry( 5, 70, 390, 10 );
	dlgedit_Label_10->setMinimumSize( 10, 10 );
	dlgedit_Label_10->setMaximumSize( 32767, 32767 );
	dlgedit_Label_10->setFrameStyle( 52 );
	dlgedit_Label_10->setText( "" );
	dlgedit_Label_10->setAlignment( 289 );
	dlgedit_Label_10->setMargin( -1 );

	QLabel* dlgedit_Label_11;
	dlgedit_Label_11 = new QLabel( this, "Label_11" );
	dlgedit_Label_11->setGeometry( 175, 10, 85, 20 );
	dlgedit_Label_11->setMinimumSize( 10, 10 );
	dlgedit_Label_11->setMaximumSize( 32767, 32767 );
	dlgedit_Label_11->setText( "Login ID:" );
	dlgedit_Label_11->setAlignment( 290 );
	dlgedit_Label_11->setMargin( -1 );

	loginID = new QLabel( this, "Label_12" );
	loginID->setGeometry( 265, 10, 110, 20 );
	loginID->setMinimumSize( 10, 10 );
	loginID->setMaximumSize( 32767, 32767 );
	loginID->setText( "" );
	loginID->setAlignment( 289 );
	loginID->setMargin( -1 );

	hostmasterSubmit = new QCheckBox( this, "CheckBox_1" );
	hostmasterSubmit->setGeometry( 15, 85, 220, 20 );
	hostmasterSubmit->setMinimumSize( 10, 10 );
	hostmasterSubmit->setMaximumSize( 32767, 32767 );
	hostmasterSubmit->setText( "Request submitted to Hostmaster" );
	hostmasterSubmit->setAutoRepeat( FALSE );
	hostmasterSubmit->setAutoResize( FALSE );

	internicSubmit = new QCheckBox( this, "CheckBox_2" );
	internicSubmit->setGeometry( 15, 105, 220, 20 );
	internicSubmit->setMinimumSize( 10, 10 );
	internicSubmit->setMaximumSize( 32767, 32767 );
	internicSubmit->setText( "Request submitted to InterNIC" );
	internicSubmit->setAutoRepeat( FALSE );
	internicSubmit->setAutoResize( FALSE );

	dnsDone = new QCheckBox( this, "CheckBox_3" );
	dnsDone->setGeometry( 15, 125, 220, 20 );
	dnsDone->setMinimumSize( 10, 10 );
	dnsDone->setMaximumSize( 32767, 32767 );
	dnsDone->setText( "DNS records created/updated" );
	dnsDone->setAutoRepeat( FALSE );
	dnsDone->setAutoResize( FALSE );

	mailDone = new QCheckBox( this, "CheckBox_4" );
	mailDone->setGeometry( 15, 145, 220, 20 );
	mailDone->setMinimumSize( 10, 10 );
	mailDone->setMaximumSize( 32767, 32767 );
	mailDone->setText( "Mail system updated" );
	mailDone->setAutoRepeat( FALSE );
	mailDone->setAutoResize( FALSE );

	vserverDone = new QCheckBox( this, "CheckBox_5" );
	vserverDone->setGeometry( 15, 165, 220, 20 );
	vserverDone->setMinimumSize( 10, 10 );
	vserverDone->setMaximumSize( 32767, 32767 );
	vserverDone->setText( "Virtual server setup completed" );
	vserverDone->setAutoRepeat( FALSE );
	vserverDone->setAutoResize( FALSE );

	internicDone = new QCheckBox( this, "CheckBox_6" );
	internicDone->setGeometry( 15, 255, 220, 20 );
	internicDone->setMinimumSize( 10, 10 );
	internicDone->setMaximumSize( 32767, 32767 );
	internicDone->setText( "InterNIC request completed" );
	internicDone->setAutoRepeat( FALSE );
	internicDone->setAutoResize( FALSE );

	domainDone = new QCheckBox( this, "CheckBox_7" );
	domainDone->setGeometry( 15, 315, 220, 20 );
	domainDone->setMinimumSize( 10, 10 );
	domainDone->setMaximumSize( 32767, 32767 );
	domainDone->setText( "Domain released" );
	domainDone->setAutoRepeat( FALSE );
	domainDone->setAutoResize( FALSE );

	hostmastDate = new QLabel( this, "Label_13" );
	hostmastDate->setGeometry( 250, 85, 135, 20 );
	hostmastDate->setMinimumSize( 10, 10 );
	hostmastDate->setMaximumSize( 32767, 32767 );
	hostmastDate->setText( "" );
	hostmastDate->setAlignment( 289 );
	hostmastDate->setMargin( -1 );

	nicReqDate = new QLabel( this, "Label_14" );
	nicReqDate->setGeometry( 250, 105, 135, 20 );
	nicReqDate->setMinimumSize( 10, 10 );
	nicReqDate->setMaximumSize( 32767, 32767 );
	nicReqDate->setText( "" );
	nicReqDate->setAlignment( 289 );
	nicReqDate->setMargin( -1 );

	dnsDate = new QLabel( this, "Label_15" );
	dnsDate->setGeometry( 250, 125, 135, 20 );
	dnsDate->setMinimumSize( 10, 10 );
	dnsDate->setMaximumSize( 32767, 32767 );
	dnsDate->setText( "" );
	dnsDate->setAlignment( 289 );
	dnsDate->setMargin( -1 );

	mailDate = new QLabel( this, "Label_16" );
	mailDate->setGeometry( 250, 145, 135, 20 );
	mailDate->setMinimumSize( 10, 10 );
	mailDate->setMaximumSize( 32767, 32767 );
	mailDate->setText( "" );
	mailDate->setAlignment( 289 );
	mailDate->setMargin( -1 );

	vserverDate = new QLabel( this, "Label_17" );
	vserverDate->setGeometry( 250, 165, 135, 20 );
	vserverDate->setMinimumSize( 10, 10 );
	vserverDate->setMaximumSize( 32767, 32767 );
	vserverDate->setText( "" );
	vserverDate->setAlignment( 289 );
	vserverDate->setMargin( -1 );

	nicDoneDate = new QLabel( this, "Label_18" );
	nicDoneDate->setGeometry( 245, 255, 135, 20 );
	nicDoneDate->setMinimumSize( 10, 10 );
	nicDoneDate->setMaximumSize( 32767, 32767 );
	nicDoneDate->setText( "" );
	nicDoneDate->setAlignment( 289 );
	nicDoneDate->setMargin( -1 );

	doneDate = new QLabel( this, "Label_19" );
	doneDate->setGeometry( 245, 315, 135, 20 );
	doneDate->setMinimumSize( 10, 10 );
	doneDate->setMaximumSize( 32767, 32767 );
	doneDate->setText( "" );
	doneDate->setAlignment( 289 );
	doneDate->setMargin( -1 );

	QLabel* dlgedit_Label_20;
	dlgedit_Label_20 = new QLabel( this, "Label_20" );
	dlgedit_Label_20->setGeometry( 35, 185, 90, 25 );
	dlgedit_Label_20->setMinimumSize( 10, 10 );
	dlgedit_Label_20->setMaximumSize( 32767, 32767 );
	dlgedit_Label_20->setText( "Server:" );
	dlgedit_Label_20->setAlignment( 290 );
	dlgedit_Label_20->setMargin( -1 );

	QLabel* dlgedit_Label_21;
	dlgedit_Label_21 = new QLabel( this, "Label_21" );
	dlgedit_Label_21->setGeometry( 35, 210, 90, 25 );
	dlgedit_Label_21->setMinimumSize( 10, 10 );
	dlgedit_Label_21->setMaximumSize( 32767, 32767 );
	dlgedit_Label_21->setText( "Process:" );
	dlgedit_Label_21->setAlignment( 290 );
	dlgedit_Label_21->setMargin( -1 );

	QLabel* dlgedit_Label_22;
	dlgedit_Label_22 = new QLabel( this, "Label_22" );
	dlgedit_Label_22->setGeometry( 35, 235, 90, 20 );
	dlgedit_Label_22->setMinimumSize( 10, 10 );
	dlgedit_Label_22->setMaximumSize( 32767, 32767 );
	dlgedit_Label_22->setText( "IP Address:" );
	dlgedit_Label_22->setAlignment( 290 );
	dlgedit_Label_22->setMargin( -1 );

	QLabel* dlgedit_Label_23;
	dlgedit_Label_23 = new QLabel( this, "Label_23" );
	dlgedit_Label_23->setGeometry( 35, 275, 90, 20 );
	dlgedit_Label_23->setMinimumSize( 10, 10 );
	dlgedit_Label_23->setMaximumSize( 32767, 32767 );
	dlgedit_Label_23->setText( "NIC Admin ID:" );
	dlgedit_Label_23->setAlignment( 290 );
	dlgedit_Label_23->setMargin( -1 );

	QLabel* dlgedit_Label_24;
	dlgedit_Label_24 = new QLabel( this, "Label_24" );
	dlgedit_Label_24->setGeometry( 35, 295, 90, 20 );
	dlgedit_Label_24->setMinimumSize( 10, 10 );
	dlgedit_Label_24->setMaximumSize( 32767, 32767 );
	dlgedit_Label_24->setText( "NIC Billing ID:" );
	dlgedit_Label_24->setAlignment( 290 );
	dlgedit_Label_24->setMargin( -1 );

	QPushButton* dlgedit_PushButton_3;
	dlgedit_PushButton_3 = new QPushButton( this, "PushButton_3" );
	dlgedit_PushButton_3->setGeometry( 155, 360, 75, 30 );
	dlgedit_PushButton_3->setMinimumSize( 10, 10 );
	dlgedit_PushButton_3->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_3, SIGNAL(clicked()), SLOT(updateClicked()) );
	dlgedit_PushButton_3->setText( "&Update" );
	dlgedit_PushButton_3->setAutoRepeat( FALSE );
	dlgedit_PushButton_3->setAutoResize( FALSE );

	QPushButton* dlgedit_PushButton_4;
	dlgedit_PushButton_4 = new QPushButton( this, "PushButton_4" );
	dlgedit_PushButton_4->setGeometry( 235, 360, 75, 30 );
	dlgedit_PushButton_4->setMinimumSize( 10, 10 );
	dlgedit_PushButton_4->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_4, SIGNAL(clicked()), SLOT(saveClicked()) );
	dlgedit_PushButton_4->setText( "&Save" );
	dlgedit_PushButton_4->setAutoRepeat( FALSE );
	dlgedit_PushButton_4->setAutoResize( FALSE );

	QPushButton* dlgedit_PushButton_5;
	dlgedit_PushButton_5 = new QPushButton( this, "PushButton_5" );
	dlgedit_PushButton_5->setGeometry( 315, 360, 75, 30 );
	dlgedit_PushButton_5->setMinimumSize( 10, 10 );
	dlgedit_PushButton_5->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_5, SIGNAL(clicked()), SLOT(cancelClicked()) );
	dlgedit_PushButton_5->setText( "&Cancel" );
	dlgedit_PushButton_5->setAutoRepeat( FALSE );
	dlgedit_PushButton_5->setAutoResize( FALSE );

	processList = new QComboBox( TRUE, this, "ComboBox_3" );
	processList->setGeometry( 130, 210, 105, 25 );
	processList->setMinimumSize( 10, 10 );
	processList->setMaximumSize( 32767, 32767 );
	processList->setInsertionPolicy( QComboBox::AtBottom );
	processList->setSizeLimit( 10 );
	processList->setAutoResize( FALSE );

	serverList = new QComboBox( TRUE, this, "ComboBox_4" );
	serverList->setGeometry( 130, 185, 105, 25 );
	serverList->setMinimumSize( 10, 10 );
	serverList->setMaximumSize( 32767, 32767 );
	serverList->setInsertionPolicy( QComboBox::AtBottom );
	serverList->setSizeLimit( 10 );
	serverList->setAutoResize( FALSE );
	serverList->insertItem( "mayhem" );
	serverList->insertItem( "zoot" );

	ipAddress = new QLineEdit( this, "LineEdit_3" );
	ipAddress->setGeometry( 130, 235, 105, 20 );
	ipAddress->setMinimumSize( 10, 10 );
	ipAddress->setMaximumSize( 32767, 32767 );
	ipAddress->setText( "" );
	ipAddress->setMaxLength( 15 );
	ipAddress->setEchoMode( QLineEdit::Normal );
	ipAddress->setFrame( TRUE );

	nicBillID = new QLineEdit( this, "LineEdit_5" );
	nicBillID->setGeometry( 130, 295, 105, 20 );
	nicBillID->setMinimumSize( 10, 10 );
	nicBillID->setMaximumSize( 32767, 32767 );
	nicBillID->setText( "" );
	nicBillID->setMaxLength( 15 );
	nicBillID->setEchoMode( QLineEdit::Normal );
	nicBillID->setFrame( TRUE );

	nicAdminID = new QLineEdit( this, "LineEdit_6" );
	nicAdminID->setGeometry( 130, 275, 105, 20 );
	nicAdminID->setMinimumSize( 10, 10 );
	nicAdminID->setMaximumSize( 32767, 32767 );
	nicAdminID->setText( "" );
	nicAdminID->setMaxLength( 15 );
	nicAdminID->setEchoMode( QLineEdit::Normal );
	nicAdminID->setFrame( TRUE );

	resize( 400,410 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


DomainChecklistData::~DomainChecklistData()
{
}
void DomainChecklistData::updateClicked()
{
}
void DomainChecklistData::saveClicked()
{
}
void DomainChecklistData::cancelClicked()
{
}
