/**********************************************************************

	--- Dlgedit generated file ---

	File: DupPhonesData.cpp
	Last generated: Fri Nov 7 21:17:13 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#include "DupPhonesData.h"

#define Inherited QDialog

#include <qframe.h>
#include <qlabel.h>
#include <qpushbt.h>

DupPhonesData::DupPhonesData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE )
{
	QLabel* tmpQLabel;
	tmpQLabel = new QLabel( this, "Label_1" );
	tmpQLabel->setGeometry( 15, 25, 395, 70 );
	tmpQLabel->setText( "The following is a list of customers having a matching phone number.  If this customer is returning to us, then the old account information should be used and updated if necessary.  To create a new customer record, select Continue." );
	tmpQLabel->setAlignment( 1313 );
	tmpQLabel->setMargin( -1 );

	tmpQLabel = new QLabel( this, "Label_2" );
	tmpQLabel->setGeometry( 0, 95, 225, 20 );
	tmpQLabel->setFrameStyle( 35 );
	tmpQLabel->setLineWidth( 2 );
	tmpQLabel->setText( "Customer Name" );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	tmpQLabel = new QLabel( this, "Label_3" );
	tmpQLabel->setGeometry( 225, 95, 100, 20 );
	tmpQLabel->setFrameStyle( 35 );
	tmpQLabel->setLineWidth( 2 );
	tmpQLabel->setText( "Day Phone" );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	tmpQLabel = new QLabel( this, "Label_4" );
	tmpQLabel->setGeometry( 325, 95, 100, 20 );
	tmpQLabel->setFrameStyle( 35 );
	tmpQLabel->setLineWidth( 2 );
	tmpQLabel->setText( "Balance" );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	dupeList = new QListBox( this, "ListBox_1" );
	dupeList->setGeometry( 0, 115, 425, 120 );
	connect( dupeList, SIGNAL(selected(int)), SLOT(viewDupCustomerL(int)) );
	dupeList->setFrameStyle( 51 );
	dupeList->setLineWidth( 2 );

	QPushButton* tmpQPushButton;
	tmpQPushButton = new QPushButton( this, "PushButton_1" );
	tmpQPushButton->setGeometry( 205, 245, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(viewDupCustomer()) );
	tmpQPushButton->setText( "&Edit/View" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	tmpQPushButton = new QPushButton( this, "PushButton_2" );
	tmpQPushButton->setGeometry( 315, 245, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(reject()) );
	tmpQPushButton->setText( "&Continue" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	tmpQLabel = new QLabel( this, "Label_5" );
	tmpQLabel->setGeometry( 0, 0, 425, 25 );
	{
		QFont font( "helvetica", 12, 75, 0 );
		font.setStyleHint( (QFont::StyleHint)0 );
		//font.setCharSet( (QFont::CharSet)0 );
		tmpQLabel->setFont( font );
	}
	tmpQLabel->setText( "One or more phone numbers were found in the database." );
	tmpQLabel->setAlignment( 292 );
	tmpQLabel->setMargin( -1 );

	QFrame* tmpQFrame;
	tmpQFrame = new QFrame( this, "Frame_1" );
	tmpQFrame->setGeometry( 223, 117, 3, 117 );
	tmpQFrame->setFrameStyle( 21 );

	tmpQFrame = new QFrame( this, "Frame_2" );
	tmpQFrame->setGeometry( 323, 117, 3, 116 );
	tmpQFrame->setFrameStyle( 21 );

	tmpQPushButton = new QPushButton( this, "PushButton_3" );
	tmpQPushButton->setGeometry( 95, 245, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(useCustomer()) );
	tmpQPushButton->setText( "&Use" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	resize( 425, 285 );
}


DupPhonesData::~DupPhonesData()
{
}
void DupPhonesData::viewDupCustomerL(int)
{
}
void DupPhonesData::viewDupCustomer()
{
}
void DupPhonesData::useCustomer()
{
}
