/**********************************************************************

	--- Dlgedit generated file ---

	File: DupPhonesData.h
	Last generated: Fri Nov 7 21:17:13 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef DupPhonesData_included
#define DupPhonesData_included

#include <qdialog.h>
#include <qlistbox.h>

class DupPhonesData : public QDialog
{
    Q_OBJECT

public:

    DupPhonesData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~DupPhonesData();

public slots:


protected slots:

    virtual void useCustomer();
    virtual void viewDupCustomer();
    virtual void viewDupCustomerL(int);

protected:
    QListBox* dupeList;

};

#endif // DupPhonesData_included
