/**********************************************************************

	--- Qt Architect generated file ---

	File: ExtendGraceDateData.h
	Last generated: Tue Mar 23 01:22:04 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef ExtendGraceDateData_included
#define ExtendGraceDateData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qspinbox.h>

class ExtendGraceDateData : public QDialog
{
    Q_OBJECT

public:

    ExtendGraceDateData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~ExtendGraceDateData();

public slots:


protected slots:

    virtual void cancelGrace();
    virtual void daysChanged(int);
    virtual void saveGrace();

protected:
    QLabel* titleLabel;
    QSpinBox* extendDays;
    QLabel* currentGraceDate;
    QLabel* newGraceDate;

};

#endif // ExtendGraceDateData_included
