/**********************************************************************

	--- Qt Architect generated file ---

	File: ExtendGraceDateData.cpp
	Last generated: Tue Mar 23 01:22:04 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "ExtendGraceDateData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>

ExtendGraceDateData::ExtendGraceDateData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	titleLabel = new QLabel( this, "Label_1" );
	titleLabel->setGeometry( 10, 10, 240, 45 );
	titleLabel->setMinimumSize( 0, 0 );
	titleLabel->setMaximumSize( 32767, 32767 );
	titleLabel->setFocusPolicy( QWidget::NoFocus );
	titleLabel->setBackgroundMode( QWidget::PaletteBackground );
	titleLabel->setText( "Extending Grace Period for " );
	titleLabel->setAlignment( 1316 );
	titleLabel->setMargin( -1 );

	extendDays = new QSpinBox( this, "SpinBox_1" );
	extendDays->setGeometry( 140, 65, 110, 20 );
	extendDays->setMinimumSize( 0, 0 );
	extendDays->setMaximumSize( 32767, 32767 );
	connect( extendDays, SIGNAL(valueChanged(int)), SLOT(daysChanged(int)) );
	extendDays->setFocusPolicy( QWidget::StrongFocus );
	extendDays->setBackgroundMode( QWidget::PaletteBackground );
	//extendDays->setFrameStyle( 50 );
	//extendDays->setLineWidth( 2 );
	extendDays->setRange( 1, 7 );
	extendDays->setSteps( 1, 0 );
	extendDays->setPrefix( "" );
	extendDays->setSuffix( " day(s)" );
	extendDays->setSpecialValueText( "" );
	extendDays->setWrapping( FALSE );

	QLabel* qtarch_Label_2;
	qtarch_Label_2 = new QLabel( this, "Label_2" );
	qtarch_Label_2->setGeometry( 10, 65, 125, 20 );
	qtarch_Label_2->setMinimumSize( 0, 0 );
	qtarch_Label_2->setMaximumSize( 32767, 32767 );
	qtarch_Label_2->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_2->setText( "Extend grace by:" );
	qtarch_Label_2->setAlignment( 290 );
	qtarch_Label_2->setMargin( -1 );

	QLabel* qtarch_Label_3;
	qtarch_Label_3 = new QLabel( this, "Label_3" );
	qtarch_Label_3->setGeometry( 10, 90, 125, 20 );
	qtarch_Label_3->setMinimumSize( 0, 0 );
	qtarch_Label_3->setMaximumSize( 32767, 32767 );
	qtarch_Label_3->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_3->setText( "Current Grace Ends:" );
	qtarch_Label_3->setAlignment( 290 );
	qtarch_Label_3->setMargin( -1 );

	currentGraceDate = new QLabel( this, "Label_4" );
	currentGraceDate->setGeometry( 145, 90, 105, 20 );
	currentGraceDate->setMinimumSize( 0, 0 );
	currentGraceDate->setMaximumSize( 32767, 32767 );
	currentGraceDate->setFocusPolicy( QWidget::NoFocus );
	currentGraceDate->setBackgroundMode( QWidget::PaletteBackground );
	currentGraceDate->setText( "0000-00-00" );
	currentGraceDate->setAlignment( 289 );
	currentGraceDate->setMargin( -1 );

	QLabel* qtarch_Label_5;
	qtarch_Label_5 = new QLabel( this, "Label_5" );
	qtarch_Label_5->setGeometry( 5, 115, 130, 20 );
	qtarch_Label_5->setMinimumSize( 0, 0 );
	qtarch_Label_5->setMaximumSize( 32767, 32767 );
	qtarch_Label_5->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_5->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_5->setText( "New Grace Ends:" );
	qtarch_Label_5->setAlignment( 290 );
	qtarch_Label_5->setMargin( -1 );

	newGraceDate = new QLabel( this, "Label_6" );
	newGraceDate->setGeometry( 145, 115, 105, 20 );
	newGraceDate->setMinimumSize( 0, 0 );
	newGraceDate->setMaximumSize( 32767, 32767 );
	newGraceDate->setFocusPolicy( QWidget::NoFocus );
	newGraceDate->setBackgroundMode( QWidget::PaletteBackground );
	newGraceDate->setText( "0000-00-00" );
	newGraceDate->setAlignment( 289 );
	newGraceDate->setMargin( -1 );

	QPushButton* qtarch_PushButton_1;
	qtarch_PushButton_1 = new QPushButton( this, "PushButton_1" );
	qtarch_PushButton_1->setGeometry( 140, 150, 70, 25 );
	qtarch_PushButton_1->setMinimumSize( 0, 0 );
	qtarch_PushButton_1->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_1, SIGNAL(clicked()), SLOT(cancelGrace()) );
	qtarch_PushButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_1->setText( "&Cancel" );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_2;
	qtarch_PushButton_2 = new QPushButton( this, "PushButton_2" );
	qtarch_PushButton_2->setGeometry( 55, 150, 70, 25 );
	qtarch_PushButton_2->setMinimumSize( 0, 0 );
	qtarch_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_2, SIGNAL(clicked()), SLOT(saveGrace()) );
	qtarch_PushButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_2->setText( "&Save" );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );
	qtarch_PushButton_2->setAutoDefault( TRUE );

	resize( 255,190 );
	setMinimumSize( 255, 190 );
	setMaximumSize( 255, 190 );
}


ExtendGraceDateData::~ExtendGraceDateData()
{
}
void ExtendGraceDateData::daysChanged(int)
{
}
void ExtendGraceDateData::cancelGrace()
{
}
void ExtendGraceDateData::saveGrace()
{
}
