/**********************************************************************

	--- Qt Architect generated file ---

	File: NCWAccountData.h
	Last generated: Mon Mar 27 19:12:53 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef NCWAccountData_included
#define NCWAccountData_included

#include <qwidget.h>
#include <qpushbutton.h>
#include <qcombobox.h>
#include "qtextview.h"
#include <qlineedit.h>

class NCWAccountData : public QWidget
{
    Q_OBJECT

public:

    NCWAccountData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~NCWAccountData();

    protected slots:

    virtual void generatePassword() =0;

    protected:

    QTextView *helpText;
    QLineEdit *loginID;
    QLineEdit *password;
    QPushButton *generateButton;
    QComboBox *loginTypeList;
    QComboBox *OSList;
    QComboBox *packageList;
    QComboBox *ratePlanList;
};

#endif // NCWAccountData_included
