/**********************************************************************

	--- Qt Architect generated file ---

	File: NCWBillingData.h
	Last generated: Mon Mar 27 19:04:32 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef NCWBillingData_included
#define NCWBillingData_included

#include <qwidget.h>
#include <qradiobutton.h>
#include <qcombobox.h>
#include "qtextview.h"
#include <qlineedit.h>

class NCWBillingData : public QWidget
{
    Q_OBJECT

public:

    NCWBillingData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~NCWBillingData();

    protected:

    QTextView *helpText;
    QLineEdit *ccName;
    QLineEdit *ccAddress;
    QLineEdit *ccAddress2;
    QLineEdit *ccCity;
    QLineEdit *ccState;
    QLineEdit *ccZIP;
    QLineEdit *ccPhone;
    QComboBox *cardTypeList;
    QLineEdit *cardNumber;
    QLineEdit *expDate;
    QRadioButton *chargeDate2;
};

#endif // NCWBillingData_included
