/**********************************************************************

	--- Qt Architect generated file ---

	File: NCWBillingData.cpp
	Last generated: Mon Mar 27 19:04:32 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "NCWBillingData.h"

#include <qlabel.h>
#include <qradiobutton.h>
#include <qhbox.h>

NCWBillingData::NCWBillingData(QWidget *parent, const char *name)
               : QWidget(parent, name, 0)
{
    helpText = new QTextView(this, "HelpText");
    helpText->setGeometry(5, 5, 175, 290);
    helpText->setMinimumSize(175, 0);
    helpText->setMaximumSize(175, 32767);
    helpText->setFocusPolicy(QWidget::NoFocus);
    helpText->setBackgroundMode(QWidget::PaletteBackground);

    QLabel *qtarch_CCNameLabel = new QLabel(this, "CCNameLabel");
    qtarch_CCNameLabel->setGeometry(185, 5, 145, 22);
    qtarch_CCNameLabel->setMinimumSize(0, 0);
    qtarch_CCNameLabel->setMaximumSize(32767, 32767);
    qtarch_CCNameLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_CCNameLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_CCNameLabel->setFrameStyle( 0 );
    qtarch_CCNameLabel->setLineWidth( 1 );
    qtarch_CCNameLabel->setMidLineWidth( 0 );
    qtarch_CCNameLabel->QFrame::setMargin( 0 );
    qtarch_CCNameLabel->setText( "Cardholder Name:" );
    qtarch_CCNameLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_CCNameLabel->setMargin( 0 );

    ccName = new QLineEdit(this, "CCName");
    ccName->setGeometry(332, 5, 163, 22);
    ccName->setMinimumSize(0, 0);
    ccName->setMaximumSize(32767, 32767);
    ccName->setFocusPolicy(QWidget::StrongFocus);
    ccName->setBackgroundMode(QWidget::PaletteBase);
    ccName->setText( "" );
    ccName->setMaxLength( 80 );
    ccName->setFrame( QLineEdit::Normal );
    ccName->setFrame( TRUE );
    ccName->setAlignment( AlignLeft );

    ccAddress = new QLineEdit(this, "CCAddress");
    ccAddress->setGeometry(332, 29, 163, 22);
    ccAddress->setMinimumSize(0, 0);
    ccAddress->setMaximumSize(32767, 32767);
    ccAddress->setFocusPolicy(QWidget::StrongFocus);
    ccAddress->setBackgroundMode(QWidget::PaletteBase);
    ccAddress->setText( "" );
    ccAddress->setMaxLength( 80 );
    ccAddress->setFrame( QLineEdit::Normal );
    ccAddress->setFrame( TRUE );
    ccAddress->setAlignment( AlignLeft );

    QLabel *qtarch_StatementAddressLabel = new QLabel(this, "StatementAddressLabel");
    qtarch_StatementAddressLabel->setGeometry(185, 29, 145, 22);
    qtarch_StatementAddressLabel->setMinimumSize(0, 0);
    qtarch_StatementAddressLabel->setMaximumSize(32767, 32767);
    qtarch_StatementAddressLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_StatementAddressLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_StatementAddressLabel->setFrameStyle( 0 );
    qtarch_StatementAddressLabel->setLineWidth( 1 );
    qtarch_StatementAddressLabel->setMidLineWidth( 0 );
    qtarch_StatementAddressLabel->QFrame::setMargin( 0 );
    qtarch_StatementAddressLabel->setText( "Cardholder Address:" );
    qtarch_StatementAddressLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_StatementAddressLabel->setMargin( 0 );

    ccAddress2 = new QLineEdit(this, "CCAddress2");
    ccAddress2->setGeometry(332, 53, 163, 22);
    ccAddress2->setMinimumSize(0, 0);
    ccAddress2->setMaximumSize(32767, 32767);
    ccAddress2->setFocusPolicy(QWidget::StrongFocus);
    ccAddress2->setBackgroundMode(QWidget::PaletteBase);
    ccAddress2->setText( "" );
    ccAddress2->setMaxLength( 80 );
    ccAddress2->setFrame( QLineEdit::Normal );
    ccAddress2->setFrame( TRUE );
    ccAddress2->setAlignment( AlignLeft );

    QLabel *qtarch_CityStateZIPLabel = new QLabel(this, "CityStateZIPLabel");
    qtarch_CityStateZIPLabel->setGeometry(185, 77, 145, 22);
    qtarch_CityStateZIPLabel->setMinimumSize(0, 0);
    qtarch_CityStateZIPLabel->setMaximumSize(32767, 32767);
    qtarch_CityStateZIPLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_CityStateZIPLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_CityStateZIPLabel->setFrameStyle( 0 );
    qtarch_CityStateZIPLabel->setLineWidth( 1 );
    qtarch_CityStateZIPLabel->setMidLineWidth( 0 );
    qtarch_CityStateZIPLabel->QFrame::setMargin( 0 );
    qtarch_CityStateZIPLabel->setText( "City, State, ZIP:" );
    qtarch_CityStateZIPLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_CityStateZIPLabel->setMargin( 0 );

    ccCity = new QLineEdit(this, "CCCity");
    ccCity->setGeometry(332, 77, 64, 22);
    ccCity->setMinimumSize(0, 0);
    ccCity->setMaximumSize(32767, 32767);
    ccCity->setFocusPolicy(QWidget::StrongFocus);
    ccCity->setBackgroundMode(QWidget::PaletteBase);
    ccCity->setText( "" );
    ccCity->setMaxLength( 40 );
    ccCity->setFrame( QLineEdit::Normal );
    ccCity->setFrame( TRUE );
    ccCity->setAlignment( AlignLeft );

    ccState = new QLineEdit(this, "CCState");
    ccState->setGeometry(398, 77, 30, 22);
    ccState->setMinimumSize(30, 0);
    ccState->setMaximumSize(30, 32767);
    ccState->setFocusPolicy(QWidget::StrongFocus);
    ccState->setBackgroundMode(QWidget::PaletteBase);
    ccState->setText( "" );
    ccState->setMaxLength( 2 );
    ccState->setFrame( QLineEdit::Normal );
    ccState->setFrame( TRUE );
    ccState->setAlignment( AlignLeft );

    ccZIP = new QLineEdit(this, "CCZIP");
    ccZIP->setGeometry(430, 77, 65, 22);
    ccZIP->setMinimumSize(65, 0);
    ccZIP->setMaximumSize(65, 32767);
    ccZIP->setFocusPolicy(QWidget::StrongFocus);
    ccZIP->setBackgroundMode(QWidget::PaletteBase);
    ccZIP->setText( "" );
    ccZIP->setMaxLength( 10 );
    ccZIP->setFrame( QLineEdit::Normal );
    ccZIP->setFrame( TRUE );
    ccZIP->setAlignment( AlignLeft );

    QLabel *qtarch_CCPhoneLabel = new QLabel(this, "CCPhoneLabel");
    qtarch_CCPhoneLabel->setGeometry(185, 101, 145, 22);
    qtarch_CCPhoneLabel->setMinimumSize(0, 0);
    qtarch_CCPhoneLabel->setMaximumSize(32767, 32767);
    qtarch_CCPhoneLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_CCPhoneLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_CCPhoneLabel->setFrameStyle( 0 );
    qtarch_CCPhoneLabel->setLineWidth( 1 );
    qtarch_CCPhoneLabel->setMidLineWidth( 0 );
    qtarch_CCPhoneLabel->QFrame::setMargin( 0 );
    qtarch_CCPhoneLabel->setText( "Phone Number:" );
    qtarch_CCPhoneLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_CCPhoneLabel->setMargin( 0 );

    ccPhone = new QLineEdit(this, "CCPhoneNumber");
    ccPhone->setGeometry(332, 101, 163, 22);
    ccPhone->setMinimumSize(0, 0);
    ccPhone->setMaximumSize(32767, 32767);
    ccPhone->setFocusPolicy(QWidget::StrongFocus);
    ccPhone->setBackgroundMode(QWidget::PaletteBase);
    ccPhone->setText( "" );
    ccPhone->setMaxLength( 12 );
    ccPhone->setFrame( QLineEdit::Normal );
    ccPhone->setFrame( TRUE );
    ccPhone->setAlignment( AlignLeft );

    QLabel *qtarch_CardTypeLabel = new QLabel(this, "CardTypeLabel");
    qtarch_CardTypeLabel->setGeometry(185, 125, 145, 25);
    qtarch_CardTypeLabel->setMinimumSize(0, 0);
    qtarch_CardTypeLabel->setMaximumSize(32767, 32767);
    qtarch_CardTypeLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_CardTypeLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_CardTypeLabel->setFrameStyle( 0 );
    qtarch_CardTypeLabel->setLineWidth( 1 );
    qtarch_CardTypeLabel->setMidLineWidth( 0 );
    qtarch_CardTypeLabel->QFrame::setMargin( 0 );
    qtarch_CardTypeLabel->setText( "Card Type:" );
    qtarch_CardTypeLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_CardTypeLabel->setMargin( 0 );

    cardTypeList = new QComboBox(FALSE, this, "CardTypeList");
    cardTypeList->setGeometry(332, 125, 163, 25);
    cardTypeList->setMinimumSize(0, 0);
    cardTypeList->setMaximumSize(32767, 32767);
    cardTypeList->setFocusPolicy(QWidget::StrongFocus);
    cardTypeList->setBackgroundMode(QWidget::NoBackground);
    cardTypeList->setSizeLimit( 10 );
    cardTypeList->setAutoResize( FALSE );
    cardTypeList->setMaxCount( 2147483647 );
    cardTypeList->setAutoCompletion( FALSE );

    QLabel *qtarch_CardNumberLabel = new QLabel(this, "CardNumberLabel");
    qtarch_CardNumberLabel->setGeometry(185, 152, 145, 22);
    qtarch_CardNumberLabel->setMinimumSize(0, 0);
    qtarch_CardNumberLabel->setMaximumSize(32767, 32767);
    qtarch_CardNumberLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_CardNumberLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_CardNumberLabel->setFrameStyle( 0 );
    qtarch_CardNumberLabel->setLineWidth( 1 );
    qtarch_CardNumberLabel->setMidLineWidth( 0 );
    qtarch_CardNumberLabel->QFrame::setMargin( 0 );
    qtarch_CardNumberLabel->setText( "Card Number:" );
    qtarch_CardNumberLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_CardNumberLabel->setMargin( 0 );

    cardNumber = new QLineEdit(this, "CardNumber");
    cardNumber->setGeometry(332, 152, 163, 22);
    cardNumber->setMinimumSize(0, 0);
    cardNumber->setMaximumSize(32767, 32767);
    cardNumber->setFocusPolicy(QWidget::StrongFocus);
    cardNumber->setBackgroundMode(QWidget::PaletteBase);
    cardNumber->setText( "" );
    cardNumber->setMaxLength( 20 );
    cardNumber->setFrame( QLineEdit::Normal );
    cardNumber->setFrame( TRUE );
    cardNumber->setAlignment( AlignLeft );

    QLabel *qtarch_ExpDateLabel = new QLabel(this, "ExpDateLabel");
    qtarch_ExpDateLabel->setGeometry(185, 176, 145, 22);
    qtarch_ExpDateLabel->setMinimumSize(0, 0);
    qtarch_ExpDateLabel->setMaximumSize(32767, 32767);
    qtarch_ExpDateLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_ExpDateLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_ExpDateLabel->setFrameStyle( 0 );
    qtarch_ExpDateLabel->setLineWidth( 1 );
    qtarch_ExpDateLabel->setMidLineWidth( 0 );
    qtarch_ExpDateLabel->QFrame::setMargin( 0 );
    qtarch_ExpDateLabel->setText( "Expiration Date (MM/YY):" );
    qtarch_ExpDateLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_ExpDateLabel->setMargin( 0 );

    expDate = new QLineEdit(this, "ExpDate");
    expDate->setGeometry(332, 176, 163, 22);
    expDate->setMinimumSize(0, 0);
    expDate->setMaximumSize(32767, 32767);
    expDate->setFocusPolicy(QWidget::StrongFocus);
    expDate->setBackgroundMode(QWidget::PaletteBase);
    expDate->setText( "" );
    expDate->setMaxLength( 5 );
    expDate->setFrame( QLineEdit::Normal );
    expDate->setFrame( TRUE );
    expDate->setAlignment( AlignLeft );

    QLabel *qtarch_ChargeDateLabel = new QLabel(this, "ChargeDateLabel");
    qtarch_ChargeDateLabel->setGeometry(185, 200, 145, 19);
    qtarch_ChargeDateLabel->setMinimumSize(0, 0);
    qtarch_ChargeDateLabel->setMaximumSize(32767, 32767);
    qtarch_ChargeDateLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_ChargeDateLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_ChargeDateLabel->setFrameStyle( 0 );
    qtarch_ChargeDateLabel->setLineWidth( 1 );
    qtarch_ChargeDateLabel->setMidLineWidth( 0 );
    qtarch_ChargeDateLabel->QFrame::setMargin( 0 );
    qtarch_ChargeDateLabel->setText( "Charge Date:" );
    qtarch_ChargeDateLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_ChargeDateLabel->setMargin( 0 );

    QHBox *qtarch_ChargeDateGroup = new QHBox(this, "ChargeDateGroup");
    qtarch_ChargeDateGroup->setGeometry(332, 200, 163, 19);
    qtarch_ChargeDateGroup->setMinimumSize(0, 0);
    qtarch_ChargeDateGroup->setMaximumSize(32767, 32767);
    qtarch_ChargeDateGroup->setFocusPolicy(QWidget::NoFocus);
    qtarch_ChargeDateGroup->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_ChargeDateGroup->setFrameStyle( 0 );
    qtarch_ChargeDateGroup->setLineWidth( 1 );
    qtarch_ChargeDateGroup->setMidLineWidth( 0 );
    qtarch_ChargeDateGroup->QFrame::setMargin( 0 );
    qtarch_ChargeDateGroup->setSpacing( 5 );

    QRadioButton *qtarch_chargeDate1 = new QRadioButton(qtarch_ChargeDateGroup, "chargeDate1");
    qtarch_chargeDate1->setGeometry(75, 0, 38, 19);
    qtarch_chargeDate1->setMinimumSize(0, 0);
    qtarch_chargeDate1->setMaximumSize(32767, 32767);
    qtarch_chargeDate1->setFocusPolicy(QWidget::TabFocus);
    qtarch_chargeDate1->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_chargeDate1->setText( "7th" );
    qtarch_chargeDate1->setAutoRepeat( FALSE );
    qtarch_chargeDate1->setAutoResize( FALSE );
    qtarch_chargeDate1->setChecked( TRUE );

    chargeDate2 = new QRadioButton(qtarch_ChargeDateGroup, "chargeDate2");
    chargeDate2->setGeometry(118, 0, 45, 19);
    chargeDate2->setMinimumSize(0, 0);
    chargeDate2->setMaximumSize(32767, 32767);
    chargeDate2->setFocusPolicy(QWidget::TabFocus);
    chargeDate2->setBackgroundMode(QWidget::PaletteBackground);
    chargeDate2->setText( "17th" );
    chargeDate2->setAutoRepeat( FALSE );
    chargeDate2->setAutoResize( FALSE );
    chargeDate2->setChecked( FALSE );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::LeftToRight, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( helpText, 1, 0 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( QBoxLayout::TopToBottom, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 1 );
	qtarch_layout_1_2->addStrut( 0 );
	QGridLayout* qtarch_layout_1_2_1 = new QGridLayout( 9, 2, 2, NULL );
	qtarch_layout_1_2->addLayout( qtarch_layout_1_2_1, 0 );
	qtarch_layout_1_2_1->addColSpacing( 0, 5 );
	qtarch_layout_1_2_1->setColStretch( 0, 0 );
	qtarch_layout_1_2_1->addColSpacing( 1, 5 );
	qtarch_layout_1_2_1->setColStretch( 1, 1 );
	qtarch_layout_1_2_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_2_1->setRowStretch( 0, 1 );
	qtarch_layout_1_2_1->addWidget( qtarch_CCNameLabel, 0, 0, 0 );
	qtarch_layout_1_2_1->addWidget( ccName, 0, 1, 0 );
	qtarch_layout_1_2_1->addRowSpacing( 1, 0 );
	qtarch_layout_1_2_1->setRowStretch( 1, 1 );
	qtarch_layout_1_2_1->addWidget( qtarch_StatementAddressLabel, 1, 0, 0 );
	qtarch_layout_1_2_1->addWidget( ccAddress, 1, 1, 0 );
	qtarch_layout_1_2_1->addRowSpacing( 2, 0 );
	qtarch_layout_1_2_1->setRowStretch( 2, 1 );
	qtarch_layout_1_2_1->addWidget( ccAddress2, 2, 1, 0 );
	qtarch_layout_1_2_1->addRowSpacing( 3, 0 );
	qtarch_layout_1_2_1->setRowStretch( 3, 1 );
	qtarch_layout_1_2_1->addWidget( qtarch_CityStateZIPLabel, 3, 0, 0 );
	QBoxLayout* qtarch_layout_1_2_1_4_2 = new QBoxLayout( QBoxLayout::LeftToRight, 2, NULL );
	qtarch_layout_1_2_1->addLayout( qtarch_layout_1_2_1_4_2, 3, 1 );
	qtarch_layout_1_2_1_4_2->addStrut( 0 );
	qtarch_layout_1_2_1_4_2->addWidget( ccCity, 1, 0 );
	qtarch_layout_1_2_1_4_2->addWidget( ccState, 1, 0 );
	qtarch_layout_1_2_1_4_2->addWidget( ccZIP, 1, 0 );
	qtarch_layout_1_2_1->addRowSpacing( 4, 0 );
	qtarch_layout_1_2_1->setRowStretch( 4, 1 );
	qtarch_layout_1_2_1->addWidget( qtarch_CCPhoneLabel, 4, 0, 0 );
	qtarch_layout_1_2_1->addWidget( ccPhone, 4, 1, 0 );
	qtarch_layout_1_2_1->addRowSpacing( 5, 0 );
	qtarch_layout_1_2_1->setRowStretch( 5, 1 );
	qtarch_layout_1_2_1->addWidget( qtarch_CardTypeLabel, 5, 0, 0 );
	qtarch_layout_1_2_1->addWidget( cardTypeList, 5, 1, 0 );
	qtarch_layout_1_2_1->addRowSpacing( 6, 0 );
	qtarch_layout_1_2_1->setRowStretch( 6, 1 );
	qtarch_layout_1_2_1->addWidget( qtarch_CardNumberLabel, 6, 0, 0 );
	qtarch_layout_1_2_1->addWidget( cardNumber, 6, 1, 0 );
	qtarch_layout_1_2_1->addRowSpacing( 7, 0 );
	qtarch_layout_1_2_1->setRowStretch( 7, 1 );
	qtarch_layout_1_2_1->addWidget( qtarch_ExpDateLabel, 7, 0, 0 );
	qtarch_layout_1_2_1->addWidget( expDate, 7, 1, 0 );
	qtarch_layout_1_2_1->addRowSpacing( 8, 0 );
	qtarch_layout_1_2_1->setRowStretch( 8, 1 );
	qtarch_layout_1_2_1->addWidget( qtarch_ChargeDateLabel, 8, 0, 0 );
	qtarch_layout_1_2_1->addWidget( qtarch_ChargeDateGroup, 8, 1, 0 );
	qtarch_layout_1_2->addStretch( 1 );
    resize(500,300);
    setMinimumSize(0, 0);
    setMaximumSize(32767, 32767);
}

NCWBillingData::~NCWBillingData()
{
}
