/**********************************************************************

	--- Qt Architect generated file ---

	File: NCWContactData.cpp
	Last generated: Mon Mar 27 17:22:41 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "NCWContactData.h"

#include <qlabel.h>

NCWContactData::NCWContactData(QWidget *parent, const char *name)
               : QWidget(parent, name, 0)
{
    helpText = new QTextView(this, "HelpText");
    helpText->setGeometry(5, 5, 175, 290);
    helpText->setMinimumSize(175, 0);
    helpText->setMaximumSize(175, 32767);
    helpText->setFocusPolicy(QWidget::NoFocus);
    helpText->setBackgroundMode(QWidget::PaletteBackground);

    QLabel *qtarch_NameLabel = new QLabel(this, "NameLabel");
    qtarch_NameLabel->setGeometry(185, 5, 83, 22);
    qtarch_NameLabel->setMinimumSize(0, 0);
    qtarch_NameLabel->setMaximumSize(32767, 32767);
    qtarch_NameLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_NameLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_NameLabel->setFrameStyle( 0 );
    qtarch_NameLabel->setLineWidth( 1 );
    qtarch_NameLabel->setMidLineWidth( 0 );
    qtarch_NameLabel->QFrame::setMargin( 0 );
    qtarch_NameLabel->setText( "Name:" );
    qtarch_NameLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_NameLabel->setMargin( 0 );

    QLabel *qtarch_ContactNameLabel = new QLabel(this, "ContactNameLabel");
    qtarch_ContactNameLabel->setGeometry(185, 32, 83, 22);
    qtarch_ContactNameLabel->setMinimumSize(0, 0);
    qtarch_ContactNameLabel->setMaximumSize(32767, 32767);
    qtarch_ContactNameLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_ContactNameLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_ContactNameLabel->setFrameStyle( 0 );
    qtarch_ContactNameLabel->setLineWidth( 1 );
    qtarch_ContactNameLabel->setMidLineWidth( 0 );
    qtarch_ContactNameLabel->QFrame::setMargin( 0 );
    qtarch_ContactNameLabel->setText( "Contact Name:" );
    qtarch_ContactNameLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_ContactNameLabel->setMargin( 0 );

    contactName = new QLineEdit(this, "ContactName");
    contactName->setGeometry(273, 32, 222, 22);
    contactName->setMinimumSize(0, 0);
    contactName->setMaximumSize(32767, 32767);
    contactName->setFocusPolicy(QWidget::StrongFocus);
    contactName->setBackgroundMode(QWidget::PaletteBase);
    contactName->setText( "" );
    contactName->setMaxLength( 80 );
    contactName->setFrame( QLineEdit::Normal );
    contactName->setFrame( TRUE );
    contactName->setAlignment( AlignLeft );

    fullName = new QLineEdit(this, "FullName");
    fullName->setGeometry(273, 5, 222, 22);
    fullName->setMinimumSize(0, 0);
    fullName->setMaximumSize(32767, 32767);
    fullName->setFocusPolicy(QWidget::StrongFocus);
    fullName->setBackgroundMode(QWidget::PaletteBase);
    fullName->setText( "" );
    fullName->setMaxLength( 80 );
    fullName->setFrame( QLineEdit::Normal );
    fullName->setFrame( TRUE );
    fullName->setAlignment( AlignLeft );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::LeftToRight, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( helpText, 1, 0 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( QBoxLayout::TopToBottom, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 1 );
	qtarch_layout_1_2->addStrut( 0 );
	QGridLayout* qtarch_layout_1_2_1 = new QGridLayout( 2, 2, 5, NULL );
	qtarch_layout_1_2->addLayout( qtarch_layout_1_2_1, 0 );
	qtarch_layout_1_2_1->addColSpacing( 0, 5 );
	qtarch_layout_1_2_1->setColStretch( 0, 0 );
	qtarch_layout_1_2_1->addColSpacing( 1, 5 );
	qtarch_layout_1_2_1->setColStretch( 1, 1 );
	qtarch_layout_1_2_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_2_1->setRowStretch( 0, 1 );
	qtarch_layout_1_2_1->addWidget( qtarch_NameLabel, 0, 0, 0 );
	qtarch_layout_1_2_1->addWidget( fullName, 0, 1, 0 );
	qtarch_layout_1_2_1->addRowSpacing( 1, 0 );
	qtarch_layout_1_2_1->setRowStretch( 1, 1 );
	qtarch_layout_1_2_1->addWidget( qtarch_ContactNameLabel, 1, 0, 0 );
	qtarch_layout_1_2_1->addWidget( contactName, 1, 1, 0 );
	qtarch_layout_1_2->addStretch( 1 );
    resize(500,300);
    setMinimumSize(0, 0);
    setMaximumSize(32767, 32767);
}

NCWContactData::~NCWContactData()
{
}
