/**********************************************************************

	--- Qt Architect generated file ---

	File: NCWContactData.h
	Last generated: Mon Mar 27 17:22:41 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef NCWContactData_included
#define NCWContactData_included

#include <qwidget.h>
#include "qtextview.h"
#include <qlineedit.h>

class NCWContactData : public QWidget
{
    Q_OBJECT

public:

    NCWContactData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~NCWContactData();

    protected:

    QTextView *helpText;
    QLineEdit *fullName;
    QLineEdit *contactName;
};

#endif // NCWContactData_included
