/**********************************************************************

	--- Qt Architect generated file ---

	File: NewCustomerData.h
	Last generated: Tue Mar 10 02:29:12 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef NewCustomerData_included
#define NewCustomerData_included

#include <qdialog.h>
#include <qpushbt.h>
#include <qlined.h>
#include <qcombo.h>
#include <qmultilineedit.h>

class NewCustomerData : public QDialog
{
    Q_OBJECT

public:

    NewCustomerData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~NewCustomerData();

public slots:


protected slots:

    virtual void addCustomer();

protected:
    QLineEdit* fullName;
    QLineEdit* contactName;
    QLineEdit* altContact;
    QLineEdit* address1;
    QLineEdit* address2;
    QLineEdit* city;
    QLineEdit* state;
    QLineEdit* zip;
    QLineEdit* country;
    QLineEdit* dayPhone;
    QLineEdit* evePhone;
    QLineEdit* faxPhone;
    QLineEdit* altPhone;
    QComboBox* ratePlan;
    QComboBox* statementType;
    QComboBox* referredBy;
    QMultiLineEdit* initialNotes;
    QPushButton* doneButton;
    QComboBox* package;

};

#endif // NewCustomerData_included
