/**********************************************************************

	--- Qt Architect generated file ---

	File: NewCustWizardData.h
	Last generated: Mon Mar 27 16:20:43 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef NewCustWizardData_included
#define NewCustWizardData_included

#include "qwizard.h"

class NewCustWizardData : public QWizard
{
    Q_OBJECT

public:

    NewCustWizardData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~NewCustWizardData();
};

#endif // NewCustWizardData_included
