/**********************************************************************

	--- Qt Architect generated file ---

	File: NewCustomerData.cpp
	Last generated: Tue Mar 10 02:29:12 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "NewCustomerData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qbttngrp.h>
#include <qpushbt.h>

NewCustomerData::NewCustomerData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* dlgedit_ButtonGroup_4;
	dlgedit_ButtonGroup_4 = new QButtonGroup( this, "ButtonGroup_4" );
	dlgedit_ButtonGroup_4->setGeometry( 10, 260, 665, 90 );
	dlgedit_ButtonGroup_4->setMinimumSize( 10, 10 );
	dlgedit_ButtonGroup_4->setMaximumSize( 32767, 32767 );
	dlgedit_ButtonGroup_4->setFrameStyle( 49 );
	dlgedit_ButtonGroup_4->setTitle( "Miscellanious" );
	dlgedit_ButtonGroup_4->setAlignment( 1 );

	QButtonGroup* dlgedit_ButtonGroup_3;
	dlgedit_ButtonGroup_3 = new QButtonGroup( this, "ButtonGroup_3" );
	dlgedit_ButtonGroup_3->setGeometry( 10, 185, 665, 70 );
	dlgedit_ButtonGroup_3->setMinimumSize( 10, 10 );
	dlgedit_ButtonGroup_3->setMaximumSize( 32767, 32767 );
	dlgedit_ButtonGroup_3->setFrameStyle( 49 );
	dlgedit_ButtonGroup_3->setTitle( "Billing Information" );
	dlgedit_ButtonGroup_3->setAlignment( 1 );

	QButtonGroup* dlgedit_ButtonGroup_2;
	dlgedit_ButtonGroup_2 = new QButtonGroup( this, "ButtonGroup_2" );
	dlgedit_ButtonGroup_2->setGeometry( 350, 65, 325, 110 );
	dlgedit_ButtonGroup_2->setMinimumSize( 10, 10 );
	dlgedit_ButtonGroup_2->setMaximumSize( 32767, 32767 );
	dlgedit_ButtonGroup_2->setFrameStyle( 49 );
	dlgedit_ButtonGroup_2->setTitle( "Phone Numbers" );
	dlgedit_ButtonGroup_2->setAlignment( 1 );

	QButtonGroup* dlgedit_ButtonGroup_1;
	dlgedit_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	dlgedit_ButtonGroup_1->setGeometry( 10, 65, 325, 110 );
	dlgedit_ButtonGroup_1->setMinimumSize( 10, 10 );
	dlgedit_ButtonGroup_1->setMaximumSize( 32767, 32767 );
	dlgedit_ButtonGroup_1->setFrameStyle( 49 );
	dlgedit_ButtonGroup_1->setTitle( "Address" );
	dlgedit_ButtonGroup_1->setAlignment( 1 );

	QLabel* dlgedit_Label_1;
	dlgedit_Label_1 = new QLabel( this, "Label_1" );
	dlgedit_Label_1->setGeometry( 15, 10, 100, 20 );
	dlgedit_Label_1->setMinimumSize( 10, 10 );
	dlgedit_Label_1->setMaximumSize( 32767, 32767 );
	dlgedit_Label_1->setText( "Name:" );
	dlgedit_Label_1->setAlignment( 290 );
	dlgedit_Label_1->setMargin( -1 );

	QLabel* dlgedit_Label_2;
	dlgedit_Label_2 = new QLabel( this, "Label_2" );
	dlgedit_Label_2->setGeometry( 15, 30, 100, 20 );
	dlgedit_Label_2->setMinimumSize( 10, 10 );
	dlgedit_Label_2->setMaximumSize( 32767, 32767 );
	dlgedit_Label_2->setText( "Contact Name:" );
	dlgedit_Label_2->setAlignment( 290 );
	dlgedit_Label_2->setMargin( -1 );

	QLabel* dlgedit_Label_3;
	dlgedit_Label_3 = new QLabel( this, "Label_3" );
	dlgedit_Label_3->setGeometry( 360, 30, 100, 20 );
	dlgedit_Label_3->setMinimumSize( 10, 10 );
	dlgedit_Label_3->setMaximumSize( 32767, 32767 );
	dlgedit_Label_3->setText( "Alt. Contact:" );
	dlgedit_Label_3->setAlignment( 290 );
	dlgedit_Label_3->setMargin( -1 );

	QLabel* dlgedit_Label_4;
	dlgedit_Label_4 = new QLabel( this, "Label_4" );
	dlgedit_Label_4->setGeometry( 15, 85, 100, 20 );
	dlgedit_Label_4->setMinimumSize( 10, 10 );
	dlgedit_Label_4->setMaximumSize( 32767, 32767 );
	dlgedit_Label_4->setText( "Address Line 1:" );
	dlgedit_Label_4->setAlignment( 290 );
	dlgedit_Label_4->setMargin( -1 );

	QLabel* dlgedit_Label_5;
	dlgedit_Label_5 = new QLabel( this, "Label_5" );
	dlgedit_Label_5->setGeometry( 15, 105, 100, 20 );
	dlgedit_Label_5->setMinimumSize( 10, 10 );
	dlgedit_Label_5->setMaximumSize( 32767, 32767 );
	dlgedit_Label_5->setText( "Address Line 2:" );
	dlgedit_Label_5->setAlignment( 290 );
	dlgedit_Label_5->setMargin( -1 );

	QLabel* dlgedit_Label_6;
	dlgedit_Label_6 = new QLabel( this, "Label_6" );
	dlgedit_Label_6->setGeometry( 15, 125, 100, 20 );
	dlgedit_Label_6->setMinimumSize( 10, 10 );
	dlgedit_Label_6->setMaximumSize( 32767, 32767 );
	dlgedit_Label_6->setText( "City, State ZIP:" );
	dlgedit_Label_6->setAlignment( 290 );
	dlgedit_Label_6->setMargin( -1 );

	QLabel* dlgedit_Label_7;
	dlgedit_Label_7 = new QLabel( this, "Label_7" );
	dlgedit_Label_7->setGeometry( 15, 145, 100, 20 );
	dlgedit_Label_7->setMinimumSize( 10, 10 );
	dlgedit_Label_7->setMaximumSize( 32767, 32767 );
	dlgedit_Label_7->setText( "Country:" );
	dlgedit_Label_7->setAlignment( 290 );
	dlgedit_Label_7->setMargin( -1 );

	QLabel* dlgedit_Label_8;
	dlgedit_Label_8 = new QLabel( this, "Label_8" );
	dlgedit_Label_8->setGeometry( 360, 85, 100, 20 );
	dlgedit_Label_8->setMinimumSize( 10, 10 );
	dlgedit_Label_8->setMaximumSize( 32767, 32767 );
	dlgedit_Label_8->setText( "Daytime:" );
	dlgedit_Label_8->setAlignment( 290 );
	dlgedit_Label_8->setMargin( -1 );

	QLabel* dlgedit_Label_9;
	dlgedit_Label_9 = new QLabel( this, "Label_9" );
	dlgedit_Label_9->setGeometry( 360, 105, 100, 20 );
	dlgedit_Label_9->setMinimumSize( 10, 10 );
	dlgedit_Label_9->setMaximumSize( 32767, 32767 );
	dlgedit_Label_9->setText( "Evening:" );
	dlgedit_Label_9->setAlignment( 290 );
	dlgedit_Label_9->setMargin( -1 );

	QLabel* dlgedit_Label_10;
	dlgedit_Label_10 = new QLabel( this, "Label_10" );
	dlgedit_Label_10->setGeometry( 360, 125, 100, 20 );
	dlgedit_Label_10->setMinimumSize( 10, 10 );
	dlgedit_Label_10->setMaximumSize( 32767, 32767 );
	dlgedit_Label_10->setText( "Fax:" );
	dlgedit_Label_10->setAlignment( 290 );
	dlgedit_Label_10->setMargin( -1 );

	QLabel* dlgedit_Label_11;
	dlgedit_Label_11 = new QLabel( this, "Label_11" );
	dlgedit_Label_11->setGeometry( 360, 145, 100, 20 );
	dlgedit_Label_11->setMinimumSize( 10, 10 );
	dlgedit_Label_11->setMaximumSize( 32767, 32767 );
	dlgedit_Label_11->setText( "Other:" );
	dlgedit_Label_11->setAlignment( 290 );
	dlgedit_Label_11->setMargin( -1 );

	QLabel* dlgedit_Label_12;
	dlgedit_Label_12 = new QLabel( this, "Label_12" );
	dlgedit_Label_12->setGeometry( 15, 205, 100, 20 );
	dlgedit_Label_12->setMinimumSize( 10, 10 );
	dlgedit_Label_12->setMaximumSize( 32767, 32767 );
	dlgedit_Label_12->setText( "Rate Plan:" );
	dlgedit_Label_12->setAlignment( 290 );
	dlgedit_Label_12->setMargin( -1 );

	QLabel* dlgedit_Label_14;
	dlgedit_Label_14 = new QLabel( this, "Label_14" );
	dlgedit_Label_14->setGeometry( 15, 275, 100, 20 );
	dlgedit_Label_14->setMinimumSize( 10, 10 );
	dlgedit_Label_14->setMaximumSize( 32767, 32767 );
	dlgedit_Label_14->setText( "Marketing Info:" );
	dlgedit_Label_14->setAlignment( 290 );
	dlgedit_Label_14->setMargin( -1 );

	QLabel* dlgedit_Label_15;
	dlgedit_Label_15 = new QLabel( this, "Label_15" );
	dlgedit_Label_15->setGeometry( 15, 305, 100, 20 );
	dlgedit_Label_15->setMinimumSize( 10, 10 );
	dlgedit_Label_15->setMaximumSize( 32767, 32767 );
	dlgedit_Label_15->setText( "Notes:" );
	dlgedit_Label_15->setAlignment( 290 );
	dlgedit_Label_15->setMargin( -1 );

	fullName = new QLineEdit( this, "LineEdit_1" );
	fullName->setGeometry( 120, 10, 205, 20 );
	fullName->setMinimumSize( 10, 10 );
	fullName->setMaximumSize( 32767, 32767 );
	fullName->setText( "" );
	fullName->setMaxLength( 60 );
	fullName->setEchoMode( QLineEdit::Normal );
	fullName->setFrame( TRUE );

	contactName = new QLineEdit( this, "LineEdit_2" );
	contactName->setGeometry( 120, 30, 205, 20 );
	contactName->setMinimumSize( 10, 10 );
	contactName->setMaximumSize( 32767, 32767 );
	contactName->setText( "" );
	contactName->setMaxLength( 60 );
	contactName->setEchoMode( QLineEdit::Normal );
	contactName->setFrame( TRUE );

	altContact = new QLineEdit( this, "LineEdit_3" );
	altContact->setGeometry( 465, 30, 205, 20 );
	altContact->setMinimumSize( 10, 10 );
	altContact->setMaximumSize( 32767, 32767 );
	altContact->setText( "" );
	altContact->setMaxLength( 60 );
	altContact->setEchoMode( QLineEdit::Normal );
	altContact->setFrame( TRUE );

	address1 = new QLineEdit( this, "LineEdit_4" );
	address1->setGeometry( 120, 85, 205, 20 );
	address1->setMinimumSize( 10, 10 );
	address1->setMaximumSize( 32767, 32767 );
	address1->setText( "" );
	address1->setMaxLength( 60 );
	address1->setEchoMode( QLineEdit::Normal );
	address1->setFrame( TRUE );

	address2 = new QLineEdit( this, "LineEdit_5" );
	address2->setGeometry( 120, 105, 205, 20 );
	address2->setMinimumSize( 10, 10 );
	address2->setMaximumSize( 32767, 32767 );
	address2->setText( "" );
	address2->setMaxLength( 60 );
	address2->setEchoMode( QLineEdit::Normal );
	address2->setFrame( TRUE );

	city = new QLineEdit( this, "LineEdit_6" );
	city->setGeometry( 120, 125, 115, 20 );
	city->setMinimumSize( 10, 10 );
	city->setMaximumSize( 32767, 32767 );
	city->setText( "" );
	city->setMaxLength( 60 );
	city->setEchoMode( QLineEdit::Normal );
	city->setFrame( TRUE );

	state = new QLineEdit( this, "LineEdit_7" );
	state->setGeometry( 235, 125, 30, 20 );
	state->setMinimumSize( 10, 10 );
	state->setMaximumSize( 32767, 32767 );
	state->setText( "" );
	state->setMaxLength( 60 );
	state->setEchoMode( QLineEdit::Normal );
	state->setFrame( TRUE );

	zip = new QLineEdit( this, "LineEdit_8" );
	zip->setGeometry( 265, 125, 60, 20 );
	zip->setMinimumSize( 10, 10 );
	zip->setMaximumSize( 32767, 32767 );
	zip->setText( "" );
	zip->setMaxLength( 60 );
	zip->setEchoMode( QLineEdit::Normal );
	zip->setFrame( TRUE );

	country = new QLineEdit( this, "LineEdit_9" );
	country->setGeometry( 120, 145, 205, 20 );
	country->setMinimumSize( 10, 10 );
	country->setMaximumSize( 32767, 32767 );
	country->setText( "" );
	country->setMaxLength( 60 );
	country->setEchoMode( QLineEdit::Normal );
	country->setFrame( TRUE );

	dayPhone = new QLineEdit( this, "LineEdit_10" );
	dayPhone->setGeometry( 465, 85, 205, 20 );
	dayPhone->setMinimumSize( 10, 10 );
	dayPhone->setMaximumSize( 32767, 32767 );
	dayPhone->setText( "" );
	dayPhone->setMaxLength( 30 );
	dayPhone->setEchoMode( QLineEdit::Normal );
	dayPhone->setFrame( TRUE );

	evePhone = new QLineEdit( this, "LineEdit_11" );
	evePhone->setGeometry( 465, 105, 205, 20 );
	evePhone->setMinimumSize( 10, 10 );
	evePhone->setMaximumSize( 32767, 32767 );
	evePhone->setText( "" );
	evePhone->setMaxLength( 30 );
	evePhone->setEchoMode( QLineEdit::Normal );
	evePhone->setFrame( TRUE );

	faxPhone = new QLineEdit( this, "LineEdit_12" );
	faxPhone->setGeometry( 465, 125, 205, 20 );
	faxPhone->setMinimumSize( 10, 10 );
	faxPhone->setMaximumSize( 32767, 32767 );
	faxPhone->setText( "" );
	faxPhone->setMaxLength( 30 );
	faxPhone->setEchoMode( QLineEdit::Normal );
	faxPhone->setFrame( TRUE );

	altPhone = new QLineEdit( this, "LineEdit_13" );
	altPhone->setGeometry( 465, 145, 205, 20 );
	altPhone->setMinimumSize( 10, 10 );
	altPhone->setMaximumSize( 32767, 32767 );
	altPhone->setText( "" );
	altPhone->setMaxLength( 30 );
	altPhone->setEchoMode( QLineEdit::Normal );
	altPhone->setFrame( TRUE );

	ratePlan = new QComboBox( FALSE, this, "ComboBox_1" );
	ratePlan->setGeometry( 120, 205, 205, 20 );
	ratePlan->setMinimumSize( 10, 10 );
	ratePlan->setMaximumSize( 32767, 32767 );
	ratePlan->setSizeLimit( 10 );
	ratePlan->setAutoResize( FALSE );

	statementType = new QComboBox( FALSE, this, "ComboBox_3" );
	statementType->setGeometry( 465, 205, 205, 20 );
	statementType->setMinimumSize( 10, 10 );
	statementType->setMaximumSize( 32767, 32767 );
	statementType->setSizeLimit( 10 );
	statementType->setAutoResize( FALSE );
	statementType->insertItem( "Email Only" );
	statementType->insertItem( "Email & Printed - Charge" );
	statementType->insertItem( "Email & Printed - Free" );

	referredBy = new QComboBox( TRUE, this, "ComboBox_2" );
	referredBy->setGeometry( 120, 275, 205, 25 );
	referredBy->setMinimumSize( 10, 10 );
	referredBy->setMaximumSize( 32767, 32767 );
	referredBy->setInsertionPolicy( QComboBox::AtTop );
	referredBy->setSizeLimit( 10 );
	referredBy->setAutoResize( FALSE );

	initialNotes = new QMultiLineEdit( this, "MultiLineEdit_1" );
	initialNotes->setGeometry( 120, 305, 550, 35 );
	initialNotes->setMinimumSize( 10, 10 );
	initialNotes->setMaximumSize( 32767, 32767 );
	initialNotes->insertLine( "" );
	initialNotes->setReadOnly( FALSE );
	initialNotes->setOverwriteMode( FALSE );

	doneButton = new QPushButton( this, "PushButton_1" );
	doneButton->setGeometry( 460, 360, 100, 30 );
	doneButton->setMinimumSize( 10, 10 );
	doneButton->setMaximumSize( 32767, 32767 );
	connect( doneButton, SIGNAL(clicked()), SLOT(addCustomer()) );
	doneButton->setText( "&Add" );
	doneButton->setAutoRepeat( FALSE );
	doneButton->setAutoResize( FALSE );
	doneButton->setAutoDefault( TRUE );

	QPushButton* dlgedit_PushButton_2;
	dlgedit_PushButton_2 = new QPushButton( this, "PushButton_2" );
	dlgedit_PushButton_2->setGeometry( 570, 360, 100, 30 );
	dlgedit_PushButton_2->setMinimumSize( 10, 10 );
	dlgedit_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_2, SIGNAL(clicked()), SLOT(reject()) );
	dlgedit_PushButton_2->setText( "&Cancel" );
	dlgedit_PushButton_2->setAutoRepeat( FALSE );
	dlgedit_PushButton_2->setAutoResize( FALSE );

	QLabel* dlgedit_Label_16;
	dlgedit_Label_16 = new QLabel( this, "Label_16" );
	dlgedit_Label_16->setGeometry( 360, 205, 100, 20 );
	dlgedit_Label_16->setMinimumSize( 10, 10 );
	dlgedit_Label_16->setMaximumSize( 32767, 32767 );
	dlgedit_Label_16->setText( "Statement Type:" );
	dlgedit_Label_16->setAlignment( 290 );
	dlgedit_Label_16->setMargin( -1 );

	QLabel* dlgedit_Label_17;
	dlgedit_Label_17 = new QLabel( this, "Label_17" );
	dlgedit_Label_17->setGeometry( 15, 230, 100, 20 );
	dlgedit_Label_17->setMinimumSize( 10, 10 );
	dlgedit_Label_17->setMaximumSize( 32767, 32767 );
	dlgedit_Label_17->setText( "Initial Package:" );
	dlgedit_Label_17->setAlignment( 290 );
	dlgedit_Label_17->setMargin( -1 );

	package = new QComboBox( FALSE, this, "ComboBox_5" );
	package->setGeometry( 120, 230, 205, 20 );
	package->setMinimumSize( 10, 10 );
	package->setMaximumSize( 32767, 32767 );
	package->setSizeLimit( 10 );
	package->setAutoResize( FALSE );
	package->insertItem( "None" );





	resize( 685,400 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


NewCustomerData::~NewCustomerData()
{
}
void NewCustomerData::addCustomer()
{
}
