/**********************************************************************

	--- Qt Architect generated file ---

	File: NewCustWizardData.cpp
	Last generated: Mon Mar 27 16:20:43 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "NewCustWizardData.h"


NewCustWizardData::NewCustWizardData(QWidget *parent, const char *name)
                  : QWizard(parent, name, 0)
{
    resize(500,300);
    setMinimumSize(0, 0);
    setMaximumSize(32767, 32767);
}

NewCustWizardData::~NewCustWizardData()
{
}
