/**********************************************************************

	--- Qt Architect generated file ---

	File: StatementViewData.h
	Last generated: Sun Sep 13 12:43:31 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef StatementViewData_included
#define StatementViewData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qpushbt.h>
#include "qlistview.h"

class StatementViewData : public QDialog
{
    Q_OBJECT

public:

    StatementViewData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~StatementViewData();

public slots:


protected slots:

    virtual void rePrintStatement();
    virtual void closeView();
    virtual void reEmailStatement();

protected:
    QLabel* custName;
    QLabel* custAddr1;
    QLabel* custAddr2;
    QLabel* custAddr3;
    QLabel* custAddr4;
    QListView* list;
    QLabel* statementDate;
    QLabel* chargesThrough;
    QLabel* dueDate;
    QLabel* terms;
    QLabel* statementNo;
    QLabel* prevBalance;
    QLabel* credits;
    QLabel* newCharges;
    QLabel* financeCharge;
    QLabel* totalDue;
    QPushButton* closeButton;
    QPushButton* printButton;
    QPushButton* emailButton;
    QLabel* emailedToLabel;
    QLabel* printedOnLabel;

};

#endif // StatementViewData_included
