/**********************************************************************

	--- Qt Architect generated file ---

	File: StatementViewData.cpp
	Last generated: Sun Sep 13 12:43:31 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "StatementViewData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qbttngrp.h>

StatementViewData::StatementViewData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* dlgedit_ButtonGroup_3;
	dlgedit_ButtonGroup_3 = new QButtonGroup( this, "ButtonGroup_3" );
	dlgedit_ButtonGroup_3->setGeometry( 520, 5, 255, 120 );
	dlgedit_ButtonGroup_3->setMinimumSize( 10, 10 );
	dlgedit_ButtonGroup_3->setMaximumSize( 32767, 32767 );
	dlgedit_ButtonGroup_3->setFrameStyle( 49 );
	dlgedit_ButtonGroup_3->setTitle( "Charge Information" );
	dlgedit_ButtonGroup_3->setAlignment( 1 );

	QButtonGroup* dlgedit_ButtonGroup_2;
	dlgedit_ButtonGroup_2 = new QButtonGroup( this, "ButtonGroup_2" );
	dlgedit_ButtonGroup_2->setGeometry( 260, 5, 255, 120 );
	dlgedit_ButtonGroup_2->setMinimumSize( 10, 10 );
	dlgedit_ButtonGroup_2->setMaximumSize( 32767, 32767 );
	dlgedit_ButtonGroup_2->setFrameStyle( 49 );
	dlgedit_ButtonGroup_2->setTitle( "Date Information" );
	dlgedit_ButtonGroup_2->setAlignment( 1 );

	QButtonGroup* dlgedit_ButtonGroup_1;
	dlgedit_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	dlgedit_ButtonGroup_1->setGeometry( 5, 5, 250, 120 );
	dlgedit_ButtonGroup_1->setMinimumSize( 10, 10 );
	dlgedit_ButtonGroup_1->setMaximumSize( 32767, 32767 );
	dlgedit_ButtonGroup_1->setFrameStyle( 49 );
	dlgedit_ButtonGroup_1->setTitle( "Billed To" );
	dlgedit_ButtonGroup_1->setAlignment( 1 );

	custName = new QLabel( this, "Label_2" );
	custName->setGeometry( 10, 20, 240, 20 );
	custName->setMinimumSize( 10, 10 );
	custName->setMaximumSize( 32767, 32767 );
	custName->setText( "CustName" );
	custName->setAlignment( 289 );
	custName->setMargin( -1 );

	custAddr1 = new QLabel( this, "Label_3" );
	custAddr1->setGeometry( 10, 40, 240, 20 );
	custAddr1->setMinimumSize( 10, 10 );
	custAddr1->setMaximumSize( 32767, 32767 );
	custAddr1->setText( "CustAddr1" );
	custAddr1->setAlignment( 289 );
	custAddr1->setMargin( -1 );

	custAddr2 = new QLabel( this, "Label_4" );
	custAddr2->setGeometry( 10, 60, 240, 20 );
	custAddr2->setMinimumSize( 10, 10 );
	custAddr2->setMaximumSize( 32767, 32767 );
	custAddr2->setText( "CustAddr2" );
	custAddr2->setAlignment( 289 );
	custAddr2->setMargin( -1 );

	custAddr3 = new QLabel( this, "Label_5" );
	custAddr3->setGeometry( 10, 80, 240, 20 );
	custAddr3->setMinimumSize( 10, 10 );
	custAddr3->setMaximumSize( 32767, 32767 );
	custAddr3->setText( "CustAddr3" );
	custAddr3->setAlignment( 289 );
	custAddr3->setMargin( -1 );

	custAddr4 = new QLabel( this, "Label_6" );
	custAddr4->setGeometry( 10, 100, 240, 20 );
	custAddr4->setMinimumSize( 10, 10 );
	custAddr4->setMaximumSize( 32767, 32767 );
	custAddr4->setText( "CustAddr4" );
	custAddr4->setAlignment( 289 );
	custAddr4->setMargin( -1 );

	list = new QListView( this, "User_1" );
	list->setGeometry( 5, 135, 780, 390 );
	list->setMinimumSize( 0, 0 );
	list->setMaximumSize( 32767, 32767 );

	QLabel* dlgedit_Label_8;
	dlgedit_Label_8 = new QLabel( this, "Label_8" );
	dlgedit_Label_8->setGeometry( 265, 40, 105, 20 );
	dlgedit_Label_8->setMinimumSize( 10, 10 );
	dlgedit_Label_8->setMaximumSize( 32767, 32767 );
	dlgedit_Label_8->setText( "Statement Date:" );
	dlgedit_Label_8->setAlignment( 290 );
	dlgedit_Label_8->setMargin( -1 );

	statementDate = new QLabel( this, "Label_9" );
	statementDate->setGeometry( 375, 40, 135, 20 );
	statementDate->setMinimumSize( 10, 10 );
	statementDate->setMaximumSize( 32767, 32767 );
	statementDate->setText( "StatementDate" );
	statementDate->setAlignment( 289 );
	statementDate->setMargin( -1 );

	QLabel* dlgedit_Label_10;
	dlgedit_Label_10 = new QLabel( this, "Label_10" );
	dlgedit_Label_10->setGeometry( 265, 60, 105, 20 );
	dlgedit_Label_10->setMinimumSize( 10, 10 );
	dlgedit_Label_10->setMaximumSize( 32767, 32767 );
	dlgedit_Label_10->setText( "Charges Through:" );
	dlgedit_Label_10->setAlignment( 290 );
	dlgedit_Label_10->setMargin( -1 );

	chargesThrough = new QLabel( this, "Label_11" );
	chargesThrough->setGeometry( 375, 60, 100, 20 );
	chargesThrough->setMinimumSize( 10, 10 );
	chargesThrough->setMaximumSize( 32767, 32767 );
	chargesThrough->setText( "ChargesThrough" );
	chargesThrough->setAlignment( 289 );
	chargesThrough->setMargin( -1 );

	QLabel* dlgedit_Label_12;
	dlgedit_Label_12 = new QLabel( this, "Label_12" );
	dlgedit_Label_12->setGeometry( 270, 80, 100, 20 );
	dlgedit_Label_12->setMinimumSize( 10, 10 );
	dlgedit_Label_12->setMaximumSize( 32767, 32767 );
	dlgedit_Label_12->setText( "Due Date:" );
	dlgedit_Label_12->setAlignment( 290 );
	dlgedit_Label_12->setMargin( -1 );

	dueDate = new QLabel( this, "Label_13" );
	dueDate->setGeometry( 375, 80, 135, 20 );
	dueDate->setMinimumSize( 10, 10 );
	dueDate->setMaximumSize( 32767, 32767 );
	dueDate->setText( "DueDate" );
	dueDate->setAlignment( 289 );
	dueDate->setMargin( -1 );

	QLabel* dlgedit_Label_14;
	dlgedit_Label_14 = new QLabel( this, "Label_14" );
	dlgedit_Label_14->setGeometry( 270, 100, 100, 20 );
	dlgedit_Label_14->setMinimumSize( 10, 10 );
	dlgedit_Label_14->setMaximumSize( 32767, 32767 );
	dlgedit_Label_14->setText( "Terms:" );
	dlgedit_Label_14->setAlignment( 290 );
	dlgedit_Label_14->setMargin( -1 );

	terms = new QLabel( this, "Label_15" );
	terms->setGeometry( 375, 100, 135, 20 );
	terms->setMinimumSize( 10, 10 );
	terms->setMaximumSize( 32767, 32767 );
	terms->setText( "Terms" );
	terms->setAlignment( 289 );
	terms->setMargin( -1 );

	QLabel* dlgedit_Label_16;
	dlgedit_Label_16 = new QLabel( this, "Label_16" );
	dlgedit_Label_16->setGeometry( 525, 20, 110, 20 );
	dlgedit_Label_16->setMinimumSize( 10, 10 );
	dlgedit_Label_16->setMaximumSize( 32767, 32767 );
	dlgedit_Label_16->setText( "Previous Balance:" );
	dlgedit_Label_16->setAlignment( 290 );
	dlgedit_Label_16->setMargin( -1 );

	QLabel* dlgedit_Label_17;
	dlgedit_Label_17 = new QLabel( this, "Label_17" );
	dlgedit_Label_17->setGeometry( 265, 20, 105, 20 );
	dlgedit_Label_17->setMinimumSize( 10, 10 );
	dlgedit_Label_17->setMaximumSize( 32767, 32767 );
	dlgedit_Label_17->setText( "Statement No.:" );
	dlgedit_Label_17->setAlignment( 290 );
	dlgedit_Label_17->setMargin( -1 );

	statementNo = new QLabel( this, "Label_18" );
	statementNo->setGeometry( 375, 20, 100, 20 );
	statementNo->setMinimumSize( 10, 10 );
	statementNo->setMaximumSize( 32767, 32767 );
	statementNo->setText( "StatementNo" );
	statementNo->setAlignment( 289 );
	statementNo->setMargin( -1 );

	prevBalance = new QLabel( this, "Label_19" );
	prevBalance->setGeometry( 640, 20, 100, 20 );
	prevBalance->setMinimumSize( 10, 10 );
	prevBalance->setMaximumSize( 32767, 32767 );
	prevBalance->setText( "PrevBalance" );
	prevBalance->setAlignment( 290 );
	prevBalance->setMargin( -1 );

	QLabel* dlgedit_Label_20;
	dlgedit_Label_20 = new QLabel( this, "Label_20" );
	dlgedit_Label_20->setGeometry( 535, 40, 100, 20 );
	dlgedit_Label_20->setMinimumSize( 10, 10 );
	dlgedit_Label_20->setMaximumSize( 32767, 32767 );
	dlgedit_Label_20->setText( "Credits:" );
	dlgedit_Label_20->setAlignment( 290 );
	dlgedit_Label_20->setMargin( -1 );

	QLabel* dlgedit_Label_21;
	dlgedit_Label_21 = new QLabel( this, "Label_21" );
	dlgedit_Label_21->setGeometry( 535, 60, 100, 20 );
	dlgedit_Label_21->setMinimumSize( 10, 10 );
	dlgedit_Label_21->setMaximumSize( 32767, 32767 );
	dlgedit_Label_21->setText( "New Charges:" );
	dlgedit_Label_21->setAlignment( 290 );
	dlgedit_Label_21->setMargin( -1 );

	QLabel* dlgedit_Label_22;
	dlgedit_Label_22 = new QLabel( this, "Label_22" );
	dlgedit_Label_22->setGeometry( 530, 80, 105, 20 );
	dlgedit_Label_22->setMinimumSize( 10, 10 );
	dlgedit_Label_22->setMaximumSize( 32767, 32767 );
	dlgedit_Label_22->setText( "Finance Charge:" );
	dlgedit_Label_22->setAlignment( 290 );
	dlgedit_Label_22->setMargin( -1 );

	QLabel* dlgedit_Label_23;
	dlgedit_Label_23 = new QLabel( this, "Label_23" );
	dlgedit_Label_23->setGeometry( 535, 100, 100, 20 );
	dlgedit_Label_23->setMinimumSize( 10, 10 );
	dlgedit_Label_23->setMaximumSize( 32767, 32767 );
	dlgedit_Label_23->setText( "Total Due:" );
	dlgedit_Label_23->setAlignment( 290 );
	dlgedit_Label_23->setMargin( -1 );

	credits = new QLabel( this, "Label_24" );
	credits->setGeometry( 640, 40, 100, 20 );
	credits->setMinimumSize( 10, 10 );
	credits->setMaximumSize( 32767, 32767 );
	credits->setText( "Credits" );
	credits->setAlignment( 290 );
	credits->setMargin( -1 );

	newCharges = new QLabel( this, "Label_25" );
	newCharges->setGeometry( 640, 60, 100, 20 );
	newCharges->setMinimumSize( 10, 10 );
	newCharges->setMaximumSize( 32767, 32767 );
	newCharges->setText( "NewCharges" );
	newCharges->setAlignment( 290 );
	newCharges->setMargin( -1 );

	financeCharge = new QLabel( this, "Label_26" );
	financeCharge->setGeometry( 640, 80, 100, 20 );
	financeCharge->setMinimumSize( 10, 10 );
	financeCharge->setMaximumSize( 32767, 32767 );
	financeCharge->setText( "FinanceCharge" );
	financeCharge->setAlignment( 290 );
	financeCharge->setMargin( -1 );

	totalDue = new QLabel( this, "Label_27" );
	totalDue->setGeometry( 640, 100, 100, 20 );
	totalDue->setMinimumSize( 10, 10 );
	totalDue->setMaximumSize( 32767, 32767 );
	totalDue->setText( "TotalDue" );
	totalDue->setAlignment( 290 );
	totalDue->setMargin( -1 );

	closeButton = new QPushButton( this, "PushButton_1" );
	closeButton->setGeometry( 700, 535, 80, 25 );
	closeButton->setMinimumSize( 10, 10 );
	closeButton->setMaximumSize( 32767, 32767 );
	connect( closeButton, SIGNAL(clicked()), SLOT(closeView()) );
	closeButton->setText( "&Close" );
	closeButton->setAutoRepeat( FALSE );
	closeButton->setAutoResize( FALSE );

	printButton = new QPushButton( this, "PushButton_2" );
	printButton->setGeometry( 620, 535, 75, 25 );
	printButton->setMinimumSize( 10, 10 );
	printButton->setMaximumSize( 32767, 32767 );
	connect( printButton, SIGNAL(clicked()), SLOT(rePrintStatement()) );
	printButton->setText( "&Print" );
	printButton->setAutoRepeat( FALSE );
	printButton->setAutoResize( FALSE );

	emailButton = new QPushButton( this, "PushButton_3" );
	emailButton->setGeometry( 540, 535, 75, 25 );
	emailButton->setMinimumSize( 10, 10 );
	emailButton->setMaximumSize( 32767, 32767 );
	connect( emailButton, SIGNAL(clicked()), SLOT(reEmailStatement()) );
	emailButton->setText( "&Email" );
	emailButton->setAutoRepeat( FALSE );
	emailButton->setAutoResize( FALSE );

	QLabel* dlgedit_Label_28;
	dlgedit_Label_28 = new QLabel( this, "Label_28" );
	dlgedit_Label_28->setGeometry( 10, 525, 100, 20 );
	dlgedit_Label_28->setMinimumSize( 10, 10 );
	dlgedit_Label_28->setMaximumSize( 32767, 32767 );
	dlgedit_Label_28->setText( "Emailed to:" );
	dlgedit_Label_28->setAlignment( 290 );
	dlgedit_Label_28->setMargin( -1 );

	QLabel* dlgedit_Label_29;
	dlgedit_Label_29 = new QLabel( this, "Label_29" );
	dlgedit_Label_29->setGeometry( 10, 545, 100, 20 );
	dlgedit_Label_29->setMinimumSize( 10, 10 );
	dlgedit_Label_29->setMaximumSize( 32767, 32767 );
	dlgedit_Label_29->setText( "Printed on:" );
	dlgedit_Label_29->setAlignment( 290 );
	dlgedit_Label_29->setMargin( -1 );

	emailedToLabel = new QLabel( this, "Label_30" );
	emailedToLabel->setGeometry( 115, 525, 225, 20 );
	emailedToLabel->setMinimumSize( 10, 10 );
	emailedToLabel->setMaximumSize( 32767, 32767 );
	emailedToLabel->setText( "Emailed To " );
	emailedToLabel->setAlignment( 289 );
	emailedToLabel->setMargin( -1 );

	printedOnLabel = new QLabel( this, "Label_31" );
	printedOnLabel->setGeometry( 115, 545, 225, 20 );
	printedOnLabel->setMinimumSize( 10, 10 );
	printedOnLabel->setMaximumSize( 32767, 32767 );
	printedOnLabel->setText( "Printed On" );
	printedOnLabel->setAlignment( 289 );
	printedOnLabel->setMargin( -1 );




	resize( 790,570 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


StatementViewData::~StatementViewData()
{
}
void StatementViewData::closeView()
{
}
void StatementViewData::rePrintStatement()
{
}
void StatementViewData::reEmailStatement()
{
}
