/**********************************************************************

	--- Qt Architect generated file ---

	File: TransferLoginData.cpp
	Last generated: Mon Sep 14 19:00:16 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "TransferLoginData.h"

#define Inherited QDialog

#include <qlabel.h>

TransferLoginData::TransferLoginData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	messageLabel = new QLabel( this, "Label_1" );
	messageLabel->setGeometry( 15, 10, 370, 35 );
	messageLabel->setMinimumSize( 10, 10 );
	messageLabel->setMaximumSize( 32767, 32767 );
	messageLabel->setText( "Select the customer to transfer this login to." );
	messageLabel->setAlignment( 1313 );
	messageLabel->setMargin( -1 );

	list = new QListView( this, "User_1" );
	list->setGeometry( 10, 75, 380, 180 );
	list->setMinimumSize( 10, 10 );
	list->setMaximumSize( 32767, 32767 );

	QLabel* dlgedit_Label_2;
	dlgedit_Label_2 = new QLabel( this, "Label_2" );
	dlgedit_Label_2->setGeometry( 15, 50, 60, 20 );
	dlgedit_Label_2->setMinimumSize( 10, 10 );
	dlgedit_Label_2->setMaximumSize( 32767, 32767 );
	dlgedit_Label_2->setText( "Query:" );
	dlgedit_Label_2->setAlignment( 290 );
	dlgedit_Label_2->setMargin( -1 );

	listQuery = new QLineEdit( this, "LineEdit_1" );
	listQuery->setGeometry( 80, 50, 135, 20 );
	listQuery->setMinimumSize( 10, 10 );
	listQuery->setMaximumSize( 32767, 32767 );
	connect( listQuery, SIGNAL(returnPressed()), SLOT(doQuery()) );
	listQuery->setText( "" );
	listQuery->setMaxLength( 40 );
	listQuery->setEchoMode( QLineEdit::Normal );
	listQuery->setFrame( TRUE );

	cancelButton = new QPushButton( this, "PushButton_1" );
	cancelButton->setGeometry( 320, 265, 70, 25 );
	cancelButton->setMinimumSize( 10, 10 );
	cancelButton->setMaximumSize( 32767, 32767 );
	connect( cancelButton, SIGNAL(clicked()), SLOT(cancelTransfer()) );
	cancelButton->setText( "&Cancel" );
	cancelButton->setAutoRepeat( FALSE );
	cancelButton->setAutoResize( FALSE );

	transferButton = new QPushButton( this, "PushButton_2" );
	transferButton->setGeometry( 245, 265, 70, 25 );
	transferButton->setMinimumSize( 10, 10 );
	transferButton->setMaximumSize( 32767, 32767 );
	connect( transferButton, SIGNAL(clicked()), SLOT(doTransfer()) );
	transferButton->setText( "&Transfer" );
	transferButton->setAutoRepeat( FALSE );
	transferButton->setAutoResize( FALSE );

	QLabel* dlgedit_Label_3;
	dlgedit_Label_3 = new QLabel( this, "Label_3" );
	dlgedit_Label_3->setGeometry( 15, 265, 65, 20 );
	dlgedit_Label_3->setMinimumSize( 10, 10 );
	dlgedit_Label_3->setMaximumSize( 32767, 32767 );
	dlgedit_Label_3->setText( "Eff. Date:" );
	dlgedit_Label_3->setAlignment( 290 );
	dlgedit_Label_3->setMargin( -1 );

	effectiveDate = new QLineEdit( this, "LineEdit_2" );
	effectiveDate->setGeometry( 85, 265, 85, 20 );
	effectiveDate->setMinimumSize( 10, 10 );
	effectiveDate->setMaximumSize( 32767, 32767 );
	effectiveDate->setText( "" );
	effectiveDate->setMaxLength( 10 );
	effectiveDate->setEchoMode( QLineEdit::Normal );
	effectiveDate->setFrame( TRUE );

	resize( 400,300 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


TransferLoginData::~TransferLoginData()
{
}
void TransferLoginData::doQuery()
{
}
void TransferLoginData::cancelTransfer()
{
}
void TransferLoginData::doTransfer()
{
}
