/**********************************************************************

	--- Qt Architect generated file ---

	File: TransferLoginData.h
	Last generated: Mon Sep 14 19:00:16 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef TransferLoginData_included
#define TransferLoginData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qpushbt.h>
#include <qlined.h>
#include "qlistview.h"

class TransferLoginData : public QDialog
{
    Q_OBJECT

public:

    TransferLoginData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~TransferLoginData();

public slots:


protected slots:

    virtual void cancelTransfer();
    virtual void doTransfer();
    virtual void doQuery();

protected:
    QLabel* messageLabel;
    QListView* list;
    QLineEdit* listQuery;
    QPushButton* cancelButton;
    QPushButton* transferButton;
    QLineEdit* effectiveDate;

};

#endif // TransferLoginData_included
