/**********************************************************************

	--- Qt Architect generated file ---

	File: AddressEditorData.h
	Last generated: Tue Feb 22 13:17:44 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef AddressEditorData_included
#define AddressEditorData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qcheckbox.h>
#include <qcombobox.h>
#include <qlineedit.h>

class AddressEditorData : public QDialog
{
    Q_OBJECT

public:

    AddressEditorData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~AddressEditorData();

    protected slots:

    virtual void saveAddress() =0;
    virtual void cancelAddress() =0;
    virtual void internationalChanged(bool) =0;

    protected:

    QLabel *typeLabel;
    QCheckBox *active;
    QLabel *typeLabel2;
    QLabel *tagLabel;
    QCheckBox *international;
    QComboBox *tagList;
    QLabel *cszLabel;
    QLabel *countryLabel;
    QLabel *postalLabel;
    QLineEdit *address1;
    QLineEdit *address2;
    QLineEdit *city;
    QLineEdit *state;
    QLineEdit *zip;
    QLineEdit *postalCode;
    QLineEdit *country;
    QLabel *lastModified;
    QLabel *lastModifiedBy;
    QPushButton *saveButton;
    QPushButton *canelButton;
};

#endif // AddressEditorData_included
