/**********************************************************************

	--- Qt Architect generated file ---

	File: PhoneEditorData.h
	Last generated: Tue Feb 22 13:15:25 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef PhoneEditorData_included
#define PhoneEditorData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qcheckbox.h>
#include <qcombobox.h>
#include <qlineedit.h>

class PhoneEditorData : public QDialog
{
    Q_OBJECT

public:

    PhoneEditorData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~PhoneEditorData();

    protected slots:

    virtual void savePhone() =0;
    virtual void cancelPhone() =0;
    virtual void internationalChanged(bool) =0;

    protected:

    QLabel *typeLabel;
    QCheckBox *active;
    QLabel *typeLabel2;
    QLabel *tagLabel;
    QCheckBox *international;
    QComboBox *tagList;
    QLineEdit *phoneNumber;
    QLabel *lastModified;
    QLabel *lastModifiedBy;
    QPushButton *saveButton;
    QPushButton *canelButton;
};

#endif // PhoneEditorData_included
