/**********************************************************************

	--- Qt Architect generated file ---

	File: PhoneEditorData.cpp
	Last generated: Tue Feb 22 13:15:25 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "PhoneEditorData.h"

#include <qlabel.h>
#include <qvbuttongroup.h>

PhoneEditorData::PhoneEditorData(QWidget *parent, const char *name)
                : QDialog(parent, name, FALSE, 0)
{
    typeLabel = new QLabel(this, "TypeLabel");
    typeLabel->setGeometry(5, 5, 54, 13);
    typeLabel->setMinimumSize(0, 0);
    typeLabel->setMaximumSize(32767, 32767);
    typeLabel->setFocusPolicy(QWidget::NoFocus);
    typeLabel->setBackgroundMode(QWidget::PaletteBackground);
    //typeLabel->setFontPropagation(QWidget::SameFont);
    //typeLabel->setPalettePropagation(QWidget::SameFont);
    typeLabel->setFrameStyle( 0 );
    typeLabel->setLineWidth( 1 );
    typeLabel->setMidLineWidth( 0 );
    typeLabel->QFrame::setMargin( -1 );
    typeLabel->setText( "Customer:" );
    typeLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    typeLabel->setMargin( -1 );

    QLabel *qtarch_TagLabel = new QLabel(this, "TagLabel");
    qtarch_TagLabel->setGeometry(5, 33, 23, 59);
    qtarch_TagLabel->setMinimumSize(0, 0);
    qtarch_TagLabel->setMaximumSize(32767, 32767);
    qtarch_TagLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_TagLabel->setBackgroundMode(QWidget::PaletteBackground);
    //qtarch_TagLabel->setFontPropagation(QWidget::SameFont);
    //qtarch_TagLabel->setPalettePropagation(QWidget::SameFont);
    qtarch_TagLabel->setFrameStyle( 0 );
    qtarch_TagLabel->setLineWidth( 1 );
    qtarch_TagLabel->setMidLineWidth( 0 );
    qtarch_TagLabel->QFrame::setMargin( -1 );
    qtarch_TagLabel->setText( "Tag:" );
    qtarch_TagLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_TagLabel->setMargin( -1 );

    typeLabel2 = new QLabel(this, "TypeLabel2");
    typeLabel2->setGeometry(64, 5, 301, 13);
    typeLabel2->setMinimumSize(0, 0);
    typeLabel2->setMaximumSize(32767, 32767);
    typeLabel2->setFocusPolicy(QWidget::NoFocus);
    typeLabel2->setBackgroundMode(QWidget::PaletteBackground);
    //typeLabel2->setFontPropagation(QWidget::SameFont);
    //typeLabel2->setPalettePropagation(QWidget::SameFont);
    typeLabel2->setFrameStyle( 0 );
    typeLabel2->setLineWidth( 1 );
    typeLabel2->setMidLineWidth( 0 );
    typeLabel2->QFrame::setMargin( -1 );
    typeLabel2->setText( "" );
    typeLabel2->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    typeLabel2->setMargin( -1 );

    QLabel *qtarch_HLine1 = new QLabel(this, "HLine1");
    qtarch_HLine1->setGeometry(5, 23, 360, 5);
    qtarch_HLine1->setMinimumSize(0, 5);
    qtarch_HLine1->setMaximumSize(32767, 5);
    qtarch_HLine1->setFocusPolicy(QWidget::NoFocus);
    qtarch_HLine1->setBackgroundMode(QWidget::PaletteBackground);
    //qtarch_HLine1->setFontPropagation(QWidget::SameFont);
    //qtarch_HLine1->setPalettePropagation(QWidget::SameFont);
    qtarch_HLine1->setFrameStyle( 52 );
    qtarch_HLine1->setLineWidth( 1 );
    qtarch_HLine1->setMidLineWidth( 0 );
    qtarch_HLine1->QFrame::setMargin( -1 );
    qtarch_HLine1->setText( "" );
    qtarch_HLine1->setAlignment( AlignHCenter|AlignVCenter|ExpandTabs );
    qtarch_HLine1->setMargin( -1 );

    tagLabel = new QLabel(this, "Label_5");
    tagLabel->setGeometry(145, 33, 107, 59);
    tagLabel->setMinimumSize(0, 0);
    tagLabel->setMaximumSize(32767, 32767);
    tagLabel->setFocusPolicy(QWidget::NoFocus);
    tagLabel->setBackgroundMode(QWidget::PaletteBackground);
    //tagLabel->setFontPropagation(QWidget::SameFont);
    //tagLabel->setPalettePropagation(QWidget::SameFont);
    tagLabel->setFrameStyle( 0 );
    tagLabel->setLineWidth( 1 );
    tagLabel->setMidLineWidth( 0 );
    tagLabel->QFrame::setMargin( -1 );
    tagLabel->setText( "" );
    tagLabel->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    tagLabel->setMargin( -1 );

    tagList = new QComboBox(TRUE, this, "TagList");
    tagList->setGeometry(33, 50, 107, 25);
    tagList->setMinimumSize(0, 0);
    tagList->setMaximumSize(32767, 32767);
    tagList->setFocusPolicy(QWidget::StrongFocus);
    tagList->setBackgroundMode(QWidget::NoBackground);
    //tagList->setFontPropagation(QWidget::AllChildren);
    //tagList->setPalettePropagation(QWidget::AllChildren);
    tagList->setInsertionPolicy( QComboBox::AtBottom );
    tagList->setSizeLimit( 10 );
    tagList->setAutoResize( FALSE );
    tagList->setMaxCount( 2147483647 );
    tagList->setAutoCompletion( FALSE );

    QLabel *qtarch_PhoneNumberLabel = new QLabel(this, "PhoneNumberLabel");
    qtarch_PhoneNumberLabel->setGeometry(5, 97, 85, 22);
    qtarch_PhoneNumberLabel->setMinimumSize(0, 0);
    qtarch_PhoneNumberLabel->setMaximumSize(32767, 32767);
    qtarch_PhoneNumberLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_PhoneNumberLabel->setBackgroundMode(QWidget::PaletteBackground);
    //qtarch_PhoneNumberLabel->setFontPropagation(QWidget::SameFont);
    //qtarch_PhoneNumberLabel->setPalettePropagation(QWidget::SameFont);
    qtarch_PhoneNumberLabel->setFrameStyle( 0 );
    qtarch_PhoneNumberLabel->setLineWidth( 1 );
    qtarch_PhoneNumberLabel->setMidLineWidth( 0 );
    qtarch_PhoneNumberLabel->QFrame::setMargin( -1 );
    qtarch_PhoneNumberLabel->setText( "Phone Number:" );
    qtarch_PhoneNumberLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_PhoneNumberLabel->setMargin( -1 );

    phoneNumber = new QLineEdit(this, "PhoneNumber");
    phoneNumber->setGeometry(95, 97, 270, 22);
    phoneNumber->setMinimumSize(0, 0);
    phoneNumber->setMaximumSize(32767, 32767);
    phoneNumber->setFocusPolicy(QWidget::StrongFocus);
    phoneNumber->setBackgroundMode(QWidget::PaletteBase);
    //phoneNumber->setFontPropagation(QWidget::SameFont);
    //phoneNumber->setPalettePropagation(QWidget::SameFont);
    phoneNumber->setText( "" );
    phoneNumber->setMaxLength( 32767 );
    phoneNumber->setFrame( QLineEdit::Normal );
    phoneNumber->setFrame( TRUE );
    phoneNumber->setAlignment( AlignLeft );

    QLabel *qtarch_LastModifiedLabel = new QLabel(this, "LastModifiedLabel");
    qtarch_LastModifiedLabel->setGeometry(5, 135, 77, 13);
    qtarch_LastModifiedLabel->setMinimumSize(0, 0);
    qtarch_LastModifiedLabel->setMaximumSize(32767, 32767);
    qtarch_LastModifiedLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_LastModifiedLabel->setBackgroundMode(QWidget::PaletteBackground);
    //qtarch_LastModifiedLabel->setFontPropagation(QWidget::SameFont);
    //qtarch_LastModifiedLabel->setPalettePropagation(QWidget::SameFont);
    qtarch_LastModifiedLabel->setFrameStyle( 0 );
    qtarch_LastModifiedLabel->setLineWidth( 1 );
    qtarch_LastModifiedLabel->setMidLineWidth( 0 );
    qtarch_LastModifiedLabel->QFrame::setMargin( -1 );
    qtarch_LastModifiedLabel->setText( "Last Modified:" );
    qtarch_LastModifiedLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_LastModifiedLabel->setMargin( -1 );

    lastModified = new QLabel(this, "LastModified");
    lastModified->setGeometry(87, 135, 128, 13);
    lastModified->setMinimumSize(0, 0);
    lastModified->setMaximumSize(32767, 32767);
    lastModified->setFocusPolicy(QWidget::NoFocus);
    lastModified->setBackgroundMode(QWidget::PaletteBackground);
    //lastModified->setFontPropagation(QWidget::SameFont);
    //lastModified->setPalettePropagation(QWidget::SameFont);
    lastModified->setFrameStyle( 0 );
    lastModified->setLineWidth( 1 );
    lastModified->setMidLineWidth( 0 );
    lastModified->QFrame::setMargin( -1 );
    lastModified->setText( "" );
    lastModified->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    lastModified->setMargin( -1 );

    QLabel *qtarch_LastModifiedByLabel = new QLabel(this, "LastModifiedByLabel");
    qtarch_LastModifiedByLabel->setGeometry(220, 135, 13, 13);
    qtarch_LastModifiedByLabel->setMinimumSize(0, 0);
    qtarch_LastModifiedByLabel->setMaximumSize(32767, 32767);
    qtarch_LastModifiedByLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_LastModifiedByLabel->setBackgroundMode(QWidget::PaletteBackground);
    //qtarch_LastModifiedByLabel->setFontPropagation(QWidget::SameFont);
    //qtarch_LastModifiedByLabel->setPalettePropagation(QWidget::SameFont);
    qtarch_LastModifiedByLabel->setFrameStyle( 0 );
    qtarch_LastModifiedByLabel->setLineWidth( 1 );
    qtarch_LastModifiedByLabel->setMidLineWidth( 0 );
    qtarch_LastModifiedByLabel->QFrame::setMargin( -1 );
    qtarch_LastModifiedByLabel->setText( "by" );
    qtarch_LastModifiedByLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_LastModifiedByLabel->setMargin( -1 );

    lastModifiedBy = new QLabel(this, "LastModifiedBy");
    lastModifiedBy->setGeometry(238, 135, 127, 13);
    lastModifiedBy->setMinimumSize(0, 0);
    lastModifiedBy->setMaximumSize(32767, 32767);
    lastModifiedBy->setFocusPolicy(QWidget::NoFocus);
    lastModifiedBy->setBackgroundMode(QWidget::PaletteBackground);
    //lastModifiedBy->setFontPropagation(QWidget::SameFont);
    //lastModifiedBy->setPalettePropagation(QWidget::SameFont);
    lastModifiedBy->setFrameStyle( 0 );
    lastModifiedBy->setLineWidth( 1 );
    lastModifiedBy->setMidLineWidth( 0 );
    lastModifiedBy->QFrame::setMargin( -1 );
    lastModifiedBy->setText( "" );
    lastModifiedBy->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    lastModifiedBy->setMargin( -1 );

    saveButton = new QPushButton(this, "SaveButton");
    saveButton->setGeometry(225, 164, 62, 26);
    saveButton->setMinimumSize(0, 0);
    saveButton->setMaximumSize(32767, 32767);
    saveButton->setFocusPolicy(QWidget::TabFocus);
    saveButton->setBackgroundMode(QWidget::PaletteButton);
    //saveButton->setFontPropagation(QWidget::SameFont);
    //saveButton->setPalettePropagation(QWidget::SameFont);
    saveButton->setText( "&Save" );
    saveButton->setAutoRepeat( FALSE );
    saveButton->setAutoResize( FALSE );
    saveButton->setToggleButton( FALSE );
    saveButton->setDefault( FALSE );
    saveButton->setAutoDefault( FALSE );
    saveButton->setIsMenuButton( FALSE );
    connect(saveButton, SIGNAL(clicked()), SLOT(savePhone()));

    canelButton = new QPushButton(this, "CancelButton");
    canelButton->setGeometry(292, 164, 73, 26);
    canelButton->setMinimumSize(0, 0);
    canelButton->setMaximumSize(32767, 32767);
    canelButton->setFocusPolicy(QWidget::TabFocus);
    canelButton->setBackgroundMode(QWidget::PaletteButton);
    //canelButton->setFontPropagation(QWidget::SameFont);
    //canelButton->setPalettePropagation(QWidget::SameFont);
    canelButton->setText( "&Cancel" );
    canelButton->setAutoRepeat( FALSE );
    canelButton->setAutoResize( FALSE );
    canelButton->setToggleButton( FALSE );
    canelButton->setDefault( FALSE );
    canelButton->setAutoDefault( FALSE );
    canelButton->setIsMenuButton( FALSE );
    connect(canelButton, SIGNAL(clicked()), SLOT(cancelPhone()));

    QVButtonGroup *qtarch_TypeGroup = new QVButtonGroup(this, "TypeGroup");
    qtarch_TypeGroup->setGeometry(257, 33, 108, 59);
    qtarch_TypeGroup->setMinimumSize(0, 0);
    qtarch_TypeGroup->setMaximumSize(32767, 32767);
    qtarch_TypeGroup->setFocusPolicy(QWidget::NoFocus);
    qtarch_TypeGroup->setBackgroundMode(QWidget::PaletteBackground);
    //qtarch_TypeGroup->setFontPropagation(QWidget::SameFont);
    //qtarch_TypeGroup->setPalettePropagation(QWidget::SameFont);
    qtarch_TypeGroup->setFrameStyle( 0 );
    qtarch_TypeGroup->setLineWidth( 1 );
    qtarch_TypeGroup->setMidLineWidth( 0 );
    qtarch_TypeGroup->QFrame::setMargin( 0 );
    qtarch_TypeGroup->setTitle( "" );
    qtarch_TypeGroup->setAlignment( AlignLeft );
    qtarch_TypeGroup->setExclusive( FALSE );

    active = new QCheckBox(qtarch_TypeGroup, "ActiveButton");
    active->setGeometry(8, 8, 92, 19);
    active->setMinimumSize(0, 0);
    active->setMaximumSize(32767, 32767);
    active->setFocusPolicy(QWidget::TabFocus);
    active->setBackgroundMode(QWidget::PaletteBackground);
    //active->setFontPropagation(QWidget::SameFont);
    //active->setPalettePropagation(QWidget::SameFont);
    active->setText( "Active" );
    active->setAutoRepeat( FALSE );
    active->setAutoResize( FALSE );
    active->setChecked( FALSE );

    international = new QCheckBox(qtarch_TypeGroup, "InternationalButton");
    international->setGeometry(8, 32, 92, 19);
    international->setMinimumSize(0, 0);
    international->setMaximumSize(32767, 32767);
    international->setFocusPolicy(QWidget::TabFocus);
    international->setBackgroundMode(QWidget::PaletteBackground);
    //international->setFontPropagation(QWidget::SameFont);
    //international->setPalettePropagation(QWidget::SameFont);
    international->setText( "International" );
    international->setAutoRepeat( FALSE );
    international->setAutoResize( FALSE );
    international->setChecked( FALSE );
    connect(international, SIGNAL(toggled(bool)), SLOT(internationalChanged(bool)));

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QBoxLayout* qtarch_layout_1_1 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 0 );
	qtarch_layout_1_1->addStrut( 0 );
	qtarch_layout_1_1->addWidget( typeLabel, 0, 0 );
	qtarch_layout_1_1->addWidget( typeLabel2, 1, 0 );
	qtarch_layout_1->addWidget( qtarch_HLine1, 1, 0 );
	QBoxLayout* qtarch_layout_1_3 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_3, 0 );
	qtarch_layout_1_3->addStrut( 0 );
	qtarch_layout_1_3->addWidget( qtarch_TagLabel, 0, 0 );
	qtarch_layout_1_3->addWidget( tagList, 1, 0 );
	qtarch_layout_1_3->addWidget( tagLabel, 1, 0 );
	qtarch_layout_1_3->addWidget( qtarch_TypeGroup, 1, 0 );
	QGridLayout* qtarch_layout_1_4 = new QGridLayout( 1, 2, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_4, 0 );
	qtarch_layout_1_4->addColSpacing( 0, 5 );
	qtarch_layout_1_4->setColStretch( 0, 0 );
	qtarch_layout_1_4->addColSpacing( 1, 5 );
	qtarch_layout_1_4->setColStretch( 1, 1 );
	qtarch_layout_1_4->addRowSpacing( 0, 0 );
	qtarch_layout_1_4->setRowStretch( 0, 1 );
	qtarch_layout_1_4->addWidget( qtarch_PhoneNumberLabel, 0, 0, 0 );
	qtarch_layout_1_4->addWidget( phoneNumber, 0, 1, 0 );
	qtarch_layout_1->addStretch( 1 );
	QBoxLayout* qtarch_layout_1_6 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_6, 0 );
	qtarch_layout_1_6->addStrut( 0 );
	qtarch_layout_1_6->addWidget( qtarch_LastModifiedLabel, 0, 0 );
	qtarch_layout_1_6->addWidget( lastModified, 1, 0 );
	qtarch_layout_1_6->addWidget( qtarch_LastModifiedByLabel, 0, 0 );
	qtarch_layout_1_6->addWidget( lastModifiedBy, 1, 0 );
	qtarch_layout_1->addStretch( 1 );
	QBoxLayout* qtarch_layout_1_8 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_8, 1 );
	qtarch_layout_1_8->addStrut( 0 );
	qtarch_layout_1_8->addStretch( 1 );
	qtarch_layout_1_8->addWidget( saveButton, 0, 0 );
	qtarch_layout_1_8->addWidget( canelButton, 0, 0 );
    resize(370,195);
    setMinimumSize(0, 0);
    setMaximumSize(32767, 32767);
}

PhoneEditorData::~PhoneEditorData()
{
}
