/**********************************************************************

	--- Qt Architect generated file ---

	File: AccountsData.cpp
	Last generated: Mon Apr 24 19:29:01 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "AccountsData.h"

#include <qpushbutton.h>

AccountsData::AccountsData(QWidget *parent, const char *name)
             : QWidget(parent, name, 0)
{
    menu = new QMenuBar(this, "MainMenu");
    menu->setGeometry(0, 0, 465, 25);
    menu->setMinimumSize(10, 25);
    menu->setMaximumSize(32767, 25);
    menu->setFocusPolicy(QWidget::NoFocus);
    menu->setBackgroundMode(QWidget::PaletteBackground);
    menu->setFrameStyle( 0 );
    menu->setLineWidth( 1 );
    menu->setMidLineWidth( 0 );
    menu->QFrame::setMargin( 0 );

    QPushButton *qtarch_NewButton = new QPushButton(this, "NewButton");
    qtarch_NewButton->setGeometry(0, 27, 65, 25);
    qtarch_NewButton->setMinimumSize(65, 25);
    qtarch_NewButton->setMaximumSize(65, 25);
    qtarch_NewButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_NewButton->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_NewButton->setText( "New" );
    qtarch_NewButton->setAutoRepeat( FALSE );
    qtarch_NewButton->setAutoResize( FALSE );
    qtarch_NewButton->setToggleButton( FALSE );
    qtarch_NewButton->setDefault( FALSE );
    qtarch_NewButton->setAutoDefault( FALSE );
    qtarch_NewButton->setIsMenuButton( FALSE );
    connect(qtarch_NewButton, SIGNAL(clicked()), SLOT(newAccount()));

    QPushButton *qtarch_EditButton = new QPushButton(this, "EditButton");
    qtarch_EditButton->setGeometry(65, 27, 65, 25);
    qtarch_EditButton->setMinimumSize(65, 25);
    qtarch_EditButton->setMaximumSize(65, 25);
    qtarch_EditButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_EditButton->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_EditButton->setText( "Edit" );
    qtarch_EditButton->setAutoRepeat( FALSE );
    qtarch_EditButton->setAutoResize( FALSE );
    qtarch_EditButton->setToggleButton( FALSE );
    qtarch_EditButton->setDefault( FALSE );
    qtarch_EditButton->setAutoDefault( FALSE );
    qtarch_EditButton->setIsMenuButton( FALSE );
    connect(qtarch_EditButton, SIGNAL(clicked()), SLOT(editAccount()));

    QPushButton *qtarch_DeleteButton = new QPushButton(this, "DeleteButton");
    qtarch_DeleteButton->setGeometry(130, 27, 65, 25);
    qtarch_DeleteButton->setMinimumSize(65, 25);
    qtarch_DeleteButton->setMaximumSize(65, 25);
    qtarch_DeleteButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_DeleteButton->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_DeleteButton->setText( "Delete" );
    qtarch_DeleteButton->setAutoRepeat( FALSE );
    qtarch_DeleteButton->setAutoResize( FALSE );
    qtarch_DeleteButton->setToggleButton( FALSE );
    qtarch_DeleteButton->setDefault( FALSE );
    qtarch_DeleteButton->setAutoDefault( FALSE );
    qtarch_DeleteButton->setIsMenuButton( FALSE );
    connect(qtarch_DeleteButton, SIGNAL(clicked()), SLOT(deleteAccount()));

    QPushButton *qtarch_CloseButton = new QPushButton(this, "CloseButton");
    qtarch_CloseButton->setGeometry(195, 27, 65, 25);
    qtarch_CloseButton->setMinimumSize(65, 25);
    qtarch_CloseButton->setMaximumSize(65, 25);
    qtarch_CloseButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_CloseButton->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_CloseButton->setText( "Close" );
    qtarch_CloseButton->setAutoRepeat( FALSE );
    qtarch_CloseButton->setAutoResize( FALSE );
    qtarch_CloseButton->setToggleButton( FALSE );
    qtarch_CloseButton->setDefault( FALSE );
    qtarch_CloseButton->setAutoDefault( FALSE );
    qtarch_CloseButton->setIsMenuButton( FALSE );
    connect(qtarch_CloseButton, SIGNAL(clicked()), SLOT(Hide()));

    QPushButton *qtarch_RegisterButton = new QPushButton(this, "RegisterButton");
    qtarch_RegisterButton->setGeometry(260, 27, 65, 25);
    qtarch_RegisterButton->setMinimumSize(65, 25);
    qtarch_RegisterButton->setMaximumSize(65, 25);
    qtarch_RegisterButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_RegisterButton->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_RegisterButton->setText( "Register" );
    qtarch_RegisterButton->setAutoRepeat( FALSE );
    qtarch_RegisterButton->setAutoResize( FALSE );
    qtarch_RegisterButton->setToggleButton( FALSE );
    qtarch_RegisterButton->setDefault( FALSE );
    qtarch_RegisterButton->setAutoDefault( FALSE );
    qtarch_RegisterButton->setIsMenuButton( FALSE );

    list = new QListView(this, "AccountList");
    list->setGeometry(0, 54, 465, 178);
    list->setMinimumSize(0, 0);
    list->setMaximumSize(32767, 32767);
    list->setFocusPolicy(QWidget::TabFocus);
    list->setBackgroundMode(QWidget::PaletteBackground);
    list->setFrameStyle( 17 );
    list->setLineWidth( 2 );
    list->setMidLineWidth( 0 );
    list->QFrame::setMargin( 0 );
    list->setResizePolicy( QScrollView::Manual );
    list->setVScrollBarMode( QScrollView::Auto );
    list->setHScrollBarMode( QScrollView::Auto );
    list->setTreeStepSize( 20 );
    list->setMultiSelection( FALSE );
    list->setAllColumnsShowFocus( FALSE );
    list->setItemMargin( 1 );
    list->setRootIsDecorated( FALSE );
    list->addColumn( "Account Number", -1 );
    list->setColumnWidthMode( 0, QListView::Maximum );
    list->setColumnAlignment( 0, 1 );
    list->addColumn( "Account Name", -1 );
    list->setColumnWidthMode( 1, QListView::Maximum );
    list->setColumnAlignment( 1, 1 );
    list->addColumn( "Account Type", -1 );
    list->setColumnWidthMode( 2, QListView::Maximum );
    list->setColumnAlignment( 2, 1 );
    list->addColumn( "Current Balance", -1 );
    list->setColumnWidthMode( 3, QListView::Maximum );
    list->setColumnAlignment( 3, 2 );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 0, 2, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( menu, 1, 0 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( QBoxLayout::LeftToRight, 0, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 0 );
	qtarch_layout_1_2->addStrut( 0 );
	qtarch_layout_1_2->addWidget( qtarch_NewButton, 0, 36 );
	qtarch_layout_1_2->addWidget( qtarch_EditButton, 0, 36 );
	qtarch_layout_1_2->addWidget( qtarch_DeleteButton, 0, 36 );
	qtarch_layout_1_2->addWidget( qtarch_CloseButton, 0, 36 );
	qtarch_layout_1_2->addWidget( qtarch_RegisterButton, 0, 36 );
	qtarch_layout_1_2->addStretch( 1 );
	qtarch_layout_1->addWidget( list, 1, 0 );
    resize(465,232);
    setMinimumSize(0, 0);
    setMaximumSize(32767, 32767);
}

AccountsData::~AccountsData()
{
}
