/**********************************************************************

	--- Qt Architect generated file ---

	File: AccountsEditData.cpp
	Last generated: Mon Apr 24 19:28:02 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "AccountsEditData.h"

#include <qlabel.h>
#include <qpushbutton.h>
#include <qframe.h>

AccountsEditData::AccountsEditData(QWidget *parent, const char *name)
                 : QWidget(parent, name, 0)
{
    QFrame *qtarch_infoFrame = new QFrame(this, "infoFrame");
    qtarch_infoFrame->setGeometry(5, 144, 440, 62);
    qtarch_infoFrame->setMinimumSize(0, 0);
    qtarch_infoFrame->setMaximumSize(32767, 32767);
    qtarch_infoFrame->setFocusPolicy(QWidget::NoFocus);
    qtarch_infoFrame->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_infoFrame->setFrameStyle( 51 );
    qtarch_infoFrame->setLineWidth( 2 );
    qtarch_infoFrame->setMidLineWidth( 0 );
    qtarch_infoFrame->QFrame::setMargin( 0 );

    QLabel *qtarch_AcctNumberLabel = new QLabel(qtarch_infoFrame, "AcctNumberLabel");
    qtarch_AcctNumberLabel->setGeometry(5, 5, 104, 13);
    qtarch_AcctNumberLabel->setMinimumSize(0, 0);
    qtarch_AcctNumberLabel->setMaximumSize(32767, 32767);
    qtarch_AcctNumberLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_AcctNumberLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_AcctNumberLabel->setFrameStyle( 0 );
    qtarch_AcctNumberLabel->setLineWidth( 1 );
    qtarch_AcctNumberLabel->setMidLineWidth( 0 );
    qtarch_AcctNumberLabel->QFrame::setMargin( -1 );
    qtarch_AcctNumberLabel->setText( "Account Number:" );
    qtarch_AcctNumberLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_AcctNumberLabel->setMargin( -1 );

    accountNo = new QLabel(qtarch_infoFrame, "accountNo");
    accountNo->setGeometry(114, 5, 132, 13);
    accountNo->setMinimumSize(0, 0);
    accountNo->setMaximumSize(32767, 32767);
    accountNo->setFocusPolicy(QWidget::NoFocus);
    accountNo->setBackgroundMode(QWidget::PaletteBackground);
    accountNo->setFrameStyle( 51 );
    accountNo->setLineWidth( 2 );
    accountNo->setMidLineWidth( 0 );
    accountNo->QFrame::setMargin( -1 );
    accountNo->setText( "" );
    accountNo->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    accountNo->setMargin( -1 );

    QLabel *qtarch_balanceLabel = new QLabel(qtarch_infoFrame, "balanceLabel");
    qtarch_balanceLabel->setGeometry(251, 5, 48, 13);
    qtarch_balanceLabel->setMinimumSize(0, 0);
    qtarch_balanceLabel->setMaximumSize(32767, 32767);
    qtarch_balanceLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_balanceLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_balanceLabel->setFrameStyle( 0 );
    qtarch_balanceLabel->setLineWidth( 1 );
    qtarch_balanceLabel->setMidLineWidth( 0 );
    qtarch_balanceLabel->QFrame::setMargin( -1 );
    qtarch_balanceLabel->setText( "Balance:" );
    qtarch_balanceLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_balanceLabel->setMargin( -1 );

    balance = new QLabel(qtarch_infoFrame, "balance");
    balance->setGeometry(304, 5, 131, 13);
    balance->setMinimumSize(0, 0);
    balance->setMaximumSize(32767, 32767);
    balance->setFocusPolicy(QWidget::NoFocus);
    balance->setBackgroundMode(QWidget::PaletteBackground);
    balance->setFrameStyle( 51 );
    balance->setLineWidth( 2 );
    balance->setMidLineWidth( 0 );
    balance->QFrame::setMargin( -1 );
    balance->setText( "" );
    balance->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    balance->setMargin( -1 );

    QLabel *qtarch_TransCountLabel = new QLabel(qtarch_infoFrame, "TransCountLabel");
    qtarch_TransCountLabel->setGeometry(5, 23, 104, 13);
    qtarch_TransCountLabel->setMinimumSize(0, 0);
    qtarch_TransCountLabel->setMaximumSize(32767, 32767);
    qtarch_TransCountLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_TransCountLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_TransCountLabel->setFrameStyle( 0 );
    qtarch_TransCountLabel->setLineWidth( 1 );
    qtarch_TransCountLabel->setMidLineWidth( 0 );
    qtarch_TransCountLabel->QFrame::setMargin( -1 );
    qtarch_TransCountLabel->setText( "Transaction Count:" );
    qtarch_TransCountLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_TransCountLabel->setMargin( -1 );

    transCount = new QLabel(qtarch_infoFrame, "transCount");
    transCount->setGeometry(114, 23, 132, 13);
    transCount->setMinimumSize(0, 0);
    transCount->setMaximumSize(32767, 32767);
    transCount->setFocusPolicy(QWidget::NoFocus);
    transCount->setBackgroundMode(QWidget::PaletteBackground);
    transCount->setFrameStyle( 51 );
    transCount->setLineWidth( 2 );
    transCount->setMidLineWidth( 0 );
    transCount->QFrame::setMargin( -1 );
    transCount->setText( "" );
    transCount->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    transCount->setMargin( -1 );

    QLabel *qtarch_NameLabel = new QLabel(this, "NameLabel");
    qtarch_NameLabel->setGeometry(5, 5, 128, 22);
    qtarch_NameLabel->setMinimumSize(0, 0);
    qtarch_NameLabel->setMaximumSize(32767, 32767);
    qtarch_NameLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_NameLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_NameLabel->setFrameStyle( 0 );
    qtarch_NameLabel->setLineWidth( 1 );
    qtarch_NameLabel->setMidLineWidth( 0 );
    qtarch_NameLabel->QFrame::setMargin( -1 );
    qtarch_NameLabel->setText( "Name:" );
    qtarch_NameLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_NameLabel->setMargin( -1 );

    QLabel *qtarch_subAcctLabel = new QLabel(this, "subAcctLabel");
    qtarch_subAcctLabel->setGeometry(5, 32, 128, 25);
    qtarch_subAcctLabel->setMinimumSize(0, 0);
    qtarch_subAcctLabel->setMaximumSize(32767, 32767);
    qtarch_subAcctLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_subAcctLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_subAcctLabel->setFrameStyle( 0 );
    qtarch_subAcctLabel->setLineWidth( 1 );
    qtarch_subAcctLabel->setMidLineWidth( 0 );
    qtarch_subAcctLabel->QFrame::setMargin( -1 );
    qtarch_subAcctLabel->setText( "Sub-account of:" );
    qtarch_subAcctLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_subAcctLabel->setMargin( -1 );

    acctName = new QLineEdit(this, "acctName");
    acctName->setGeometry(138, 5, 307, 22);
    acctName->setMinimumSize(0, 0);
    acctName->setMaximumSize(32767, 32767);
    acctName->setFocusPolicy(QWidget::StrongFocus);
    acctName->setBackgroundMode(QWidget::PaletteBase);
    acctName->setText( "" );
    acctName->setMaxLength( 30 );
    acctName->setFrame( QLineEdit::Normal );
    acctName->setFrame( TRUE );
    acctName->setAlignment( AlignLeft );

    subAcctOf = new QComboBox(FALSE, this, "subAcctList");
    subAcctOf->setGeometry(138, 32, 307, 25);
    subAcctOf->setMinimumSize(0, 0);
    subAcctOf->setMaximumSize(32767, 32767);
    subAcctOf->setFocusPolicy(QWidget::StrongFocus);
    subAcctOf->setBackgroundMode(QWidget::NoBackground);
    subAcctOf->setSizeLimit( 10 );
    subAcctOf->setAutoResize( FALSE );
    subAcctOf->insertItem( "None" );
    subAcctOf->setMaxCount( 2147483647 );
    subAcctOf->setAutoCompletion( FALSE );

    QLabel *qtarch_acctTypeLabel = new QLabel(this, "acctTypeLabel");
    qtarch_acctTypeLabel->setGeometry(5, 62, 128, 25);
    qtarch_acctTypeLabel->setMinimumSize(0, 0);
    qtarch_acctTypeLabel->setMaximumSize(32767, 32767);
    qtarch_acctTypeLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_acctTypeLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_acctTypeLabel->setFrameStyle( 0 );
    qtarch_acctTypeLabel->setLineWidth( 1 );
    qtarch_acctTypeLabel->setMidLineWidth( 0 );
    qtarch_acctTypeLabel->QFrame::setMargin( -1 );
    qtarch_acctTypeLabel->setText( "Account Type:" );
    qtarch_acctTypeLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_acctTypeLabel->setMargin( -1 );

    acctType = new QComboBox(FALSE, this, "acctTypeList");
    acctType->setGeometry(138, 62, 307, 25);
    acctType->setMinimumSize(0, 0);
    acctType->setMaximumSize(32767, 32767);
    acctType->setFocusPolicy(QWidget::StrongFocus);
    acctType->setBackgroundMode(QWidget::NoBackground);
    acctType->setSizeLimit( 10 );
    acctType->setAutoResize( FALSE );
    acctType->insertItem( "Bank" );
    acctType->insertItem( "Accounts Receivable" );
    acctType->insertItem( "Other Current Asset" );
    acctType->insertItem( "Fixed Asset" );
    acctType->insertItem( "Other Asset" );
    acctType->insertItem( "Accounts Payable" );
    acctType->insertItem( "Credit Card" );
    acctType->insertItem( "Other Current Liability" );
    acctType->insertItem( "Long Term Liability" );
    acctType->insertItem( "Capital/Equity" );
    acctType->insertItem( "Income" );
    acctType->insertItem( "Cost of Goods Sold" );
    acctType->insertItem( "Expense" );
    acctType->insertItem( "Other Income" );
    acctType->insertItem( "Other Expense" );
    acctType->setMaxCount( 2147483647 );
    acctType->setAutoCompletion( FALSE );

    QLabel *qtarch_acctNumberLabel = new QLabel(this, "acctNumberLabel");
    qtarch_acctNumberLabel->setGeometry(5, 92, 128, 22);
    qtarch_acctNumberLabel->setMinimumSize(0, 0);
    qtarch_acctNumberLabel->setMaximumSize(32767, 32767);
    qtarch_acctNumberLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_acctNumberLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_acctNumberLabel->setFrameStyle( 0 );
    qtarch_acctNumberLabel->setLineWidth( 1 );
    qtarch_acctNumberLabel->setMidLineWidth( 0 );
    qtarch_acctNumberLabel->QFrame::setMargin( -1 );
    qtarch_acctNumberLabel->setText( "Bank/Account Number:" );
    qtarch_acctNumberLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_acctNumberLabel->setMargin( -1 );

    acctNumber = new QLineEdit(this, "acctNumber");
    acctNumber->setGeometry(138, 92, 307, 22);
    acctNumber->setMinimumSize(0, 0);
    acctNumber->setMaximumSize(32767, 32767);
    acctNumber->setFocusPolicy(QWidget::StrongFocus);
    acctNumber->setBackgroundMode(QWidget::PaletteBase);
    acctNumber->setText( "" );
    acctNumber->setMaxLength( 30 );
    acctNumber->setFrame( QLineEdit::Normal );
    acctNumber->setFrame( TRUE );
    acctNumber->setAlignment( AlignLeft );

    QLabel *qtarch_taxLineLabel = new QLabel(this, "taxLineLabel");
    qtarch_taxLineLabel->setGeometry(5, 119, 128, 22);
    qtarch_taxLineLabel->setMinimumSize(0, 0);
    qtarch_taxLineLabel->setMaximumSize(32767, 32767);
    qtarch_taxLineLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_taxLineLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_taxLineLabel->setFrameStyle( 0 );
    qtarch_taxLineLabel->setLineWidth( 1 );
    qtarch_taxLineLabel->setMidLineWidth( 0 );
    qtarch_taxLineLabel->QFrame::setMargin( -1 );
    qtarch_taxLineLabel->setText( "Tax Line:" );
    qtarch_taxLineLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_taxLineLabel->setMargin( -1 );

    QPushButton *qtarch_saveButton = new QPushButton(this, "saveButton");
    qtarch_saveButton->setGeometry(305, 209, 62, 26);
    qtarch_saveButton->setMinimumSize(0, 0);
    qtarch_saveButton->setMaximumSize(32767, 32767);
    qtarch_saveButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_saveButton->setBackgroundMode(QWidget::PaletteButton);
    qtarch_saveButton->setText( "&Save" );
    qtarch_saveButton->setAutoRepeat( FALSE );
    qtarch_saveButton->setAutoResize( FALSE );
    qtarch_saveButton->setToggleButton( FALSE );
    qtarch_saveButton->setDefault( FALSE );
    qtarch_saveButton->setAutoDefault( FALSE );
    qtarch_saveButton->setIsMenuButton( FALSE );
    connect(qtarch_saveButton, SIGNAL(clicked()), SLOT(saveAccount()));

    QPushButton *qtarch_cancelButton = new QPushButton(this, "cancelButton");
    qtarch_cancelButton->setGeometry(372, 209, 73, 26);
    qtarch_cancelButton->setMinimumSize(0, 0);
    qtarch_cancelButton->setMaximumSize(32767, 32767);
    qtarch_cancelButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_cancelButton->setBackgroundMode(QWidget::PaletteButton);
    qtarch_cancelButton->setText( "&Cancel" );
    qtarch_cancelButton->setAutoRepeat( FALSE );
    qtarch_cancelButton->setAutoResize( FALSE );
    qtarch_cancelButton->setToggleButton( FALSE );
    qtarch_cancelButton->setDefault( FALSE );
    qtarch_cancelButton->setAutoDefault( FALSE );
    qtarch_cancelButton->setIsMenuButton( FALSE );
    connect(qtarch_cancelButton, SIGNAL(clicked()), SLOT(cancelAccount()));

    taxLine = new QLineEdit(this, "taxLine");
    taxLine->setGeometry(138, 119, 307, 22);
    taxLine->setMinimumSize(0, 0);
    taxLine->setMaximumSize(32767, 32767);
    taxLine->setFocusPolicy(QWidget::StrongFocus);
    taxLine->setBackgroundMode(QWidget::PaletteBase);
    taxLine->setText( "" );
    taxLine->setMaxLength( 255 );
    taxLine->setFrame( QLineEdit::Normal );
    taxLine->setFrame( TRUE );
    taxLine->setAlignment( AlignLeft );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 3, NULL );
	qtarch_layout_1->addStrut( 0 );
	QGridLayout* qtarch_layout_1_1 = new QGridLayout( 5, 2, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 0 );
	qtarch_layout_1_1->addColSpacing( 0, 5 );
	qtarch_layout_1_1->setColStretch( 0, 0 );
	qtarch_layout_1_1->addColSpacing( 1, 5 );
	qtarch_layout_1_1->setColStretch( 1, 1 );
	qtarch_layout_1_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_1->setRowStretch( 0, 1 );
	qtarch_layout_1_1->addWidget( qtarch_NameLabel, 0, 0, 0 );
	qtarch_layout_1_1->addWidget( acctName, 0, 1, 0 );
	qtarch_layout_1_1->addRowSpacing( 1, 0 );
	qtarch_layout_1_1->setRowStretch( 1, 1 );
	qtarch_layout_1_1->addWidget( qtarch_subAcctLabel, 1, 0, 0 );
	qtarch_layout_1_1->addWidget( subAcctOf, 1, 1, 0 );
	qtarch_layout_1_1->addRowSpacing( 2, 0 );
	qtarch_layout_1_1->setRowStretch( 2, 1 );
	qtarch_layout_1_1->addWidget( qtarch_acctTypeLabel, 2, 0, 0 );
	qtarch_layout_1_1->addWidget( acctType, 2, 1, 0 );
	qtarch_layout_1_1->addRowSpacing( 3, 0 );
	qtarch_layout_1_1->setRowStretch( 3, 1 );
	qtarch_layout_1_1->addWidget( qtarch_acctNumberLabel, 3, 0, 0 );
	qtarch_layout_1_1->addWidget( acctNumber, 3, 1, 0 );
	qtarch_layout_1_1->addRowSpacing( 4, 0 );
	qtarch_layout_1_1->setRowStretch( 4, 1 );
	qtarch_layout_1_1->addWidget( qtarch_taxLineLabel, 4, 0, 0 );
	qtarch_layout_1_1->addWidget( taxLine, 4, 1, 0 );
	qtarch_layout_1->addWidget( qtarch_infoFrame, 1, 0 );
	QGridLayout* qtarch_layout_1_2 = new QGridLayout( qtarch_infoFrame, 3, 4, 5, 5, NULL );
	qtarch_layout_1_2->addColSpacing( 0, 5 );
	qtarch_layout_1_2->setColStretch( 0, 0 );
	qtarch_layout_1_2->addColSpacing( 1, 5 );
	qtarch_layout_1_2->setColStretch( 1, 1 );
	qtarch_layout_1_2->addColSpacing( 2, 5 );
	qtarch_layout_1_2->setColStretch( 2, 0 );
	qtarch_layout_1_2->addColSpacing( 3, 5 );
	qtarch_layout_1_2->setColStretch( 3, 1 );
	qtarch_layout_1_2->addRowSpacing( 0, 0 );
	qtarch_layout_1_2->setRowStretch( 0, 0 );
	qtarch_layout_1_2->addWidget( qtarch_AcctNumberLabel, 0, 0, 0 );
	qtarch_layout_1_2->addWidget( accountNo, 0, 1, 0 );
	qtarch_layout_1_2->addWidget( qtarch_balanceLabel, 0, 2, 0 );
	qtarch_layout_1_2->addWidget( balance, 0, 3, 0 );
	qtarch_layout_1_2->addRowSpacing( 1, 0 );
	qtarch_layout_1_2->setRowStretch( 1, 0 );
	qtarch_layout_1_2->addWidget( qtarch_TransCountLabel, 1, 0, 0 );
	qtarch_layout_1_2->addWidget( transCount, 1, 1, 0 );
	qtarch_layout_1_2->addRowSpacing( 2, 0 );
	qtarch_layout_1_2->setRowStretch( 2, 1 );
	QBoxLayout* qtarch_layout_1_3 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_3, 0 );
	qtarch_layout_1_3->addStrut( 0 );
	qtarch_layout_1_3->addStretch( 1 );
	qtarch_layout_1_3->addWidget( qtarch_saveButton, 0, 0 );
	qtarch_layout_1_3->addWidget( qtarch_cancelButton, 0, 0 );
    resize(450,240);
    setMinimumSize(0, 0);
    setMaximumSize(32767, 32767);
}

AccountsEditData::~AccountsEditData()
{
}
