/**********************************************************************

	--- Qt Architect generated file ---

	File: AccountsData.h
	Last generated: Mon Apr 24 19:29:01 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef AccountsData_included
#define AccountsData_included

#include <qwidget.h>
#include <qlistview.h>
#include <qmenubar.h>

class AccountsData : public QWidget
{
    Q_OBJECT

public:

    AccountsData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~AccountsData();

    protected slots:

    virtual void Hide() =0;
    virtual void editAccount() =0;
    virtual void newAccount() =0;
    virtual void deleteAccount() =0;

    protected:

    QMenuBar *menu;
    QListView *list;
};

#endif // AccountsData_included
