/**********************************************************************

	--- Qt Architect generated file ---

	File: AccountsEditData.h
	Last generated: Mon Apr 24 19:28:02 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef AccountsEditData_included
#define AccountsEditData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qcombobox.h>
#include <qlineedit.h>

class AccountsEditData : public QWidget
{
    Q_OBJECT

public:

    AccountsEditData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~AccountsEditData();

    protected slots:

    virtual void saveAccount() =0;
    virtual void cancelAccount() =0;

    protected:

    QLineEdit *acctName;
    QComboBox *subAcctOf;
    QComboBox *acctType;
    QLineEdit *acctNumber;
    QLabel *accountNo;
    QLabel *balance;
    QLabel *transCount;
    QLineEdit *taxLine;
};

#endif // AccountsEditData_included
