/**********************************************************************

	--- Qt Architect generated file ---

	File: AddBaseTypeLinkData.h
	Last generated: Sat Dec 13 05:27:12 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef AddBaseTypeLinkData_included
#define AddBaseTypeLinkData_included

#include <qdialog.h>
#include <qpushbt.h>
#include <qlistbox.h>

class AddBaseTypeLinkData : public QDialog
{
    Q_OBJECT

public:

    AddBaseTypeLinkData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~AddBaseTypeLinkData();

public slots:


protected slots:

    virtual void itemSelected(int);

protected:
    QListBox* baseItemList;
    QPushButton* acceptButton;
    QPushButton* cancelButton;

};

#endif // AddBaseTypeLinkData_included
