/**********************************************************************

	--- Qt Architect generated file ---

	File: BaseListData.h
	Last generated: Thu Jan 21 14:56:03 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef BaseListData_included
#define BaseListData_included

#include <qdialog.h>
#include <qlistview.h>
#include <qmenubar.h>

class BaseListData : public QDialog
{
    Q_OBJECT

public:

    BaseListData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~BaseListData();

public slots:


protected slots:

    virtual void Hide();
    virtual void editItem();
    virtual void newItem();
    virtual void deleteItem();

protected:
    QMenuBar* menu;
    QListView* list;

};

#endif // BaseListData_included
