/**********************************************************************

	--- Qt Architect generated file ---

	File: BaseListData.cpp
	Last generated: Thu Jan 21 14:56:03 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "BaseListData.h"

#define Inherited QDialog

#include <qpushbt.h>

BaseListData::BaseListData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, FALSE, 0 )
{
	menu = new QMenuBar( this, "MenuBar_1" );
	menu->setGeometry( 0, 0, 468, 30 );
	menu->setMinimumSize( 0, 30 );
	menu->setMaximumSize( 32767, 30 );
	menu->setFocusPolicy( QWidget::NoFocus );
	menu->setBackgroundMode( QWidget::PaletteBackground );
	menu->setFrameStyle( 34 );
	menu->setLineWidth( 2 );

	QPushButton* qtarch_PushButton_14;
	qtarch_PushButton_14 = new QPushButton( this, "PushButton_14" );
	qtarch_PushButton_14->setGeometry( 0, 30, 70, 30 );
	qtarch_PushButton_14->setMinimumSize( 70, 30 );
	qtarch_PushButton_14->setMaximumSize( 70, 30 );
	connect( qtarch_PushButton_14, SIGNAL(clicked()), SLOT(newItem()) );
	qtarch_PushButton_14->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_14->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_14->setText( "&New" );
	qtarch_PushButton_14->setAutoRepeat( FALSE );
	qtarch_PushButton_14->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_15;
	qtarch_PushButton_15 = new QPushButton( this, "PushButton_15" );
	qtarch_PushButton_15->setGeometry( 70, 30, 70, 30 );
	qtarch_PushButton_15->setMinimumSize( 70, 30 );
	qtarch_PushButton_15->setMaximumSize( 70, 30 );
	connect( qtarch_PushButton_15, SIGNAL(clicked()), SLOT(editItem()) );
	qtarch_PushButton_15->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_15->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_15->setText( "&Edit" );
	qtarch_PushButton_15->setAutoRepeat( FALSE );
	qtarch_PushButton_15->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_16;
	qtarch_PushButton_16 = new QPushButton( this, "PushButton_16" );
	qtarch_PushButton_16->setGeometry( 140, 30, 70, 30 );
	qtarch_PushButton_16->setMinimumSize( 70, 30 );
	qtarch_PushButton_16->setMaximumSize( 70, 30 );
	connect( qtarch_PushButton_16, SIGNAL(clicked()), SLOT(deleteItem()) );
	qtarch_PushButton_16->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_16->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_16->setText( "&Delete" );
	qtarch_PushButton_16->setAutoRepeat( FALSE );
	qtarch_PushButton_16->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_17;
	qtarch_PushButton_17 = new QPushButton( this, "PushButton_17" );
	qtarch_PushButton_17->setGeometry( 210, 30, 70, 30 );
	qtarch_PushButton_17->setMinimumSize( 70, 30 );
	qtarch_PushButton_17->setMaximumSize( 70, 30 );
	connect( qtarch_PushButton_17, SIGNAL(clicked()), SLOT(Hide()) );
	qtarch_PushButton_17->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_17->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_17->setText( "&Close" );
	qtarch_PushButton_17->setAutoRepeat( FALSE );
	qtarch_PushButton_17->setAutoResize( FALSE );

	list = new QListView( this, "ListView_2" );
	list->setGeometry( 0, 60, 468, 251 );
	list->setMinimumSize( 0, 0 );
	list->setMaximumSize( 32767, 32767 );
	list->setFocusPolicy( QWidget::TabFocus );
	list->setBackgroundMode( QWidget::PaletteBackground );
	list->setResizePolicy( QScrollView::Manual );
	list->setVScrollBarMode( QScrollView::Auto );
	list->setHScrollBarMode( QScrollView::Auto );
	list->setTreeStepSize( 20 );
	list->setMultiSelection( FALSE );
	list->setAllColumnsShowFocus( FALSE );
	list->setItemMargin( 1 );
	list->setRootIsDecorated( FALSE );
	list->addColumn( "Item ID", -1 );
	list->setColumnWidthMode( 0, QListView::Maximum );
	list->setColumnAlignment( 0, 1 );

	QGridLayout* qtarch_layout_1 = new QGridLayout( this, 3, 1, 0, 0, NULL );
	qtarch_layout_1->addColSpacing( 0, 5 );
	qtarch_layout_1->setColStretch( 0, 1 );
	qtarch_layout_1->addRowSpacing( 0, 0 );
	qtarch_layout_1->setRowStretch( 0, 0 );
	qtarch_layout_1->addWidget( menu, 0, 0, 9 );
	qtarch_layout_1->addRowSpacing( 1, 0 );
	qtarch_layout_1->setRowStretch( 1, 0 );
	QBoxLayout* qtarch_layout_1_2_1 = new QBoxLayout( QBoxLayout::LeftToRight, 0, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2_1, 1, 0 );
	qtarch_layout_1_2_1->addStrut( 0 );
	qtarch_layout_1_2_1->addWidget( qtarch_PushButton_14, 0, 9 );
	qtarch_layout_1_2_1->addWidget( qtarch_PushButton_15, 0, 9 );
	qtarch_layout_1_2_1->addWidget( qtarch_PushButton_16, 0, 9 );
	qtarch_layout_1_2_1->addWidget( qtarch_PushButton_17, 0, 9 );
	qtarch_layout_1_2_1->addStretch( 1 );
	qtarch_layout_1->addRowSpacing( 2, 0 );
	qtarch_layout_1->setRowStretch( 2, 1 );
	qtarch_layout_1->addWidget( list, 2, 0, 36 );
	resize( 468,311 );
	setMinimumSize( 468, 311 );
	setMaximumSize( 32767, 32767 );
}


BaseListData::~BaseListData()
{
}
void BaseListData::newItem()
{
}
void BaseListData::editItem()
{
}
void BaseListData::deleteItem()
{
}
void BaseListData::Hide()
{
}
