/**********************************************************************

	--- Qt Architect generated file ---

	File: BillingCycleEditData.cpp
	Last generated: Mon May 11 11:46:43 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "BillingCycleEditData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>

BillingCycleEditData::BillingCycleEditData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QLabel* dlgedit_Label_29;
	dlgedit_Label_29 = new QLabel( this, "Label_29" );
	dlgedit_Label_29->setGeometry( 30, 20, 100, 20 );
	dlgedit_Label_29->setMinimumSize( 10, 10 );
	dlgedit_Label_29->setMaximumSize( 32767, 32767 );
	dlgedit_Label_29->setText( "Cycle ID:" );
	dlgedit_Label_29->setAlignment( 290 );
	dlgedit_Label_29->setMargin( -1 );

	cycleID = new QLineEdit( this, "LineEdit_12" );
	cycleID->setGeometry( 140, 20, 120, 20 );
	cycleID->setMinimumSize( 10, 10 );
	cycleID->setMaximumSize( 32767, 32767 );
	cycleID->setText( "" );
	cycleID->setMaxLength( 16 );
	cycleID->setEchoMode( QLineEdit::Normal );
	cycleID->setFrame( TRUE );

	QLabel* dlgedit_Label_30;
	dlgedit_Label_30 = new QLabel( this, "Label_30" );
	dlgedit_Label_30->setGeometry( 30, 45, 100, 20 );
	dlgedit_Label_30->setMinimumSize( 10, 10 );
	dlgedit_Label_30->setMaximumSize( 32767, 32767 );
	dlgedit_Label_30->setText( "Description:" );
	dlgedit_Label_30->setAlignment( 290 );
	dlgedit_Label_30->setMargin( -1 );

	description = new QLineEdit( this, "LineEdit_13" );
	description->setGeometry( 140, 45, 290, 20 );
	description->setMinimumSize( 10, 10 );
	description->setMaximumSize( 32767, 32767 );
	description->setText( "" );
	description->setMaxLength( 32767 );
	description->setEchoMode( QLineEdit::Normal );
	description->setFrame( TRUE );

	QLabel* dlgedit_Label_31;
	dlgedit_Label_31 = new QLabel( this, "Label_31" );
	dlgedit_Label_31->setGeometry( 35, 70, 100, 20 );
	dlgedit_Label_31->setMinimumSize( 10, 10 );
	dlgedit_Label_31->setMaximumSize( 32767, 32767 );
	dlgedit_Label_31->setText( "Day of month:" );
	dlgedit_Label_31->setAlignment( 290 );
	dlgedit_Label_31->setMargin( -1 );

	day = new QLineEdit( this, "LineEdit_14" );
	day->setGeometry( 140, 70, 40, 20 );
	day->setMinimumSize( 10, 10 );
	day->setMaximumSize( 32767, 32767 );
	day->setText( "" );
	day->setMaxLength( 2 );
	day->setEchoMode( QLineEdit::Normal );
	day->setFrame( TRUE );

	QLabel* dlgedit_Label_32;
	dlgedit_Label_32 = new QLabel( this, "Label_32" );
	dlgedit_Label_32->setGeometry( 25, 95, 110, 20 );
	dlgedit_Label_32->setMinimumSize( 10, 10 );
	dlgedit_Label_32->setMaximumSize( 32767, 32767 );
	dlgedit_Label_32->setText( "Months processed:" );
	dlgedit_Label_32->setAlignment( 290 );
	dlgedit_Label_32->setMargin( -1 );

	january = new QCheckBox( this, "CheckBox_1" );
	january->setGeometry( 140, 95, 70, 20 );
	january->setMinimumSize( 10, 10 );
	january->setMaximumSize( 32767, 32767 );
	january->setText( "Jan" );
	january->setAutoRepeat( FALSE );
	january->setAutoResize( FALSE );

	february = new QCheckBox( this, "CheckBox_2" );
	february->setGeometry( 210, 95, 70, 20 );
	february->setMinimumSize( 10, 10 );
	february->setMaximumSize( 32767, 32767 );
	february->setText( "Feb" );
	february->setAutoRepeat( FALSE );
	february->setAutoResize( FALSE );

	march = new QCheckBox( this, "CheckBox_3" );
	march->setGeometry( 280, 95, 70, 20 );
	march->setMinimumSize( 10, 10 );
	march->setMaximumSize( 32767, 32767 );
	march->setText( "Mar" );
	march->setAutoRepeat( FALSE );
	march->setAutoResize( FALSE );

	april = new QCheckBox( this, "CheckBox_4" );
	april->setGeometry( 140, 115, 70, 20 );
	april->setMinimumSize( 10, 10 );
	april->setMaximumSize( 32767, 32767 );
	april->setText( "Apr" );
	april->setAutoRepeat( FALSE );
	april->setAutoResize( FALSE );

	may = new QCheckBox( this, "CheckBox_5" );
	may->setGeometry( 210, 115, 70, 20 );
	may->setMinimumSize( 10, 10 );
	may->setMaximumSize( 32767, 32767 );
	may->setText( "May" );
	may->setAutoRepeat( FALSE );
	may->setAutoResize( FALSE );

	june = new QCheckBox( this, "CheckBox_6" );
	june->setGeometry( 280, 115, 70, 20 );
	june->setMinimumSize( 10, 10 );
	june->setMaximumSize( 32767, 32767 );
	june->setText( "Jun" );
	june->setAutoRepeat( FALSE );
	june->setAutoResize( FALSE );

	july = new QCheckBox( this, "CheckBox_7" );
	july->setGeometry( 140, 135, 70, 20 );
	july->setMinimumSize( 10, 10 );
	july->setMaximumSize( 32767, 32767 );
	july->setText( "Jul" );
	july->setAutoRepeat( FALSE );
	july->setAutoResize( FALSE );

	august = new QCheckBox( this, "CheckBox_8" );
	august->setGeometry( 210, 135, 70, 20 );
	august->setMinimumSize( 10, 10 );
	august->setMaximumSize( 32767, 32767 );
	august->setText( "Aug" );
	august->setAutoRepeat( FALSE );
	august->setAutoResize( FALSE );

	september = new QCheckBox( this, "CheckBox_9" );
	september->setGeometry( 280, 135, 70, 20 );
	september->setMinimumSize( 10, 10 );
	september->setMaximumSize( 32767, 32767 );
	september->setText( "Sep" );
	september->setAutoRepeat( FALSE );
	september->setAutoResize( FALSE );

	october = new QCheckBox( this, "CheckBox_10" );
	october->setGeometry( 140, 155, 70, 20 );
	october->setMinimumSize( 10, 10 );
	october->setMaximumSize( 32767, 32767 );
	october->setText( "Oct" );
	october->setAutoRepeat( FALSE );
	october->setAutoResize( FALSE );

	november = new QCheckBox( this, "CheckBox_11" );
	november->setGeometry( 210, 155, 70, 20 );
	november->setMinimumSize( 10, 10 );
	november->setMaximumSize( 32767, 32767 );
	november->setText( "Nov" );
	november->setAutoRepeat( FALSE );
	november->setAutoResize( FALSE );

	december = new QCheckBox( this, "CheckBox_12" );
	december->setGeometry( 280, 155, 70, 20 );
	december->setMinimumSize( 10, 10 );
	december->setMaximumSize( 32767, 32767 );
	december->setText( "Dec" );
	december->setAutoRepeat( FALSE );
	december->setAutoResize( FALSE );

	QPushButton* dlgedit_PushButton_16;
	dlgedit_PushButton_16 = new QPushButton( this, "PushButton_16" );
	dlgedit_PushButton_16->setGeometry( 110, 220, 100, 30 );
	dlgedit_PushButton_16->setMinimumSize( 10, 10 );
	dlgedit_PushButton_16->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_16, SIGNAL(clicked()), SLOT(saveCycle()) );
	dlgedit_PushButton_16->setText( "&Save" );
	dlgedit_PushButton_16->setAutoRepeat( FALSE );
	dlgedit_PushButton_16->setAutoResize( FALSE );
	dlgedit_PushButton_16->setAutoDefault( TRUE );

	QPushButton* dlgedit_PushButton_17;
	dlgedit_PushButton_17 = new QPushButton( this, "PushButton_17" );
	dlgedit_PushButton_17->setGeometry( 235, 220, 100, 30 );
	dlgedit_PushButton_17->setMinimumSize( 10, 10 );
	dlgedit_PushButton_17->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_17, SIGNAL(clicked()), SLOT(cancelCycle()) );
	dlgedit_PushButton_17->setText( "&Cancel" );
	dlgedit_PushButton_17->setAutoRepeat( FALSE );
	dlgedit_PushButton_17->setAutoResize( FALSE );

	defaultCycle = new QCheckBox( this, "CheckBox_13" );
	defaultCycle->setGeometry( 140, 185, 215, 20 );
	defaultCycle->setMinimumSize( 10, 10 );
	defaultCycle->setMaximumSize( 32767, 32767 );
	defaultCycle->setText( "Default for new customers." );
	defaultCycle->setAutoRepeat( FALSE );
	defaultCycle->setAutoResize( FALSE );

	resize( 450,270 );
	setMinimumSize( 450, 235 );
	setMaximumSize( 450, 235 );
}


BillingCycleEditData::~BillingCycleEditData()
{
}
void BillingCycleEditData::saveCycle()
{
}
void BillingCycleEditData::cancelCycle()
{
}
