/**********************************************************************

	--- Qt Architect generated file ---

	File: BillingCyclesData.cpp
	Last generated: Mon Jan 18 19:53:19 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "BillingCyclesData.h"

#define Inherited QDialog

#include <qpushbt.h>

BillingCyclesData::BillingCyclesData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, FALSE, 0 )
{
	QPushButton* qtarch_PushButton_10;
	qtarch_PushButton_10 = new QPushButton( this, "PushButton_10" );
	qtarch_PushButton_10->setGeometry( 0, 30, 68, 30 );
	qtarch_PushButton_10->setMinimumSize( 68, 30 );
	qtarch_PushButton_10->setMaximumSize( 68, 30 );
	connect( qtarch_PushButton_10, SIGNAL(clicked()), SLOT(newCycle()) );
	qtarch_PushButton_10->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_10->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_10->setText( "&New" );
	qtarch_PushButton_10->setAutoRepeat( FALSE );
	qtarch_PushButton_10->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_11;
	qtarch_PushButton_11 = new QPushButton( this, "PushButton_11" );
	qtarch_PushButton_11->setGeometry( 68, 30, 68, 30 );
	qtarch_PushButton_11->setMinimumSize( 68, 30 );
	qtarch_PushButton_11->setMaximumSize( 68, 30 );
	connect( qtarch_PushButton_11, SIGNAL(clicked()), SLOT(editCycle()) );
	qtarch_PushButton_11->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_11->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_11->setText( "&Edit" );
	qtarch_PushButton_11->setAutoRepeat( FALSE );
	qtarch_PushButton_11->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_12;
	qtarch_PushButton_12 = new QPushButton( this, "PushButton_12" );
	qtarch_PushButton_12->setGeometry( 136, 30, 68, 30 );
	qtarch_PushButton_12->setMinimumSize( 68, 30 );
	qtarch_PushButton_12->setMaximumSize( 68, 30 );
	connect( qtarch_PushButton_12, SIGNAL(clicked()), SLOT(deleteCycle()) );
	qtarch_PushButton_12->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_12->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_12->setText( "&Delete" );
	qtarch_PushButton_12->setAutoRepeat( FALSE );
	qtarch_PushButton_12->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_13;
	qtarch_PushButton_13 = new QPushButton( this, "PushButton_13" );
	qtarch_PushButton_13->setGeometry( 204, 30, 68, 30 );
	qtarch_PushButton_13->setMinimumSize( 68, 30 );
	qtarch_PushButton_13->setMaximumSize( 68, 30 );
	connect( qtarch_PushButton_13, SIGNAL(clicked()), SLOT(Hide()) );
	qtarch_PushButton_13->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_13->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_13->setText( "&Close" );
	qtarch_PushButton_13->setAutoRepeat( FALSE );
	qtarch_PushButton_13->setAutoResize( FALSE );

	list = new QListView( this, "ListView_1" );
	list->setGeometry( 0, 60, 282, 131 );
	list->setMinimumSize( 0, 0 );
	list->setMaximumSize( 32767, 32767 );
	connect( list, SIGNAL(doubleClicked(QListViewItem*)), SLOT(editCycleLV(QListViewItem*)) );
	list->setFocusPolicy( QWidget::TabFocus );
	list->setBackgroundMode( QWidget::PaletteBackground );
	list->setResizePolicy( QScrollView::Manual );
	list->setVScrollBarMode( QScrollView::Auto );
	list->setHScrollBarMode( QScrollView::Auto );
	list->setTreeStepSize( 20 );
	list->setMultiSelection( FALSE );
	list->setAllColumnsShowFocus( TRUE );
	list->setItemMargin( 1 );
	list->setRootIsDecorated( FALSE );
	list->addColumn( "Cycle ID", -1 );
	list->setColumnWidthMode( 0, QListView::Maximum );
	list->setColumnAlignment( 0, 1 );
	list->addColumn( "Description", -1 );
	list->setColumnWidthMode( 1, QListView::Maximum );
	list->setColumnAlignment( 1, 1 );

	menu = new QMenuBar( this, "MenuBar_5" );
	menu->setGeometry( 0, 0, 282, 30 );
	menu->setMinimumSize( 0, 30 );
	menu->setMaximumSize( 32767, 30 );
	menu->setFocusPolicy( QWidget::NoFocus );
	menu->setBackgroundMode( QWidget::PaletteBackground );
	menu->setFrameStyle( 34 );
	menu->setLineWidth( 2 );

	QGridLayout* qtarch_layout_1 = new QGridLayout( this, 3, 1, 0, 0, NULL );
	qtarch_layout_1->addColSpacing( 0, 1 );
	qtarch_layout_1->setColStretch( 0, 1 );
	qtarch_layout_1->addRowSpacing( 0, 0 );
	qtarch_layout_1->setRowStretch( 0, 0 );
	qtarch_layout_1->addWidget( menu, 0, 0, 9 );
	qtarch_layout_1->addRowSpacing( 1, 0 );
	qtarch_layout_1->setRowStretch( 1, 0 );
	QBoxLayout* qtarch_layout_1_2_1 = new QBoxLayout( QBoxLayout::LeftToRight, 0, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2_1, 1, 0 );
	qtarch_layout_1_2_1->addStrut( 0 );
	qtarch_layout_1_2_1->addWidget( qtarch_PushButton_10, 0, 9 );
	qtarch_layout_1_2_1->addWidget( qtarch_PushButton_11, 0, 9 );
	qtarch_layout_1_2_1->addWidget( qtarch_PushButton_12, 0, 9 );
	qtarch_layout_1_2_1->addWidget( qtarch_PushButton_13, 0, 9 );
	qtarch_layout_1_2_1->addStretch( 1 );
	qtarch_layout_1->addRowSpacing( 2, 0 );
	qtarch_layout_1->setRowStretch( 2, 1 );
	qtarch_layout_1->addWidget( list, 2, 0, 9 );
	resize( 282,191 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


BillingCyclesData::~BillingCyclesData()
{
}
void BillingCyclesData::newCycle()
{
}
void BillingCyclesData::editCycle()
{
}
void BillingCyclesData::deleteCycle()
{
}
void BillingCyclesData::Hide()
{
}
void BillingCyclesData::editCycleLV(QListViewItem*)
{
}
