/**********************************************************************

	--- Qt Architect generated file ---

	File: BillingCycleEditData.h
	Last generated: Mon May 11 11:46:43 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef BillingCycleEditData_included
#define BillingCycleEditData_included

#include <qdialog.h>
#include <qchkbox.h>
#include <qlined.h>

class BillingCycleEditData : public QDialog
{
    Q_OBJECT

public:

    BillingCycleEditData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~BillingCycleEditData();

public slots:


protected slots:

    virtual void cancelCycle();
    virtual void saveCycle();

protected:
    QLineEdit* cycleID;
    QLineEdit* description;
    QLineEdit* day;
    QCheckBox* january;
    QCheckBox* february;
    QCheckBox* march;
    QCheckBox* april;
    QCheckBox* may;
    QCheckBox* june;
    QCheckBox* july;
    QCheckBox* august;
    QCheckBox* september;
    QCheckBox* october;
    QCheckBox* november;
    QCheckBox* december;
    QCheckBox* defaultCycle;

};

#endif // BillingCycleEditData_included
