/**********************************************************************

	--- Qt Architect generated file ---

	File: DomainTypeBillablesAddData.h
	Last generated: Mon May 25 13:09:21 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef DomainTypeBillablesAddData_included
#define DomainTypeBillablesAddData_included

#include <qdialog.h>
#include <qpushbt.h>
#include <qlistbox.h>

class DomainTypeBillablesAddData : public QDialog
{
    Q_OBJECT

public:

    DomainTypeBillablesAddData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~DomainTypeBillablesAddData();

public slots:


protected slots:

    virtual void addBillableItem();
    virtual void cancelBillableItem();

protected:
    QListBox* itemList;
    QPushButton* addButton;
    QPushButton* cancelButton;

};

#endif // DomainTypeBillablesAddData_included
