/**********************************************************************

	--- Qt Architect generated file ---

	File: GenJournalEntryData.h
	Last generated: Thu Dec 25 23:52:23 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef GenJournalEntryData_included
#define GenJournalEntryData_included

#include <qwidget.h>
#include <qlined.h>

class GenJournalEntryData : public QWidget
{
    Q_OBJECT

public:

    GenJournalEntryData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~GenJournalEntryData();

public slots:


protected slots:

    virtual void saveEntry();
    virtual void cancelEntry();

protected:
    QLineEdit* entryDate;
    QLineEdit* entryNo;
    QLineEdit* description;

};

#endif // GenJournalEntryData_included
