/**********************************************************************

	--- Qt Architect generated file ---

	File: GenJournalEntryData.cpp
	Last generated: Thu Dec 25 23:52:23 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "GenJournalEntryData.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qpushbt.h>

GenJournalEntryData::GenJournalEntryData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QLabel* dlgedit_Label_1;
	dlgedit_Label_1 = new QLabel( this, "Label_1" );
	dlgedit_Label_1->setGeometry( 10, 20, 100, 20 );
	dlgedit_Label_1->setMinimumSize( 10, 10 );
	dlgedit_Label_1->setMaximumSize( 32767, 32767 );
	dlgedit_Label_1->setText( "Date:" );
	dlgedit_Label_1->setAlignment( 290 );
	dlgedit_Label_1->setMargin( -1 );

	QLabel* dlgedit_Label_2;
	dlgedit_Label_2 = new QLabel( this, "Label_2" );
	dlgedit_Label_2->setGeometry( 280, 20, 100, 20 );
	dlgedit_Label_2->setMinimumSize( 10, 10 );
	dlgedit_Label_2->setMaximumSize( 32767, 32767 );
	dlgedit_Label_2->setText( "Entry No:" );
	dlgedit_Label_2->setAlignment( 290 );
	dlgedit_Label_2->setMargin( -1 );

	QLabel* dlgedit_Label_3;
	dlgedit_Label_3 = new QLabel( this, "Label_3" );
	dlgedit_Label_3->setGeometry( 10, 45, 100, 20 );
	dlgedit_Label_3->setMinimumSize( 10, 10 );
	dlgedit_Label_3->setMaximumSize( 32767, 32767 );
	dlgedit_Label_3->setText( "Description:" );
	dlgedit_Label_3->setAlignment( 290 );
	dlgedit_Label_3->setMargin( -1 );

	QLabel* dlgedit_Label_4;
	dlgedit_Label_4 = new QLabel( this, "Label_4" );
	dlgedit_Label_4->setGeometry( 10, 75, 130, 20 );
	dlgedit_Label_4->setMinimumSize( 10, 10 );
	dlgedit_Label_4->setMaximumSize( 32767, 32767 );
	{
        /*
		QColorGroup normal( QColor( QRgb(0) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QColorGroup disabled( QColor( QRgb(8421504) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(8421504) ), QColor( QRgb(12632256) ) );
		QColorGroup active( QColor( QRgb(0) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QPalette palette( normal, disabled, active );
		dlgedit_Label_4->setPalette( palette );
        */
	}
	dlgedit_Label_4->setFrameStyle( 34 );
	dlgedit_Label_4->setText( "Account" );
	dlgedit_Label_4->setAlignment( 292 );
	dlgedit_Label_4->setMargin( -1 );

	QLabel* dlgedit_Label_5;
	dlgedit_Label_5 = new QLabel( this, "Label_5" );
	dlgedit_Label_5->setGeometry( 140, 75, 100, 20 );
	dlgedit_Label_5->setMinimumSize( 10, 10 );
	dlgedit_Label_5->setMaximumSize( 32767, 32767 );
	{
        /*
		QColorGroup normal( QColor( QRgb(0) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QColorGroup disabled( QColor( QRgb(8421504) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(8421504) ), QColor( QRgb(12632256) ) );
		QColorGroup active( QColor( QRgb(0) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QPalette palette( normal, disabled, active );
		dlgedit_Label_5->setPalette( palette );
        */
	}
	dlgedit_Label_5->setFrameStyle( 34 );
	dlgedit_Label_5->setText( "Credit" );
	dlgedit_Label_5->setAlignment( 292 );
	dlgedit_Label_5->setMargin( -1 );

	QLabel* dlgedit_Label_6;
	dlgedit_Label_6 = new QLabel( this, "Label_6" );
	dlgedit_Label_6->setGeometry( 240, 75, 100, 20 );
	dlgedit_Label_6->setMinimumSize( 10, 10 );
	dlgedit_Label_6->setMaximumSize( 32767, 32767 );
	{
        /*
		QColorGroup normal( QColor( QRgb(0) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QColorGroup disabled( QColor( QRgb(8421504) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(8421504) ), QColor( QRgb(12632256) ) );
		QColorGroup active( QColor( QRgb(0) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QPalette palette( normal, disabled, active );
		dlgedit_Label_6->setPalette( palette );
        */
	}
	dlgedit_Label_6->setFrameStyle( 34 );
	dlgedit_Label_6->setText( "Debit" );
	dlgedit_Label_6->setAlignment( 292 );
	dlgedit_Label_6->setMargin( -1 );

	QLabel* dlgedit_Label_7;
	dlgedit_Label_7 = new QLabel( this, "Label_7" );
	dlgedit_Label_7->setGeometry( 340, 75, 255, 20 );
	dlgedit_Label_7->setMinimumSize( 10, 10 );
	dlgedit_Label_7->setMaximumSize( 32767, 32767 );
	{
        /*
		QColorGroup normal( QColor( QRgb(0) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QColorGroup disabled( QColor( QRgb(8421504) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(8421504) ), QColor( QRgb(12632256) ) );
		QColorGroup active( QColor( QRgb(0) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QPalette palette( normal, disabled, active );
		dlgedit_Label_7->setPalette( palette );
        */
	}
	dlgedit_Label_7->setFrameStyle( 34 );
	dlgedit_Label_7->setText( "Memo" );
	dlgedit_Label_7->setAlignment( 292 );
	dlgedit_Label_7->setMargin( -1 );

	entryDate = new QLineEdit( this, "LineEdit_4" );
	entryDate->setGeometry( 115, 20, 100, 20 );
	entryDate->setMinimumSize( 10, 10 );
	entryDate->setMaximumSize( 32767, 32767 );
	entryDate->setText( "" );
	entryDate->setMaxLength( 10 );
	entryDate->setEchoMode( QLineEdit::Normal );
	entryDate->setFrame( TRUE );

	entryNo = new QLineEdit( this, "LineEdit_5" );
	entryNo->setGeometry( 385, 20, 100, 20 );
	entryNo->setMinimumSize( 10, 10 );
	entryNo->setMaximumSize( 32767, 32767 );
	entryNo->setText( "" );
	entryNo->setMaxLength( 20 );
	entryNo->setEchoMode( QLineEdit::Normal );
	entryNo->setFrame( TRUE );

	description = new QLineEdit( this, "LineEdit_6" );
	description->setGeometry( 115, 45, 370, 20 );
	description->setMinimumSize( 10, 10 );
	description->setMaximumSize( 32767, 32767 );
	description->setText( "" );
	description->setMaxLength( 200 );
	description->setEchoMode( QLineEdit::Normal );
	description->setFrame( TRUE );

	QPushButton* dlgedit_PushButton_1;
	dlgedit_PushButton_1 = new QPushButton( this, "PushButton_1" );
	dlgedit_PushButton_1->setGeometry( 350, 275, 100, 30 );
	dlgedit_PushButton_1->setMinimumSize( 10, 10 );
	dlgedit_PushButton_1->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_1, SIGNAL(clicked()), SLOT(saveEntry()) );
	dlgedit_PushButton_1->setText( "&Save" );
	dlgedit_PushButton_1->setAutoRepeat( FALSE );
	dlgedit_PushButton_1->setAutoResize( FALSE );

	QPushButton* dlgedit_PushButton_2;
	dlgedit_PushButton_2 = new QPushButton( this, "PushButton_2" );
	dlgedit_PushButton_2->setGeometry( 475, 275, 100, 30 );
	dlgedit_PushButton_2->setMinimumSize( 10, 10 );
	dlgedit_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_2, SIGNAL(clicked()), SLOT(cancelEntry()) );
	dlgedit_PushButton_2->setText( "&Cancel" );
	dlgedit_PushButton_2->setAutoRepeat( FALSE );
	dlgedit_PushButton_2->setAutoResize( FALSE );

	resize( 605,325 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


GenJournalEntryData::~GenJournalEntryData()
{
}
void GenJournalEntryData::saveEntry()
{
}
void GenJournalEntryData::cancelEntry()
{
}
