/**********************************************************************

	--- Qt Architect generated file ---

	File: OverdueAccountsData.cpp
	Last generated: Mon Apr 24 16:26:20 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "OverdueAccountsData.h"

#include <qlabel.h>
#include <qpushbutton.h>
#include <qbuttongroup.h>

OverdueAccountsData::OverdueAccountsData(QWidget *parent, const char *name)
                    : TAAWidget(parent, name)
{
    QButtonGroup *qtarch_SummaryGroup = new QButtonGroup(this, "SummaryGroup");
    qtarch_SummaryGroup->setGeometry(5, 220, 228, 125);
    qtarch_SummaryGroup->setMinimumSize(10, 125);
    qtarch_SummaryGroup->setMaximumSize(32767, 125);
    qtarch_SummaryGroup->setFocusPolicy(QWidget::NoFocus);
    qtarch_SummaryGroup->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_SummaryGroup->setFrameStyle( 49 );
    qtarch_SummaryGroup->setLineWidth( 1 );
    qtarch_SummaryGroup->setMidLineWidth( 0 );
    qtarch_SummaryGroup->QFrame::setMargin( 0 );
    qtarch_SummaryGroup->setTitle( "Summary Information" );
    qtarch_SummaryGroup->setAlignment( AlignLeft );
    qtarch_SummaryGroup->setExclusive( FALSE );

    QLabel *qtarch_AccountsOverdueLabel = new QLabel(qtarch_SummaryGroup, "AccountsOverdueLabel");
    qtarch_AccountsOverdueLabel->setGeometry(5, 20, 127, 23);
    qtarch_AccountsOverdueLabel->setMinimumSize(0, 23);
    qtarch_AccountsOverdueLabel->setMaximumSize(32767, 23);
    qtarch_AccountsOverdueLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_AccountsOverdueLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_AccountsOverdueLabel->setFrameStyle( 0 );
    qtarch_AccountsOverdueLabel->setLineWidth( 1 );
    qtarch_AccountsOverdueLabel->setMidLineWidth( 0 );
    qtarch_AccountsOverdueLabel->QFrame::setMargin( -1 );
    qtarch_AccountsOverdueLabel->setText( "Accounts Overdue:" );
    qtarch_AccountsOverdueLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_AccountsOverdueLabel->setMargin( -1 );

    accountsOverdue = new QLabel(qtarch_SummaryGroup, "AccountsOverdue");
    accountsOverdue->setGeometry(134, 20, 89, 23);
    accountsOverdue->setMinimumSize(0, 23);
    accountsOverdue->setMaximumSize(32767, 23);
    accountsOverdue->setFocusPolicy(QWidget::NoFocus);
    accountsOverdue->setBackgroundMode(QWidget::PaletteBackground);
    accountsOverdue->setFrameStyle( 50 );
    accountsOverdue->setLineWidth( 1 );
    accountsOverdue->setMidLineWidth( 0 );
    accountsOverdue->QFrame::setMargin( -1 );
    accountsOverdue->setText( "" );
    accountsOverdue->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    accountsOverdue->setMargin( -1 );

    QLabel *qtarch_AccountsSelectedLabel = new QLabel(qtarch_SummaryGroup, "AccountsSelectedLabel");
    qtarch_AccountsSelectedLabel->setGeometry(5, 45, 127, 23);
    qtarch_AccountsSelectedLabel->setMinimumSize(0, 23);
    qtarch_AccountsSelectedLabel->setMaximumSize(32767, 23);
    qtarch_AccountsSelectedLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_AccountsSelectedLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_AccountsSelectedLabel->setFrameStyle( 0 );
    qtarch_AccountsSelectedLabel->setLineWidth( 1 );
    qtarch_AccountsSelectedLabel->setMidLineWidth( 0 );
    qtarch_AccountsSelectedLabel->QFrame::setMargin( -1 );
    qtarch_AccountsSelectedLabel->setText( "Account Selected:" );
    qtarch_AccountsSelectedLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_AccountsSelectedLabel->setMargin( -1 );

    accountsSelected = new QLabel(qtarch_SummaryGroup, "AccountsSelected");
    accountsSelected->setGeometry(134, 45, 89, 23);
    accountsSelected->setMinimumSize(0, 23);
    accountsSelected->setMaximumSize(32767, 23);
    accountsSelected->setFocusPolicy(QWidget::NoFocus);
    accountsSelected->setBackgroundMode(QWidget::PaletteBackground);
    accountsSelected->setFrameStyle( 50 );
    accountsSelected->setLineWidth( 1 );
    accountsSelected->setMidLineWidth( 0 );
    accountsSelected->QFrame::setMargin( -1 );
    accountsSelected->setText( "" );
    accountsSelected->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    accountsSelected->setMargin( -1 );

    QLabel *qtarch_TotalFromSelectedLabel = new QLabel(qtarch_SummaryGroup, "TotalFromSelectedLabel");
    qtarch_TotalFromSelectedLabel->setGeometry(5, 70, 127, 23);
    qtarch_TotalFromSelectedLabel->setMinimumSize(0, 23);
    qtarch_TotalFromSelectedLabel->setMaximumSize(32767, 23);
    qtarch_TotalFromSelectedLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_TotalFromSelectedLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_TotalFromSelectedLabel->setFrameStyle( 0 );
    qtarch_TotalFromSelectedLabel->setLineWidth( 1 );
    qtarch_TotalFromSelectedLabel->setMidLineWidth( 0 );
    qtarch_TotalFromSelectedLabel->QFrame::setMargin( -1 );
    qtarch_TotalFromSelectedLabel->setText( "Total from Selected:" );
    qtarch_TotalFromSelectedLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_TotalFromSelectedLabel->setMargin( -1 );

    selectedOverdue = new QLabel(qtarch_SummaryGroup, "TotalFromSelected");
    selectedOverdue->setGeometry(134, 70, 89, 23);
    selectedOverdue->setMinimumSize(0, 23);
    selectedOverdue->setMaximumSize(32767, 23);
    selectedOverdue->setFocusPolicy(QWidget::NoFocus);
    selectedOverdue->setBackgroundMode(QWidget::PaletteBackground);
    selectedOverdue->setFrameStyle( 50 );
    selectedOverdue->setLineWidth( 2 );
    selectedOverdue->setMidLineWidth( 0 );
    selectedOverdue->QFrame::setMargin( -1 );
    selectedOverdue->setText( "" );
    selectedOverdue->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    selectedOverdue->setMargin( -1 );

    QLabel *qtarch_AmountOverdueLabel = new QLabel(qtarch_SummaryGroup, "AmountOverdueLabel");
    qtarch_AmountOverdueLabel->setGeometry(5, 95, 127, 23);
    qtarch_AmountOverdueLabel->setMinimumSize(0, 23);
    qtarch_AmountOverdueLabel->setMaximumSize(32767, 23);
    qtarch_AmountOverdueLabel->setFocusPolicy(QWidget::NoFocus);
    qtarch_AmountOverdueLabel->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_AmountOverdueLabel->setFrameStyle( 0 );
    qtarch_AmountOverdueLabel->setLineWidth( 1 );
    qtarch_AmountOverdueLabel->setMidLineWidth( 0 );
    qtarch_AmountOverdueLabel->QFrame::setMargin( -1 );
    qtarch_AmountOverdueLabel->setText( "Total Amount Overdue:" );
    qtarch_AmountOverdueLabel->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    qtarch_AmountOverdueLabel->setMargin( -1 );

    amountOverdue = new QLabel(qtarch_SummaryGroup, "AmountOverdue");
    amountOverdue->setGeometry(134, 95, 89, 23);
    amountOverdue->setMinimumSize(0, 23);
    amountOverdue->setMaximumSize(32767, 23);
    amountOverdue->setFocusPolicy(QWidget::NoFocus);
    amountOverdue->setBackgroundMode(QWidget::PaletteBackground);
    amountOverdue->setFrameStyle( 50 );
    amountOverdue->setLineWidth( 2 );
    amountOverdue->setMidLineWidth( 0 );
    amountOverdue->QFrame::setMargin( -1 );
    amountOverdue->setText( "" );
    amountOverdue->setAlignment( AlignRight|AlignVCenter|ExpandTabs );
    amountOverdue->setMargin( -1 );

    QButtonGroup *qtarch_ActionGroup = new QButtonGroup(this, "ActionGroup");
    qtarch_ActionGroup->setGeometry(238, 220, 227, 125);
    qtarch_ActionGroup->setMinimumSize(10, 10);
    qtarch_ActionGroup->setMaximumSize(32767, 32767);
    qtarch_ActionGroup->setFocusPolicy(QWidget::NoFocus);
    qtarch_ActionGroup->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_ActionGroup->setFrameStyle( 49 );
    qtarch_ActionGroup->setLineWidth( 1 );
    qtarch_ActionGroup->setMidLineWidth( 0 );
    qtarch_ActionGroup->QFrame::setMargin( 0 );
    qtarch_ActionGroup->setTitle( "Action" );
    qtarch_ActionGroup->setAlignment( AlignLeft );
    qtarch_ActionGroup->setExclusive( FALSE );

    noAction = new QRadioButton(qtarch_ActionGroup, "noActionButton");
    noAction->setGeometry(5, 20, 217, 19);
    noAction->setMinimumSize(10, 10);
    noAction->setMaximumSize(32767, 32767);
    noAction->setFocusPolicy(QWidget::TabFocus);
    noAction->setBackgroundMode(QWidget::PaletteBackground);
    noAction->setText( "Non&e" );
    noAction->setAutoRepeat( FALSE );
    noAction->setAutoResize( FALSE );
    noAction->setChecked( TRUE );

    actionOne = new QRadioButton(qtarch_ActionGroup, "reminderButton");
    actionOne->setGeometry(5, 41, 217, 19);
    actionOne->setMinimumSize(10, 10);
    actionOne->setMaximumSize(32767, 32767);
    actionOne->setFocusPolicy(QWidget::TabFocus);
    actionOne->setBackgroundMode(QWidget::PaletteBackground);
    actionOne->setText( "&Send Reminder" );
    actionOne->setAutoRepeat( FALSE );
    actionOne->setAutoResize( FALSE );
    actionOne->setChecked( FALSE );

    actionTwo = new QRadioButton(qtarch_ActionGroup, "suspendButton");
    actionTwo->setGeometry(5, 62, 217, 19);
    actionTwo->setMinimumSize(10, 10);
    actionTwo->setMaximumSize(32767, 32767);
    actionTwo->setFocusPolicy(QWidget::TabFocus);
    actionTwo->setBackgroundMode(QWidget::PaletteBackground);
    actionTwo->setText( "S&uspend Account" );
    actionTwo->setAutoRepeat( FALSE );
    actionTwo->setAutoResize( FALSE );
    actionTwo->setChecked( FALSE );

    QPushButton *qtarch_continueButton = new QPushButton(this, "continueButton");
    qtarch_continueButton->setGeometry(470, 297, 85, 23);
    qtarch_continueButton->setMinimumSize(85, 23);
    qtarch_continueButton->setMaximumSize(85, 23);
    qtarch_continueButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_continueButton->setBackgroundMode(QWidget::PaletteButton);
    qtarch_continueButton->setText( "C&ontinue" );
    qtarch_continueButton->setAutoRepeat( FALSE );
    qtarch_continueButton->setAutoResize( FALSE );
    qtarch_continueButton->setToggleButton( FALSE );
    qtarch_continueButton->setDefault( FALSE );
    qtarch_continueButton->setAutoDefault( FALSE );
    qtarch_continueButton->setIsMenuButton( FALSE );
    connect(qtarch_continueButton, SIGNAL(clicked()), SLOT(processSelections()));

    QPushButton *qtarch_cancelButton = new QPushButton(this, "cancelButton");
    qtarch_cancelButton->setGeometry(470, 322, 85, 23);
    qtarch_cancelButton->setMinimumSize(85, 23);
    qtarch_cancelButton->setMaximumSize(85, 23);
    qtarch_cancelButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_cancelButton->setBackgroundMode(QWidget::PaletteButton);
    qtarch_cancelButton->setText( "&Cancel" );
    qtarch_cancelButton->setAutoRepeat( FALSE );
    qtarch_cancelButton->setAutoResize( FALSE );
    qtarch_cancelButton->setToggleButton( FALSE );
    qtarch_cancelButton->setDefault( FALSE );
    qtarch_cancelButton->setAutoDefault( FALSE );
    qtarch_cancelButton->setIsMenuButton( FALSE );
    connect(qtarch_cancelButton, SIGNAL(clicked()), SLOT(cancelOverdue()));

    QPushButton *qtarch_selectAllButton = new QPushButton(this, "selectAllButton");
    qtarch_selectAllButton->setGeometry(470, 270, 85, 25);
    qtarch_selectAllButton->setMinimumSize(85, 25);
    qtarch_selectAllButton->setMaximumSize(85, 25);
    qtarch_selectAllButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_selectAllButton->setBackgroundMode(QWidget::PaletteButton);
    qtarch_selectAllButton->setText( "Select &All" );
    qtarch_selectAllButton->setAutoRepeat( FALSE );
    qtarch_selectAllButton->setAutoResize( FALSE );
    qtarch_selectAllButton->setToggleButton( FALSE );
    qtarch_selectAllButton->setDefault( FALSE );
    qtarch_selectAllButton->setAutoDefault( FALSE );
    qtarch_selectAllButton->setIsMenuButton( FALSE );
    connect(qtarch_selectAllButton, SIGNAL(clicked()), SLOT(selectAll()));

    QPushButton *qtarch_selectNoneButton = new QPushButton(this, "selectNoneButton");
    qtarch_selectNoneButton->setGeometry(470, 245, 85, 23);
    qtarch_selectNoneButton->setMinimumSize(85, 23);
    qtarch_selectNoneButton->setMaximumSize(85, 23);
    qtarch_selectNoneButton->setFocusPolicy(QWidget::TabFocus);
    qtarch_selectNoneButton->setBackgroundMode(QWidget::PaletteButton);
    qtarch_selectNoneButton->setText( "Select &None" );
    qtarch_selectNoneButton->setAutoRepeat( FALSE );
    qtarch_selectNoneButton->setAutoResize( FALSE );
    qtarch_selectNoneButton->setToggleButton( FALSE );
    qtarch_selectNoneButton->setDefault( FALSE );
    qtarch_selectNoneButton->setAutoDefault( FALSE );
    qtarch_selectNoneButton->setIsMenuButton( FALSE );
    connect(qtarch_selectNoneButton, SIGNAL(clicked()), SLOT(selectNone()));

    progress = new QProgressBar(100, this, "ProgressBar");
    progress->setGeometry(470, 351, 85, 22);
    progress->setMinimumSize(85, 22);
    progress->setMaximumSize(85, 22);
    progress->setFocusPolicy(QWidget::NoFocus);
    progress->setBackgroundMode(QWidget::PaletteBackground);
    progress->setFrameStyle( 51 );
    progress->setLineWidth( 2 );
    progress->setMidLineWidth( 0 );
    progress->QFrame::setMargin( 0 );
    progress->setProgress( -1 );

    list = new QListView(this, "AccountList");
    list->setGeometry(5, 5, 550, 210);
    list->setMinimumSize(0, 0);
    list->setMaximumSize(32767, 32767);
    list->setFocusPolicy(QWidget::TabFocus);
    list->setBackgroundMode(QWidget::PaletteBackground);
    list->setFrameStyle( 17 );
    list->setLineWidth( 2 );
    list->setMidLineWidth( 0 );
    list->QFrame::setMargin( 0 );
    list->setResizePolicy( QScrollView::Manual );
    list->setVScrollBarMode( QScrollView::Auto );
    list->setHScrollBarMode( QScrollView::Auto );
    list->setTreeStepSize( 20 );
    list->setMultiSelection( FALSE );
    list->setAllColumnsShowFocus( FALSE );
    list->setItemMargin( 1 );
    list->setRootIsDecorated( FALSE );
    list->addColumn( "Cust ID", -1 );
    list->setColumnWidthMode( 0, QListView::Maximum );
    list->setColumnAlignment( 0, 1 );
    list->addColumn( "Customer Name", -1 );
    list->setColumnWidthMode( 1, QListView::Maximum );
    list->setColumnAlignment( 1, 1 );
    list->addColumn( "Primary Login", -1 );
    list->setColumnWidthMode( 2, QListView::Maximum );
    list->setColumnAlignment( 2, 1 );
    list->addColumn( "Balance", -1 );
    list->setColumnWidthMode( 3, QListView::Maximum );
    list->setColumnAlignment( 3, 2 );
    list->addColumn( "Overdue", -1 );
    list->setColumnWidthMode( 4, QListView::Maximum );
    list->setColumnAlignment( 4, 2 );
    list->addColumn( "Oldest", -1 );
    list->setColumnWidthMode( 5, QListView::Maximum );
    list->setColumnAlignment( 5, 2 );
    list->addColumn( "Grace", -1 );
    list->setColumnWidthMode( 6, QListView::Maximum );
    list->setColumnAlignment( 6, 2 );

    statusBar = new QLabel(this, "StatusLabel");
    statusBar->setGeometry(5, 350, 463, 25);
    statusBar->setMinimumSize(0, 0);
    statusBar->setMaximumSize(32767, 32767);
    statusBar->setFocusPolicy(QWidget::NoFocus);
    statusBar->setBackgroundMode(QWidget::PaletteBackground);
    statusBar->setFrameStyle( 51 );
    statusBar->setLineWidth( 2 );
    statusBar->setMidLineWidth( 0 );
    statusBar->QFrame::setMargin( 0 );
    statusBar->setText( "" );
    statusBar->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    statusBar->setMargin( 0 );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( list, 1, 0 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 0 );
	qtarch_layout_1_2->addStrut( 0 );
	qtarch_layout_1_2->addWidget( qtarch_SummaryGroup, 1, 0 );
	QBoxLayout* qtarch_layout_1_2_1 = new QBoxLayout( qtarch_SummaryGroup, QBoxLayout::TopToBottom, 5, 0, NULL );
	qtarch_layout_1_2_1->addStrut( 0 );
	qtarch_layout_1_2_1->addSpacing( 15 );
	QGridLayout* qtarch_layout_1_2_1_2 = new QGridLayout( 4, 2, 2, NULL );
	qtarch_layout_1_2_1->addLayout( qtarch_layout_1_2_1_2, 0 );
	qtarch_layout_1_2_1_2->addColSpacing( 0, 5 );
	qtarch_layout_1_2_1_2->setColStretch( 0, 0 );
	qtarch_layout_1_2_1_2->addColSpacing( 1, 5 );
	qtarch_layout_1_2_1_2->setColStretch( 1, 1 );
	qtarch_layout_1_2_1_2->addRowSpacing( 0, 0 );
	qtarch_layout_1_2_1_2->setRowStretch( 0, 1 );
	qtarch_layout_1_2_1_2->addWidget( qtarch_AccountsOverdueLabel, 0, 0, 0 );
	qtarch_layout_1_2_1_2->addWidget( accountsOverdue, 0, 1, 0 );
	qtarch_layout_1_2_1_2->addRowSpacing( 1, 0 );
	qtarch_layout_1_2_1_2->setRowStretch( 1, 1 );
	qtarch_layout_1_2_1_2->addWidget( qtarch_AccountsSelectedLabel, 1, 0, 0 );
	qtarch_layout_1_2_1_2->addWidget( accountsSelected, 1, 1, 0 );
	qtarch_layout_1_2_1_2->addRowSpacing( 2, 0 );
	qtarch_layout_1_2_1_2->setRowStretch( 2, 1 );
	qtarch_layout_1_2_1_2->addWidget( qtarch_TotalFromSelectedLabel, 2, 0, 0 );
	qtarch_layout_1_2_1_2->addWidget( selectedOverdue, 2, 1, 0 );
	qtarch_layout_1_2_1_2->addRowSpacing( 3, 0 );
	qtarch_layout_1_2_1_2->setRowStretch( 3, 1 );
	qtarch_layout_1_2_1_2->addWidget( qtarch_AmountOverdueLabel, 3, 0, 0 );
	qtarch_layout_1_2_1_2->addWidget( amountOverdue, 3, 1, 0 );
	qtarch_layout_1_2_1->addStretch( 1 );
	qtarch_layout_1_2->addWidget( qtarch_ActionGroup, 1, 0 );
	QBoxLayout* qtarch_layout_1_2_2 = new QBoxLayout( qtarch_ActionGroup, QBoxLayout::TopToBottom, 5, 2, NULL );
	qtarch_layout_1_2_2->addStrut( 0 );
	qtarch_layout_1_2_2->addSpacing( 15 );
	qtarch_layout_1_2_2->addWidget( noAction, 1, 0 );
	qtarch_layout_1_2_2->addWidget( actionOne, 1, 0 );
	qtarch_layout_1_2_2->addWidget( actionTwo, 1, 0 );
	qtarch_layout_1_2_2->addStretch( 1 );
	QBoxLayout* qtarch_layout_1_2_3 = new QBoxLayout( QBoxLayout::TopToBottom, 2, NULL );
	qtarch_layout_1_2->addLayout( qtarch_layout_1_2_3, 1 );
	qtarch_layout_1_2_3->addStrut( 0 );
	qtarch_layout_1_2_3->addStretch( 1 );
	qtarch_layout_1_2_3->addWidget( qtarch_selectNoneButton, 0, 0 );
	qtarch_layout_1_2_3->addWidget( qtarch_selectAllButton, 0, 0 );
	qtarch_layout_1_2_3->addWidget( qtarch_continueButton, 0, 0 );
	qtarch_layout_1_2_3->addWidget( qtarch_cancelButton, 0, 0 );
	QBoxLayout* qtarch_layout_1_3 = new QBoxLayout( QBoxLayout::LeftToRight, 2, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_3, 0 );
	qtarch_layout_1_3->addStrut( 0 );
	qtarch_layout_1_3->addWidget( statusBar, 1, 0 );
	qtarch_layout_1_3->addWidget( progress, 0, 0 );
    resize(560,380);
    setMinimumSize(0, 0);
    setMaximumSize(32767, 32767);
}

OverdueAccountsData::~OverdueAccountsData()
{
}
