/**********************************************************************

	--- Dlgedit generated file ---

	File: PaymentTermsData.h
	Last generated: Thu Sep 18 11:53:11 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef PaymentTermsData_included
#define PaymentTermsData_included

#include <qwidget.h>
#include <qlistbox.h>
#include <qmenubar.h>

class PaymentTermsData : public QWidget
{
    Q_OBJECT

public:

    PaymentTermsData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~PaymentTermsData();

public slots:


protected slots:

    virtual void newPaymentTerms();
    virtual void Hide();
    virtual void editPaymentTerms();
    virtual void deletePaymentTerms();
    virtual void editPaymentTermsL(int);

protected:
    QListBox* list;
    QMenuBar* menu;

};

#endif // PaymentTermsData_included
