/**********************************************************************

	--- Dlgedit generated file ---

	File: PaymentTermsEditData.h
	Last generated: Tue Sep 30 21:58:57 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef PaymentTermsEditData_included
#define PaymentTermsEditData_included

#include <qwidget.h>
#include <qlined.h>

class PaymentTermsEditData : public QWidget
{
    Q_OBJECT

public:

    PaymentTermsEditData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~PaymentTermsEditData();

public slots:


protected slots:

    virtual void savePaymentTerms();
    virtual void cancelPaymentTerms();

protected:
    QLineEdit* desc;
    QLineEdit* dueDays;
    QLineEdit* graceDays;
    QLineEdit* financePct;
    QLineEdit* financeDays;
    QLineEdit* discountPct;
    QLineEdit* discountDays;

};

#endif // PaymentTermsEditData_included
