/**********************************************************************

	--- Dlgedit generated file ---

	File: PaymentTermsEditData.cpp
	Last generated: Tue Sep 30 21:58:57 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#include "PaymentTermsEditData.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qpushbt.h>

PaymentTermsEditData::PaymentTermsEditData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name )
{
	QLabel* tmpQLabel;
	tmpQLabel = new QLabel( this, "Label_5" );
	tmpQLabel->setGeometry( 30, 20, 130, 20 );
	tmpQLabel->setText( "Description:" );
	tmpQLabel->setAlignment( 290 );
	tmpQLabel->setMargin( -1 );

	tmpQLabel = new QLabel( this, "Label_6" );
	tmpQLabel->setGeometry( 20, 50, 140, 20 );
	tmpQLabel->setText( "Net due in" );
	tmpQLabel->setAlignment( 290 );
	tmpQLabel->setMargin( -1 );

	desc = new QLineEdit( this, "LineEdit_2" );
	desc->setGeometry( 170, 20, 350, 20 );
	desc->setText( "" );
	desc->setMaxLength( 60 );
	desc->setEchoMode( QLineEdit::Normal );
	desc->setFrame( TRUE );

	tmpQLabel = new QLabel( this, "Label_7" );
	tmpQLabel->setGeometry( 210, 50, 100, 20 );
	tmpQLabel->setText( "days." );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	dueDays = new QLineEdit( this, "LineEdit_3" );
	dueDays->setGeometry( 170, 50, 30, 20 );
	dueDays->setText( "" );
	dueDays->setMaxLength( 3 );
	dueDays->setEchoMode( QLineEdit::Normal );
	dueDays->setFrame( TRUE );

	tmpQLabel = new QLabel( this, "Label_8" );
	tmpQLabel->setGeometry( 60, 80, 100, 20 );
	tmpQLabel->setText( "Grace period of" );
	tmpQLabel->setAlignment( 290 );
	tmpQLabel->setMargin( -1 );

	graceDays = new QLineEdit( this, "LineEdit_4" );
	graceDays->setGeometry( 170, 80, 30, 20 );
	graceDays->setText( "" );
	graceDays->setMaxLength( 3 );
	graceDays->setEchoMode( QLineEdit::Normal );
	graceDays->setFrame( TRUE );

	tmpQLabel = new QLabel( this, "Label_9" );
	tmpQLabel->setGeometry( 210, 80, 100, 20 );
	tmpQLabel->setText( "days." );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	tmpQLabel = new QLabel( this, "Label_10" );
	tmpQLabel->setGeometry( 10, 110, 150, 20 );
	tmpQLabel->setText( "Charge fincance charge of" );
	tmpQLabel->setAlignment( 290 );
	tmpQLabel->setMargin( -1 );

	financePct = new QLineEdit( this, "LineEdit_5" );
	financePct->setGeometry( 170, 110, 40, 20 );
	financePct->setText( "" );
	financePct->setMaxLength( 5 );
	financePct->setEchoMode( QLineEdit::Normal );
	financePct->setFrame( TRUE );

	tmpQLabel = new QLabel( this, "Label_11" );
	tmpQLabel->setGeometry( 220, 110, 110, 20 );
	tmpQLabel->setText( "percent, starting" );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	financeDays = new QLineEdit( this, "LineEdit_6" );
	financeDays->setGeometry( 370, 110, 30, 20 );
	financeDays->setText( "" );
	financeDays->setMaxLength( 3 );
	financeDays->setEchoMode( QLineEdit::Normal );
	financeDays->setFrame( TRUE );

	tmpQLabel = new QLabel( this, "Label_12" );
	tmpQLabel->setGeometry( 410, 110, 150, 20 );
	tmpQLabel->setText( "days after grace period." );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	tmpQLabel = new QLabel( this, "Label_13" );
	tmpQLabel->setGeometry( 20, 140, 140, 20 );
	tmpQLabel->setText( "Auto apply discount of" );
	tmpQLabel->setAlignment( 290 );
	tmpQLabel->setMargin( -1 );

	discountPct = new QLineEdit( this, "LineEdit_7" );
	discountPct->setGeometry( 170, 140, 40, 20 );
	discountPct->setText( "" );
	discountPct->setMaxLength( 5 );
	discountPct->setEchoMode( QLineEdit::Normal );
	discountPct->setFrame( TRUE );

	tmpQLabel = new QLabel( this, "Label_14" );
	tmpQLabel->setGeometry( 220, 140, 150, 20 );
	tmpQLabel->setText( "percent if paid within" );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	discountDays = new QLineEdit( this, "LineEdit_8" );
	discountDays->setGeometry( 370, 140, 30, 20 );
	discountDays->setText( "" );
	discountDays->setMaxLength( 3 );
	discountDays->setEchoMode( QLineEdit::Normal );
	discountDays->setFrame( TRUE );

	tmpQLabel = new QLabel( this, "Label_15" );
	tmpQLabel->setGeometry( 410, 140, 140, 20 );
	tmpQLabel->setText( "days before due date." );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	QPushButton* tmpQPushButton;
	tmpQPushButton = new QPushButton( this, "PushButton_13" );
	tmpQPushButton->setGeometry( 160, 180, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(savePaymentTerms()) );
	tmpQPushButton->setText( "Save" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );
	tmpQPushButton->setAutoDefault( TRUE );

	tmpQPushButton = new QPushButton( this, "PushButton_14" );
	tmpQPushButton->setGeometry( 330, 180, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(cancelPaymentTerms()) );
	tmpQPushButton->setText( "Cancel" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	resize( 590, 220 );
}


PaymentTermsEditData::~PaymentTermsEditData()
{
}
void PaymentTermsEditData::savePaymentTerms()
{
}
void PaymentTermsEditData::cancelPaymentTerms()
{
}
