/**********************************************************************

	--- Dlgedit generated file ---

	File: PaymentTermsData.cpp
	Last generated: Thu Sep 18 11:53:11 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#include "PaymentTermsData.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qpushbt.h>

PaymentTermsData::PaymentTermsData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name )
{
	list = new QListBox( this, "list" );
	list->setGeometry( 0, 90, 470, 200 );
	{
		QFont font( "Fixed", 10, 50, 0 );
		font.setFixedPitch( TRUE );
		font.setStyleHint( (QFont::StyleHint)4 );
		list->setFont( font );
	}
	connect( list, SIGNAL(selected(int)), SLOT(editPaymentTermsL(int)) );
	list->setFrameStyle( 51 );
	list->setLineWidth( 2 );

	QPushButton* tmpQPushButton;
	tmpQPushButton = new QPushButton( this, "newBut" );
	tmpQPushButton->setGeometry( 0, 30, 60, 30 );
	{
        /*
		QColorGroup normal( QColor( QRgb(0) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QColorGroup disabled( QColor( QRgb(8421504) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(8421504) ), QColor( QRgb(12632256) ) );
		QColorGroup active( QColor( QRgb(0) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QPalette palette( normal, disabled, active );
		tmpQPushButton->setPalette( palette );
        */
	}
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(newPaymentTerms()) );
	tmpQPushButton->setText( "New" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	tmpQPushButton = new QPushButton( this, "editBut" );
	tmpQPushButton->setGeometry( 60, 30, 60, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(editPaymentTerms()) );
	tmpQPushButton->setText( "Edit" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	tmpQPushButton = new QPushButton( this, "closeBut" );
	tmpQPushButton->setGeometry( 180, 30, 60, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(Hide()) );
	tmpQPushButton->setText( "Close" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	tmpQPushButton = new QPushButton( this, "deleteBut" );
	tmpQPushButton->setGeometry( 120, 30, 60, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(deletePaymentTerms()) );
	tmpQPushButton->setText( "Delete" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	menu = new QMenuBar( this, "menu" );
	menu->setGeometry( 0, 0, 470, 30 );
	menu->setFrameStyle( 34 );
	menu->setLineWidth( 2 );

	QLabel* tmpQLabel;
	tmpQLabel = new QLabel( this, "Label_14" );
	tmpQLabel->setGeometry( 0, 60, 470, 30 );
	{
		QFont font( "Fixed", 10, 50, 0 );
		font.setStyleHint( (QFont::StyleHint)4 );
		tmpQLabel->setFont( font );
	}
	tmpQLabel->setFrameStyle( 34 );
	tmpQLabel->setText( "Description" );
	tmpQLabel->setAlignment( 273 );
	tmpQLabel->setMargin( -1 );

	resize( 470, 290 );
}


PaymentTermsData::~PaymentTermsData()
{
}
void PaymentTermsData::editPaymentTermsL(int)
{
}
void PaymentTermsData::newPaymentTerms()
{
}
void PaymentTermsData::editPaymentTerms()
{
}
void PaymentTermsData::Hide()
{
}
void PaymentTermsData::deletePaymentTerms()
{
}
