/**********************************************************************

	--- Qt Architect generated file ---

	File: RatePlanEditData.cpp
	Last generated: Thu Dec 25 23:48:38 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "RatePlanEditData.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qpushbt.h>

RatePlanEditData::RatePlanEditData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	autoConvertGroup = new QButtonGroup( this, "ButtonGroup_2" );
	autoConvertGroup->setGeometry( 10, 70, 385, 130 );
	autoConvertGroup->setMinimumSize( 10, 10 );
	autoConvertGroup->setMaximumSize( 32767, 32767 );
	autoConvertGroup->setFrameStyle( 49 );
	autoConvertGroup->setTitle( "Auto Convert" );
	autoConvertGroup->setAlignment( 1 );

	QLabel* dlgedit_Label_3;
	dlgedit_Label_3 = new QLabel( this, "Label_3" );
	dlgedit_Label_3->setGeometry( 10, 10, 100, 20 );
	dlgedit_Label_3->setMinimumSize( 10, 10 );
	dlgedit_Label_3->setMaximumSize( 32767, 32767 );
	dlgedit_Label_3->setText( "Tag:" );
	dlgedit_Label_3->setAlignment( 290 );
	dlgedit_Label_3->setMargin( -1 );

	QLabel* dlgedit_Label_4;
	dlgedit_Label_4 = new QLabel( this, "Label_4" );
	dlgedit_Label_4->setGeometry( 10, 35, 100, 20 );
	dlgedit_Label_4->setMinimumSize( 10, 10 );
	dlgedit_Label_4->setMaximumSize( 32767, 32767 );
	dlgedit_Label_4->setText( "Description:" );
	dlgedit_Label_4->setAlignment( 290 );
	dlgedit_Label_4->setMargin( -1 );

	noAutoConvert = new QRadioButton( this, "RadioButton_3" );
	noAutoConvert->setGeometry( 25, 90, 150, 20 );
	noAutoConvert->setMinimumSize( 10, 10 );
	noAutoConvert->setMaximumSize( 32767, 32767 );
	connect( noAutoConvert, SIGNAL(toggled(bool)), SLOT(toggleAutoConvert(bool)) );
	noAutoConvert->setText( "Do not auto-convert." );
	noAutoConvert->setAutoRepeat( FALSE );
	noAutoConvert->setAutoResize( FALSE );
	noAutoConvert->setChecked( TRUE );

	autoConvertDays = new QRadioButton( this, "RadioButton_4" );
	autoConvertDays->setGeometry( 25, 110, 75, 20 );
	autoConvertDays->setMinimumSize( 10, 10 );
	autoConvertDays->setMaximumSize( 32767, 32767 );
	connect( autoConvertDays, SIGNAL(toggled(bool)), SLOT(toggleConvertDays(bool)) );
	autoConvertDays->setText( "Convert " );
	autoConvertDays->setAutoRepeat( FALSE );
	autoConvertDays->setAutoResize( FALSE );

	convertDaysLabel = new QLabel( this, "Label_5" );
	convertDaysLabel->setGeometry( 140, 110, 205, 20 );
	convertDaysLabel->setMinimumSize( 10, 10 );
	convertDaysLabel->setMaximumSize( 32767, 32767 );
	convertDaysLabel->setText( "days after the account is created." );
	convertDaysLabel->setAlignment( 289 );
	convertDaysLabel->setMargin( -1 );

	autoConvertDate = new QRadioButton( this, "RadioButton_5" );
	autoConvertDate->setGeometry( 25, 130, 145, 20 );
	autoConvertDate->setMinimumSize( 10, 10 );
	autoConvertDate->setMaximumSize( 32767, 32767 );
	connect( autoConvertDate, SIGNAL(toggled(bool)), SLOT(toggleConvertDate(bool)) );
	autoConvertDate->setText( "Convert on this date" );
	autoConvertDate->setAutoRepeat( FALSE );
	autoConvertDate->setAutoResize( FALSE );

	convertToLabel = new QLabel( this, "Label_6" );
	convertToLabel->setGeometry( 25, 165, 85, 20 );
	convertToLabel->setMinimumSize( 10, 10 );
	convertToLabel->setMaximumSize( 32767, 32767 );
	convertToLabel->setText( "Convert to:" );
	convertToLabel->setAlignment( 290 );
	convertToLabel->setMargin( -1 );

	planTag = new QLineEdit( this, "LineEdit_3" );
	planTag->setGeometry( 115, 10, 105, 20 );
	planTag->setMinimumSize( 10, 10 );
	planTag->setMaximumSize( 32767, 32767 );
	planTag->setText( "" );
	planTag->setMaxLength( 16 );
	planTag->setEchoMode( QLineEdit::Normal );
	planTag->setFrame( TRUE );

	description = new QLineEdit( this, "LineEdit_4" );
	description->setGeometry( 115, 35, 280, 20 );
	description->setMinimumSize( 10, 10 );
	description->setMaximumSize( 32767, 32767 );
	description->setText( "" );
	description->setMaxLength( 80 );
	description->setEchoMode( QLineEdit::Normal );
	description->setFrame( TRUE );

	convertDays = new QLineEdit( this, "LineEdit_5" );
	convertDays->setGeometry( 100, 110, 30, 20 );
	convertDays->setMinimumSize( 10, 10 );
	convertDays->setMaximumSize( 32767, 32767 );
	convertDays->setText( "" );
	convertDays->setMaxLength( 3 );
	convertDays->setEchoMode( QLineEdit::Normal );
	convertDays->setFrame( TRUE );

	convertDate = new QLineEdit( this, "LineEdit_6" );
	convertDate->setGeometry( 170, 130, 75, 20 );
	convertDate->setMinimumSize( 10, 10 );
	convertDate->setMaximumSize( 32767, 32767 );
	convertDate->setText( "" );
	convertDate->setMaxLength( 10 );
	convertDate->setEchoMode( QLineEdit::Normal );
	convertDate->setFrame( TRUE );

	convertToList = new QComboBox( FALSE, this, "ComboBox_1" );
	convertToList->setGeometry( 115, 165, 275, 20 );
	convertToList->setMinimumSize( 10, 10 );
	convertToList->setMaximumSize( 32767, 32767 );
	convertToList->setSizeLimit( 10 );
	convertToList->setAutoResize( FALSE );

	promoPlan = new QCheckBox( this, "CheckBox_1" );
	promoPlan->setGeometry( 35, 205, 125, 20 );
	promoPlan->setMinimumSize( 10, 10 );
	promoPlan->setMaximumSize( 32767, 32767 );
	connect( promoPlan, SIGNAL(toggled(bool)), SLOT(togglePromoPlan(bool)) );
	promoPlan->setText( "Promotional Plan" );
	promoPlan->setAutoRepeat( FALSE );
	promoPlan->setAutoResize( FALSE );

	promoEndsOnLabel = new QLabel( this, "Label_7" );
	promoEndsOnLabel->setGeometry( 190, 205, 120, 20 );
	promoEndsOnLabel->setMinimumSize( 10, 10 );
	promoEndsOnLabel->setMaximumSize( 32767, 32767 );
	promoEndsOnLabel->setText( "Promotion Ends On:" );
	promoEndsOnLabel->setAlignment( 290 );
	promoEndsOnLabel->setMargin( -1 );

	promoEndsOn = new QLineEdit( this, "LineEdit_7" );
	promoEndsOn->setGeometry( 315, 205, 75, 20 );
	promoEndsOn->setMinimumSize( 10, 10 );
	promoEndsOn->setMaximumSize( 32767, 32767 );
	promoEndsOn->setText( "" );
	promoEndsOn->setMaxLength( 10 );
	promoEndsOn->setEchoMode( QLineEdit::Normal );
	promoEndsOn->setFrame( TRUE );

	QPushButton* dlgedit_PushButton_5;
	dlgedit_PushButton_5 = new QPushButton( this, "PushButton_5" );
	dlgedit_PushButton_5->setGeometry( 180, 250, 100, 30 );
	dlgedit_PushButton_5->setMinimumSize( 10, 10 );
	dlgedit_PushButton_5->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_5, SIGNAL(clicked()), SLOT(saveRatePlan()) );
	dlgedit_PushButton_5->setText( "&Save" );
	dlgedit_PushButton_5->setAutoRepeat( FALSE );
	dlgedit_PushButton_5->setAutoResize( FALSE );

	QPushButton* dlgedit_PushButton_6;
	dlgedit_PushButton_6 = new QPushButton( this, "PushButton_6" );
	dlgedit_PushButton_6->setGeometry( 290, 250, 100, 30 );
	dlgedit_PushButton_6->setMinimumSize( 10, 10 );
	dlgedit_PushButton_6->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_6, SIGNAL(clicked()), SLOT(cancelRatePlan()) );
	dlgedit_PushButton_6->setText( "&Cancel" );
	dlgedit_PushButton_6->setAutoRepeat( FALSE );
	dlgedit_PushButton_6->setAutoResize( FALSE );

	autoConvertGroup->insert( noAutoConvert );
	autoConvertGroup->insert( autoConvertDays );
	autoConvertGroup->insert( autoConvertDate );

	resize( 400,290 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


RatePlanEditData::~RatePlanEditData()
{
}
void RatePlanEditData::toggleAutoConvert(bool)
{
}
void RatePlanEditData::toggleConvertDays(bool)
{
}
void RatePlanEditData::toggleConvertDate(bool)
{
}
void RatePlanEditData::togglePromoPlan(bool)
{
}
void RatePlanEditData::saveRatePlan()
{
}
void RatePlanEditData::cancelRatePlan()
{
}
