/**********************************************************************

	--- Dlgedit generated file ---

	File: RatePlansData.cpp
	Last generated: Tue Oct 14 16:04:44 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#include "RatePlansData.h"

#define Inherited QWidget

#include <qframe.h>
#include <qlabel.h>
#include <qpushbt.h>

RatePlansData::RatePlansData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name )
{
	menu = new QMenuBar( this, "MenuBar_2" );
	menu->setGeometry( 0, 0, 459, 30 );
	menu->setFrameStyle( 34 );
	menu->setLineWidth( 2 );

	QPushButton* tmpQPushButton;
	tmpQPushButton = new QPushButton( this, "PushButton_10" );
	tmpQPushButton->setGeometry( 0, 30, 60, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(newRatePlan()) );
	tmpQPushButton->setText( "New" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	tmpQPushButton = new QPushButton( this, "PushButton_11" );
	tmpQPushButton->setGeometry( 60, 30, 60, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(editRatePlan()) );
	tmpQPushButton->setText( "Edit" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	tmpQPushButton = new QPushButton( this, "PushButton_12" );
	tmpQPushButton->setGeometry( 120, 30, 60, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(deleteRatePlan()) );
	tmpQPushButton->setText( "Delete" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	tmpQPushButton = new QPushButton( this, "PushButton_13" );
	tmpQPushButton->setGeometry( 180, 30, 60, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(Hide()) );
	tmpQPushButton->setText( "Close" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	list = new QListBox( this, "ListBox_2" );
	list->setGeometry( 0, 80, 459, 215 );
	connect( list, SIGNAL(selected(int)), SLOT(editRatePlanL(int)) );
	list->setFrameStyle( 51 );
	list->setLineWidth( 2 );

	QFrame* tmpQFrame;
	tmpQFrame = new QFrame( this, "Frame_1" );
	tmpQFrame->setGeometry( 124, 82, 3, 211 );
	{
        /*
		QColorGroup normal( QColor( QRgb(0) ), QColor( QRgb(16777215) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QColorGroup disabled( QColor( QRgb(8421504) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(8421504) ), QColor( QRgb(12632256) ) );
		QColorGroup active( QColor( QRgb(0) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(6316128) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QPalette palette( normal, disabled, active );
		tmpQFrame->setPalette( palette );
        */
	}
	tmpQFrame->setFrameStyle( 37 );
	tmpQFrame->setMidLineWidth( 1 );

	QLabel* tmpQLabel;
	tmpQLabel = new QLabel( this, "Label_16" );
	tmpQLabel->setGeometry( 125, 60, 333, 20 );
	{
		QFont font( "Fixed", 10, 50, 0 );
		font.setStyleHint( (QFont::StyleHint)4 );
		tmpQLabel->setFont( font );
	}
	tmpQLabel->setFrameStyle( 34 );
	tmpQLabel->setText( "Description" );
	tmpQLabel->setAlignment( 273 );
	tmpQLabel->setMargin( -1 );

	tmpQLabel = new QLabel( this, "Label_15" );
	tmpQLabel->setGeometry( 0, 60, 127, 20 );
	{
		QFont font( "Fixed", 10, 50, 0 );
		font.setStyleHint( (QFont::StyleHint)4 );
		tmpQLabel->setFont( font );
	}
	tmpQLabel->setFrameStyle( 34 );
	tmpQLabel->setText( "Plan ID" );
	tmpQLabel->setAlignment( 273 );
	tmpQLabel->setMargin( -1 );

	resize( 459, 300 );
}


RatePlansData::~RatePlansData()
{
}
void RatePlansData::newRatePlan()
{
}
void RatePlansData::editRatePlan()
{
}
void RatePlansData::deleteRatePlan()
{
}
void RatePlansData::Hide()
{
}
void RatePlansData::editRatePlanL(int)
{
}
