/**********************************************************************

	--- Dlgedit generated file ---

	File: RatePlansData.h
	Last generated: Tue Oct 14 16:04:44 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef RatePlansData_included
#define RatePlansData_included

#include <qwidget.h>
#include <qlistbox.h>
#include <qmenubar.h>

class RatePlansData : public QWidget
{
    Q_OBJECT

public:

    RatePlansData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~RatePlansData();

public slots:


protected slots:

    virtual void Hide();
    virtual void editRatePlan();
    virtual void newRatePlan();
    virtual void deleteRatePlan();
    virtual void editRatePlanL(int);

protected:
    QMenuBar* menu;
    QListBox* list;

};

#endif // RatePlansData_included
