/**********************************************************************

	--- Qt Architect generated file ---

	File: RatePlanEditData.h
	Last generated: Thu Dec 25 23:48:38 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef RatePlanEditData_included
#define RatePlanEditData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qbttngrp.h>
#include <qchkbox.h>
#include <qlined.h>
#include <qradiobt.h>
#include <qcombo.h>

class RatePlanEditData : public QWidget
{
    Q_OBJECT

public:

    RatePlanEditData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~RatePlanEditData();

public slots:


protected slots:

    virtual void toggleAutoConvert(bool);
    virtual void toggleConvertDays(bool);
    virtual void cancelRatePlan();
    virtual void togglePromoPlan(bool);
    virtual void toggleConvertDate(bool);
    virtual void saveRatePlan();

protected:
    QButtonGroup* autoConvertGroup;
    QRadioButton* noAutoConvert;
    QRadioButton* autoConvertDays;
    QLabel* convertDaysLabel;
    QRadioButton* autoConvertDate;
    QLabel* convertToLabel;
    QLineEdit* planTag;
    QLineEdit* description;
    QLineEdit* convertDays;
    QLineEdit* convertDate;
    QComboBox* convertToList;
    QCheckBox* promoPlan;
    QLabel* promoEndsOnLabel;
    QLineEdit* promoEndsOn;

};

#endif // RatePlanEditData_included
