/**********************************************************************

	--- Qt Architect generated file ---

	File: RunSubscriptionsData.h
	Last generated: Wed Aug 26 15:14:00 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef RunSubscriptionsData_included
#define RunSubscriptionsData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qpushbt.h>
#include <qprogbar.h>
#include "qlistview.h"

class RunSubscriptionsData : public QDialog
{
    Q_OBJECT

public:

    RunSubscriptionsData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~RunSubscriptionsData();

public slots:


protected slots:

    virtual void processSelections();
    virtual void cancelAction();

protected:
    QListView* list;
    QPushButton* beginButton;
    QPushButton* cancelButton;
    QLabel* totalSubscriptions;
    QLabel* accountsReceivable;
    QLabel* amountCharged;
    QProgressBar* progress;
    QLabel* progressLabel;

};

#endif // RunSubscriptionsData_included
