/**********************************************************************

	--- Qt Architect generated file ---

	File: RunSubscriptionsData.cpp
	Last generated: Wed Aug 26 15:14:00 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "RunSubscriptionsData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qbttngrp.h>

RunSubscriptionsData::RunSubscriptionsData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* dlgedit_ButtonGroup_3;
	dlgedit_ButtonGroup_3 = new QButtonGroup( this, "ButtonGroup_3" );
	dlgedit_ButtonGroup_3->setGeometry( 5, 285, 295, 105 );
	dlgedit_ButtonGroup_3->setMinimumSize( 10, 10 );
	dlgedit_ButtonGroup_3->setMaximumSize( 32767, 32767 );
	dlgedit_ButtonGroup_3->setFrameStyle( 49 );
	dlgedit_ButtonGroup_3->setTitle( "Summary Information" );
	dlgedit_ButtonGroup_3->setAlignment( 1 );

	list = new QListView( this, "User_1" );
	list->setGeometry( 5, 35, 590, 240 );
	list->setMinimumSize( 10, 10 );
	list->setMaximumSize( 32767, 32767 );

	QLabel* dlgedit_Label_2;
	dlgedit_Label_2 = new QLabel( this, "Label_2" );
	dlgedit_Label_2->setGeometry( 5, 10, 325, 25 );
	dlgedit_Label_2->setMinimumSize( 10, 10 );
	dlgedit_Label_2->setMaximumSize( 32767, 32767 );
	dlgedit_Label_2->setText( "The following accounts have pending subscriptions." );
	dlgedit_Label_2->setAlignment( 1313 );
	dlgedit_Label_2->setMargin( -1 );

	beginButton = new QPushButton( this, "PushButton_1" );
	beginButton->setGeometry( 510, 340, 80, 25 );
	beginButton->setMinimumSize( 10, 10 );
	beginButton->setMaximumSize( 32767, 32767 );
	connect( beginButton, SIGNAL(clicked()), SLOT(processSelections()) );
	beginButton->setText( "&Begin" );
	beginButton->setAutoRepeat( FALSE );
	beginButton->setAutoResize( FALSE );
	beginButton->setAutoDefault( TRUE );

	cancelButton = new QPushButton( this, "PushButton_2" );
	cancelButton->setGeometry( 510, 370, 80, 25 );
	cancelButton->setMinimumSize( 10, 10 );
	cancelButton->setMaximumSize( 32767, 32767 );
	connect( cancelButton, SIGNAL(clicked()), SLOT(cancelAction()) );
	cancelButton->setText( "&Cancel" );
	cancelButton->setAutoRepeat( FALSE );
	cancelButton->setAutoResize( FALSE );

	QLabel* dlgedit_Label_4;
	dlgedit_Label_4 = new QLabel( this, "Label_4" );
	dlgedit_Label_4->setGeometry( 10, 305, 135, 20 );
	dlgedit_Label_4->setMinimumSize( 10, 10 );
	dlgedit_Label_4->setMaximumSize( 32767, 32767 );
	dlgedit_Label_4->setText( "Total Subscriptions:" );
	dlgedit_Label_4->setAlignment( 290 );
	dlgedit_Label_4->setMargin( -1 );

	QLabel* dlgedit_Label_5;
	dlgedit_Label_5 = new QLabel( this, "Label_5" );
	dlgedit_Label_5->setGeometry( 10, 325, 135, 20 );
	dlgedit_Label_5->setMinimumSize( 10, 10 );
	dlgedit_Label_5->setMaximumSize( 32767, 32767 );
	dlgedit_Label_5->setText( "Accounts Receivable:" );
	dlgedit_Label_5->setAlignment( 290 );
	dlgedit_Label_5->setMargin( -1 );

	QLabel* dlgedit_Label_6;
	dlgedit_Label_6 = new QLabel( this, "Label_6" );
	dlgedit_Label_6->setGeometry( 10, 345, 135, 20 );
	dlgedit_Label_6->setMinimumSize( 10, 10 );
	dlgedit_Label_6->setMaximumSize( 32767, 32767 );
	dlgedit_Label_6->setText( "Amount Charged:" );
	dlgedit_Label_6->setAlignment( 290 );
	dlgedit_Label_6->setMargin( -1 );

	totalSubscriptions = new QLabel( this, "Label_8" );
	totalSubscriptions->setGeometry( 150, 305, 145, 20 );
	totalSubscriptions->setMinimumSize( 10, 10 );
	totalSubscriptions->setMaximumSize( 32767, 32767 );
	totalSubscriptions->setFrameStyle( 50 );
	totalSubscriptions->setText( "" );
	totalSubscriptions->setAlignment( 290 );
	totalSubscriptions->setMargin( -1 );

	accountsReceivable = new QLabel( this, "Label_9" );
	accountsReceivable->setGeometry( 150, 325, 145, 20 );
	accountsReceivable->setMinimumSize( 10, 10 );
	accountsReceivable->setMaximumSize( 32767, 32767 );
	accountsReceivable->setFrameStyle( 50 );
	accountsReceivable->setText( "" );
	accountsReceivable->setAlignment( 290 );
	accountsReceivable->setMargin( -1 );

	amountCharged = new QLabel( this, "Label_10" );
	amountCharged->setGeometry( 150, 345, 145, 20 );
	amountCharged->setMinimumSize( 10, 10 );
	amountCharged->setMaximumSize( 32767, 32767 );
	amountCharged->setFrameStyle( 50 );
	amountCharged->setLineWidth( 2 );
	amountCharged->setText( "" );
	amountCharged->setAlignment( 290 );
	amountCharged->setMargin( -1 );

	progress = new QProgressBar( 100, this, "ProgressBar_1" );
	progress->setGeometry( 430, 10, 165, 20 );
	progress->setMinimumSize( 10, 10 );
	progress->setMaximumSize( 32767, 32767 );
	progress->setFrameStyle( 51 );
	progress->setLineWidth( 2 );
	progress->setProgress( -1 );

	progressLabel = new QLabel( this, "Label_12" );
	progressLabel->setGeometry( 350, 10, 75, 20 );
	progressLabel->setMinimumSize( 10, 10 );
	progressLabel->setMaximumSize( 32767, 32767 );
	progressLabel->setText( "Searching..." );
	progressLabel->setAlignment( 290 );
	progressLabel->setMargin( -1 );


	resize( 600,400 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


RunSubscriptionsData::~RunSubscriptionsData()
{
}
void RunSubscriptionsData::processSelections()
{
}
void RunSubscriptionsData::cancelAction()
{
}
