/**********************************************************************

	--- Qt Architect generated file ---

	File: TE_CitiesData.cpp
	Last generated: Tue Jul 27 14:18:49 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "TE_CitiesData.h"

#define Inherited QWidget


TE_CitiesData::TE_CitiesData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	allCitiesButton = new QCheckBox( this, "AllCitiesButton" );
	allCitiesButton->setGeometry( 5, 5, 435, 25 );
	allCitiesButton->setMinimumSize( 0, 25 );
	allCitiesButton->setMaximumSize( 32767, 25 );
	connect( allCitiesButton, SIGNAL(clicked()), SLOT(allCitiesClicked()) );
	allCitiesButton->setFocusPolicy( QWidget::TabFocus );
	allCitiesButton->setBackgroundMode( QWidget::PaletteBackground );
	allCitiesButton->setText( "Send to customers in all cities" );
	allCitiesButton->setAutoRepeat( FALSE );
	allCitiesButton->setAutoResize( FALSE );

	cityList = new QListView( this, "CityList" );
	cityList->setGeometry( 5, 35, 435, 250 );
	cityList->setMinimumSize( 0, 0 );
	cityList->setMaximumSize( 32767, 32767 );
	cityList->setFocusPolicy( QWidget::TabFocus );
	cityList->setBackgroundMode( QWidget::PaletteBackground );
	cityList->setResizePolicy( QScrollView::Manual );
	cityList->setVScrollBarMode( QScrollView::Auto );
	cityList->setHScrollBarMode( QScrollView::Auto );
	cityList->setTreeStepSize( 20 );
	cityList->setMultiSelection( FALSE );
	cityList->setAllColumnsShowFocus( FALSE );
	cityList->setItemMargin( 1 );
	cityList->setRootIsDecorated( FALSE );
	cityList->addColumn( "City", -1 );
	cityList->setColumnWidthMode( 0, QListView::Maximum );
	cityList->setColumnAlignment( 0, 1 );
	cityList->addColumn( "Cust Count", -1 );
	cityList->setColumnWidthMode( 1, QListView::Maximum );
	cityList->setColumnAlignment( 1, 2 );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( allCitiesButton, 0, 34 );
	qtarch_layout_1->addWidget( cityList, 1, 36 );
	resize( 445,290 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


TE_CitiesData::~TE_CitiesData()
{
}
void TE_CitiesData::allCitiesClicked()
{
}
