/**********************************************************************

	--- Qt Architect generated file ---

	File: TE_CitiesData.h
	Last generated: Tue Jul 27 14:18:49 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef TE_CitiesData_included
#define TE_CitiesData_included

#include <qwidget.h>
#include <qchkbox.h>
#include <qlistview.h>

class TE_CitiesData : public QWidget
{
    Q_OBJECT

public:

    TE_CitiesData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~TE_CitiesData();

public slots:


protected slots:

    virtual void allCitiesClicked();

protected:
    QCheckBox* allCitiesButton;
    QListView* cityList;

};

#endif // TE_CitiesData_included
