/**********************************************************************

	--- Qt Architect generated file ---

	File: TE_LoginTypesData.h
	Last generated: Sat Jul 31 14:28:00 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef TE_LoginTypesData_included
#define TE_LoginTypesData_included

#include <qwidget.h>
#include <qchkbox.h>
#include <qlistview.h>

class TE_LoginTypesData : public QWidget
{
    Q_OBJECT

public:

    TE_LoginTypesData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~TE_LoginTypesData();

public slots:


protected slots:

    virtual void allLoginsClicked();
    virtual void listItemSelected(QListViewItem*);

protected:
    QCheckBox* allLoginsButton;
    QCheckBox* includeInactive;
    QListView* loginTypeList;
    QCheckBox* primaryOnlyCheckbox;

};

#endif // TE_LoginTypesData_included
