/**********************************************************************

	--- Qt Architect generated file ---

	File: TE_LoginTypesData.cpp
	Last generated: Sat Jul 31 14:28:00 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "TE_LoginTypesData.h"

#define Inherited QWidget


TE_LoginTypesData::TE_LoginTypesData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	allLoginsButton = new QCheckBox( this, "AllLoginsCheckbox" );
	allLoginsButton->setGeometry( 5, 5, 198, 25 );
	allLoginsButton->setMinimumSize( 0, 0 );
	allLoginsButton->setMaximumSize( 32767, 32767 );
	connect( allLoginsButton, SIGNAL(clicked()), SLOT(allLoginsClicked()) );
	allLoginsButton->setFocusPolicy( QWidget::TabFocus );
	allLoginsButton->setBackgroundMode( QWidget::PaletteBackground );
	allLoginsButton->setText( "Send to all Login Types" );
	allLoginsButton->setAutoRepeat( FALSE );
	allLoginsButton->setAutoResize( FALSE );

	includeInactive = new QCheckBox( this, "IncludeInactiveButton" );
	includeInactive->setGeometry( 208, 5, 197, 25 );
	includeInactive->setMinimumSize( 0, 25 );
	includeInactive->setMaximumSize( 32767, 25 );
	includeInactive->setFocusPolicy( QWidget::TabFocus );
	includeInactive->setBackgroundMode( QWidget::PaletteBackground );
	includeInactive->setText( "Include inactive accounts" );
	includeInactive->setAutoRepeat( FALSE );
	includeInactive->setAutoResize( FALSE );

	loginTypeList = new QListView( this, "LoginTypeList" );
	loginTypeList->setGeometry( 5, 65, 400, 220 );
	loginTypeList->setMinimumSize( 0, 0 );
	loginTypeList->setMaximumSize( 32767, 32767 );
	connect( loginTypeList, SIGNAL(currentChanged(QListViewItem*)), SLOT(listItemSelected(QListViewItem*)) );
	loginTypeList->setFocusPolicy( QWidget::TabFocus );
	loginTypeList->setBackgroundMode( QWidget::PaletteBackground );
	loginTypeList->setResizePolicy( QScrollView::Manual );
	loginTypeList->setVScrollBarMode( QScrollView::Auto );
	loginTypeList->setHScrollBarMode( QScrollView::Auto );
	loginTypeList->setTreeStepSize( 20 );
	loginTypeList->setMultiSelection( FALSE );
	loginTypeList->setAllColumnsShowFocus( FALSE );
	loginTypeList->setItemMargin( 1 );
	loginTypeList->setRootIsDecorated( FALSE );
	loginTypeList->addColumn( "Type", -1 );
	loginTypeList->setColumnWidthMode( 0, QListView::Maximum );
	loginTypeList->setColumnAlignment( 0, 1 );
	loginTypeList->addColumn( "Description", -1 );
	loginTypeList->setColumnWidthMode( 1, QListView::Maximum );
	loginTypeList->setColumnAlignment( 1, 1 );
	loginTypeList->addColumn( "Inactive", -1 );
	loginTypeList->setColumnWidthMode( 2, QListView::Maximum );
	loginTypeList->setColumnAlignment( 2, 2 );
	loginTypeList->addColumn( "Active", -1 );
	loginTypeList->setColumnWidthMode( 3, QListView::Maximum );
	loginTypeList->setColumnAlignment( 3, 2 );

	primaryOnlyCheckbox = new QCheckBox( this, "PrimaryOnlyCheckBox" );
	primaryOnlyCheckbox->setGeometry( 5, 35, 198, 25 );
	primaryOnlyCheckbox->setMinimumSize( 0, 25 );
	primaryOnlyCheckbox->setMaximumSize( 32767, 25 );
	primaryOnlyCheckbox->setFocusPolicy( QWidget::TabFocus );
	primaryOnlyCheckbox->setBackgroundMode( QWidget::PaletteBackground );
	primaryOnlyCheckbox->setText( "Send to Primary Logins Only" );
	primaryOnlyCheckbox->setAutoRepeat( FALSE );
	primaryOnlyCheckbox->setAutoResize( FALSE );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QGridLayout* qtarch_layout_1_1 = new QGridLayout( 2, 2, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 0 );
	qtarch_layout_1_1->addColSpacing( 0, 5 );
	qtarch_layout_1_1->setColStretch( 0, 1 );
	qtarch_layout_1_1->addColSpacing( 1, 5 );
	qtarch_layout_1_1->setColStretch( 1, 1 );
	qtarch_layout_1_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_1->setRowStretch( 0, 0 );
	qtarch_layout_1_1->addWidget( allLoginsButton, 0, 0, 36 );
	qtarch_layout_1_1->addWidget( includeInactive, 0, 1, 36 );
	qtarch_layout_1_1->addRowSpacing( 1, 0 );
	qtarch_layout_1_1->setRowStretch( 1, 1 );
	qtarch_layout_1_1->addWidget( primaryOnlyCheckbox, 1, 0, 36 );
	qtarch_layout_1->addWidget( loginTypeList, 1, 36 );
	resize( 410,290 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


TE_LoginTypesData::~TE_LoginTypesData()
{
}
void TE_LoginTypesData::allLoginsClicked()
{
}
void TE_LoginTypesData::listItemSelected(QListViewItem*)
{
}
