/**********************************************************************

	--- Qt Architect generated file ---

	File: TE_MainData.cpp
	Last generated: Tue Jul 27 15:26:12 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "TE_MainData.h"

#define Inherited QWidget

#include <qbttngrp.h>
#include <qpushbt.h>

TE_MainData::TE_MainData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	theTabBar = new QTabBar( this, "TheTabBar" );
	theTabBar->setGeometry( 5, 5, 415, 24 );
	theTabBar->setMinimumSize( 0, 24 );
	theTabBar->setMaximumSize( 32767, 24 );
	connect( theTabBar, SIGNAL(selected(int)), SLOT(tabSelected(int)) );
	theTabBar->setFocusPolicy( QWidget::TabFocus );
	theTabBar->setBackgroundMode( QWidget::PaletteBackground );
	theTabBar->setShape( QTabBar::RoundedAbove );
	{
		QTab* tab;
		tab = new QTab("Message");
		theTabBar->addTab( tab );

		tab = new QTab("Login Types");
		theTabBar->addTab( tab );

		tab = new QTab("Cities");
		theTabBar->addTab( tab );

	}

	QButtonGroup* qtarch_ButtonGroup_1;
	qtarch_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	qtarch_ButtonGroup_1->setGeometry( 5, 29, 415, 276 );
	qtarch_ButtonGroup_1->setMinimumSize( 10, 10 );
	qtarch_ButtonGroup_1->setMaximumSize( 32767, 32767 );
	qtarch_ButtonGroup_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_ButtonGroup_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ButtonGroup_1->setFrameStyle( 49 );
	qtarch_ButtonGroup_1->setTitle( "" );
	qtarch_ButtonGroup_1->setAlignment( 1 );

	QPushButton* qtarch_SendButton;
	qtarch_SendButton = new QPushButton( this, "SendButton" );
	qtarch_SendButton->setGeometry( 360, 310, 60, 25 );
	qtarch_SendButton->setMinimumSize( 60, 25 );
	qtarch_SendButton->setMaximumSize( 60, 25 );
	connect( qtarch_SendButton, SIGNAL(clicked()), SLOT(sendMessage()) );
	qtarch_SendButton->setFocusPolicy( QWidget::TabFocus );
	qtarch_SendButton->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_SendButton->setText( "&Send" );
	qtarch_SendButton->setAutoRepeat( FALSE );
	qtarch_SendButton->setAutoResize( FALSE );

	qws = new QWidgetStack( qtarch_ButtonGroup_1, "WidgetStack" );
	qws->setGeometry( 5, 5, 405, 266 );
	qws->setMinimumSize( 0, 0 );
	qws->setMaximumSize( 32767, 32767 );
	qws->setFocusPolicy( QWidget::NoFocus );
	qws->setBackgroundMode( QWidget::PaletteBackground );


	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QBoxLayout* qtarch_layout_1_1 = new QBoxLayout( QBoxLayout::TopToBottom, 0, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 1 );
	qtarch_layout_1_1->addStrut( 0 );
	qtarch_layout_1_1->addWidget( theTabBar, 1, 12 );
	qtarch_layout_1_1->addWidget( qtarch_ButtonGroup_1, 1, 36 );
	QBoxLayout* qtarch_layout_1_1_2 = new QBoxLayout( qtarch_ButtonGroup_1, QBoxLayout::TopToBottom, 5, 0, NULL );
	qtarch_layout_1_1_2->addStrut( 0 );
	qtarch_layout_1_1_2->addWidget( qws, 1, 36 );
	qtarch_layout_1_1->addSpacing( 5 );
	QGridLayout* qtarch_layout_1_1_4 = new QGridLayout( 1, 1, 5, NULL );
	qtarch_layout_1_1->addLayout( qtarch_layout_1_1_4, 0 );
	qtarch_layout_1_1_4->addColSpacing( 0, 5 );
	qtarch_layout_1_1_4->setColStretch( 0, 1 );
	qtarch_layout_1_1_4->addRowSpacing( 0, 0 );
	qtarch_layout_1_1_4->setRowStretch( 0, 1 );
	qtarch_layout_1_1_4->addWidget( qtarch_SendButton, 0, 0, 34 );
	resize( 425,340 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


TE_MainData::~TE_MainData()
{
}
void TE_MainData::tabSelected(int)
{
}
void TE_MainData::sendMessage()
{
}
