/**********************************************************************

	--- Qt Architect generated file ---

	File: TE_MessageData.cpp
	Last generated: Tue Jul 27 12:05:27 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "TE_MessageData.h"

#define Inherited QWidget

#include <qlabel.h>

TE_MessageData::TE_MessageData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QLabel* qtarch_FromLabel;
	qtarch_FromLabel = new QLabel( this, "FromLabel" );
	qtarch_FromLabel->setGeometry( 5, 5, 80, 25 );
	qtarch_FromLabel->setMinimumSize( 80, 25 );
	qtarch_FromLabel->setMaximumSize( 80, 25 );
	qtarch_FromLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_FromLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_FromLabel->setText( "From:" );
	qtarch_FromLabel->setAlignment( 290 );
	qtarch_FromLabel->setMargin( -1 );

	fromLine = new QLineEdit( this, "FromLine" );
	fromLine->setGeometry( 90, 5, 390, 25 );
	fromLine->setMinimumSize( 0, 25 );
	fromLine->setMaximumSize( 32767, 25 );
	connect( fromLine, SIGNAL(textChanged(const char*)), SLOT(fromChanged(const char*)) );
	fromLine->setFocusPolicy( QWidget::StrongFocus );
	fromLine->setBackgroundMode( QWidget::PaletteBase );
	fromLine->setText( "" );
	fromLine->setMaxLength( 32 );
	fromLine->setEchoMode( QLineEdit::Normal );
	fromLine->setFrame( TRUE );

	QLabel* qtarch_SubjectLabel;
	qtarch_SubjectLabel = new QLabel( this, "SubjectLabel" );
	qtarch_SubjectLabel->setGeometry( 5, 35, 80, 25 );
	qtarch_SubjectLabel->setMinimumSize( 80, 25 );
	qtarch_SubjectLabel->setMaximumSize( 80, 25 );
	qtarch_SubjectLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_SubjectLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_SubjectLabel->setText( "Subject:" );
	qtarch_SubjectLabel->setAlignment( 290 );
	qtarch_SubjectLabel->setMargin( -1 );

	msgSubject = new QLineEdit( this, "SubjectLine" );
	msgSubject->setGeometry( 90, 35, 390, 25 );
	msgSubject->setMinimumSize( 0, 25 );
	msgSubject->setMaximumSize( 32767, 25 );
	connect( msgSubject, SIGNAL(textChanged(const char*)), SLOT(subjectChanged(const char*)) );
	msgSubject->setFocusPolicy( QWidget::StrongFocus );
	msgSubject->setBackgroundMode( QWidget::PaletteBase );
	msgSubject->setText( "" );
	msgSubject->setMaxLength( 80 );
	msgSubject->setEchoMode( QLineEdit::Normal );
	msgSubject->setFrame( TRUE );

	QLabel* qtarch_MsgTextLabel;
	qtarch_MsgTextLabel = new QLabel( this, "MsgTextLabel" );
	qtarch_MsgTextLabel->setGeometry( 5, 65, 80, 220 );
	qtarch_MsgTextLabel->setMinimumSize( 80, 0 );
	qtarch_MsgTextLabel->setMaximumSize( 80, 32767 );
	qtarch_MsgTextLabel->setFocusPolicy( QWidget::NoFocus );
	qtarch_MsgTextLabel->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_MsgTextLabel->setText( "Message Text:" );
	qtarch_MsgTextLabel->setAlignment( 1290 );
	qtarch_MsgTextLabel->setMargin( -1 );

	msgText = new QMultiLineEdit( this, "MsgText" );
	msgText->setGeometry( 90, 65, 390, 220 );
	msgText->setMinimumSize( 0, 0 );
	msgText->setMaximumSize( 32767, 32767 );
	connect( msgText, SIGNAL(textChanged()), SLOT(msgTextChanged()) );
	msgText->setFocusPolicy( QWidget::StrongFocus );
	msgText->setBackgroundMode( QWidget::PaletteBase );
	msgText->insertLine( "" );
	msgText->setReadOnly( FALSE );
	msgText->setOverwriteMode( FALSE );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QGridLayout* qtarch_layout_1_1 = new QGridLayout( 3, 2, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 1 );
	qtarch_layout_1_1->addColSpacing( 0, 5 );
	qtarch_layout_1_1->setColStretch( 0, 0 );
	qtarch_layout_1_1->addColSpacing( 1, 5 );
	qtarch_layout_1_1->setColStretch( 1, 1 );
	qtarch_layout_1_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_1->setRowStretch( 0, 0 );
	qtarch_layout_1_1->addWidget( qtarch_FromLabel, 0, 0, 34 );
	qtarch_layout_1_1->addWidget( fromLine, 0, 1, 36 );
	qtarch_layout_1_1->addRowSpacing( 1, 0 );
	qtarch_layout_1_1->setRowStretch( 1, 0 );
	qtarch_layout_1_1->addWidget( qtarch_SubjectLabel, 1, 0, 36 );
	qtarch_layout_1_1->addWidget( msgSubject, 1, 1, 36 );
	qtarch_layout_1_1->addRowSpacing( 2, 0 );
	qtarch_layout_1_1->setRowStretch( 2, 1 );
	qtarch_layout_1_1->addWidget( qtarch_MsgTextLabel, 2, 0, 36 );
	qtarch_layout_1_1->addWidget( msgText, 2, 1, 36 );
	resize( 485,290 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


TE_MessageData::~TE_MessageData()
{
}
void TE_MessageData::fromChanged(const char*)
{
}
void TE_MessageData::subjectChanged(const char*)
{
}
void TE_MessageData::msgTextChanged()
{
}
