/**********************************************************************

	--- Qt Architect generated file ---

	File: TE_MainData.h
	Last generated: Tue Jul 27 15:26:12 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef TE_MainData_included
#define TE_MainData_included

#include <qwidget.h>
#include "qwidgetstack.h"
#include <qtabbar.h>

class TE_MainData : public QWidget
{
    Q_OBJECT

public:

    TE_MainData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~TE_MainData();

public slots:


protected slots:

    virtual void sendMessage();
    virtual void tabSelected(int);

protected:
    QTabBar* theTabBar;
    QWidgetStack* qws;

};

#endif // TE_MainData_included
