/**********************************************************************

	--- Qt Architect generated file ---

	File: VendorEditData.cpp
	Last generated: Thu Dec 25 23:50:24 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "VendorEditData.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qpushbt.h>
#include <qframe.h>

VendorEditData::VendorEditData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QFrame* dlgedit_Frame_5;
	dlgedit_Frame_5 = new QFrame( this, "Frame_5" );
	dlgedit_Frame_5->setGeometry( 675, 15, 80, 30 );
	dlgedit_Frame_5->setMinimumSize( 10, 10 );
	dlgedit_Frame_5->setMaximumSize( 32767, 32767 );
	dlgedit_Frame_5->setFrameStyle( 49 );

	QLabel* dlgedit_Label_35;
	dlgedit_Label_35 = new QLabel( this, "Label_35" );
	dlgedit_Label_35->setGeometry( 20, 20, 100, 20 );
	dlgedit_Label_35->setMinimumSize( 10, 10 );
	dlgedit_Label_35->setMaximumSize( 32767, 32767 );
	dlgedit_Label_35->setText( "Company Name:" );
	dlgedit_Label_35->setAlignment( 290 );
	dlgedit_Label_35->setMargin( -1 );

	QLabel* dlgedit_Label_36;
	dlgedit_Label_36 = new QLabel( this, "Label_36" );
	dlgedit_Label_36->setGeometry( 20, 50, 100, 20 );
	dlgedit_Label_36->setMinimumSize( 10, 10 );
	dlgedit_Label_36->setMaximumSize( 32767, 32767 );
	dlgedit_Label_36->setText( "Contact Name:" );
	dlgedit_Label_36->setAlignment( 290 );
	dlgedit_Label_36->setMargin( -1 );

	QLabel* dlgedit_Label_39;
	dlgedit_Label_39 = new QLabel( this, "Label_39" );
	dlgedit_Label_39->setGeometry( 400, 50, 100, 20 );
	dlgedit_Label_39->setMinimumSize( 10, 10 );
	dlgedit_Label_39->setMaximumSize( 32767, 32767 );
	dlgedit_Label_39->setText( "Alt. Contact:" );
	dlgedit_Label_39->setAlignment( 290 );
	dlgedit_Label_39->setMargin( -1 );

	QFrame* dlgedit_Frame_10;
	dlgedit_Frame_10 = new QFrame( this, "Frame_10" );
	dlgedit_Frame_10->setGeometry( 10, 90, 370, 80 );
	dlgedit_Frame_10->setMinimumSize( 10, 10 );
	dlgedit_Frame_10->setMaximumSize( 32767, 32767 );
	dlgedit_Frame_10->setFrameStyle( 49 );

	QLabel* dlgedit_Label_40;
	dlgedit_Label_40 = new QLabel( this, "Label_40" );
	dlgedit_Label_40->setGeometry( 20, 80, 60, 20 );
	dlgedit_Label_40->setMinimumSize( 10, 10 );
	dlgedit_Label_40->setMaximumSize( 32767, 32767 );
	dlgedit_Label_40->setText( "Address" );
	dlgedit_Label_40->setAlignment( 292 );
	dlgedit_Label_40->setMargin( -1 );

	QLabel* dlgedit_Label_41;
	dlgedit_Label_41 = new QLabel( this, "Label_41" );
	dlgedit_Label_41->setGeometry( 20, 100, 100, 20 );
	dlgedit_Label_41->setMinimumSize( 10, 10 );
	dlgedit_Label_41->setMaximumSize( 32767, 32767 );
	dlgedit_Label_41->setText( "Address Line 1:" );
	dlgedit_Label_41->setAlignment( 290 );
	dlgedit_Label_41->setMargin( -1 );

	QLabel* dlgedit_Label_42;
	dlgedit_Label_42 = new QLabel( this, "Label_42" );
	dlgedit_Label_42->setGeometry( 30, 120, 90, 20 );
	dlgedit_Label_42->setMinimumSize( 10, 10 );
	dlgedit_Label_42->setMaximumSize( 32767, 32767 );
	dlgedit_Label_42->setText( "Address Line 2:" );
	dlgedit_Label_42->setAlignment( 290 );
	dlgedit_Label_42->setMargin( -1 );

	QLabel* dlgedit_Label_43;
	dlgedit_Label_43 = new QLabel( this, "Label_43" );
	dlgedit_Label_43->setGeometry( 20, 140, 100, 20 );
	dlgedit_Label_43->setMinimumSize( 10, 10 );
	dlgedit_Label_43->setMaximumSize( 32767, 32767 );
	dlgedit_Label_43->setText( "City, State ZIP:" );
	dlgedit_Label_43->setAlignment( 290 );
	dlgedit_Label_43->setMargin( -1 );

	QFrame* dlgedit_Frame_11;
	dlgedit_Frame_11 = new QFrame( this, "Frame_11" );
	dlgedit_Frame_11->setGeometry( 390, 90, 370, 180 );
	dlgedit_Frame_11->setMinimumSize( 10, 10 );
	dlgedit_Frame_11->setMaximumSize( 32767, 32767 );
	dlgedit_Frame_11->setFrameStyle( 49 );

	QFrame* dlgedit_Frame_12;
	dlgedit_Frame_12 = new QFrame( this, "Frame_12" );
	dlgedit_Frame_12->setGeometry( 10, 185, 370, 85 );
	dlgedit_Frame_12->setMinimumSize( 10, 10 );
	dlgedit_Frame_12->setMaximumSize( 32767, 32767 );
	dlgedit_Frame_12->setFrameStyle( 49 );

	QLabel* dlgedit_Label_44;
	dlgedit_Label_44 = new QLabel( this, "Label_44" );
	dlgedit_Label_44->setGeometry( 400, 100, 100, 20 );
	dlgedit_Label_44->setMinimumSize( 10, 10 );
	dlgedit_Label_44->setMaximumSize( 32767, 32767 );
	dlgedit_Label_44->setText( "Print check as:" );
	dlgedit_Label_44->setAlignment( 290 );
	dlgedit_Label_44->setMargin( -1 );

	QLabel* dlgedit_Label_47;
	dlgedit_Label_47 = new QLabel( this, "Label_47" );
	dlgedit_Label_47->setGeometry( 400, 120, 100, 20 );
	dlgedit_Label_47->setMinimumSize( 10, 10 );
	dlgedit_Label_47->setMaximumSize( 32767, 32767 );
	dlgedit_Label_47->setText( "Acct. Number:" );
	dlgedit_Label_47->setAlignment( 290 );
	dlgedit_Label_47->setMargin( -1 );

	QLabel* dlgedit_Label_48;
	dlgedit_Label_48 = new QLabel( this, "Label_48" );
	dlgedit_Label_48->setGeometry( 400, 140, 100, 20 );
	dlgedit_Label_48->setMinimumSize( 10, 10 );
	dlgedit_Label_48->setMaximumSize( 32767, 32767 );
	dlgedit_Label_48->setText( "Vendor Type:" );
	dlgedit_Label_48->setAlignment( 290 );
	dlgedit_Label_48->setMargin( -1 );

	QLabel* dlgedit_Label_49;
	dlgedit_Label_49 = new QLabel( this, "Label_49" );
	dlgedit_Label_49->setGeometry( 400, 160, 100, 20 );
	dlgedit_Label_49->setMinimumSize( 10, 10 );
	dlgedit_Label_49->setMaximumSize( 32767, 32767 );
	dlgedit_Label_49->setText( "Terms:" );
	dlgedit_Label_49->setAlignment( 290 );
	dlgedit_Label_49->setMargin( -1 );

	QLabel* dlgedit_Label_50;
	dlgedit_Label_50 = new QLabel( this, "Label_50" );
	dlgedit_Label_50->setGeometry( 20, 175, 100, 20 );
	dlgedit_Label_50->setMinimumSize( 10, 10 );
	dlgedit_Label_50->setMaximumSize( 32767, 32767 );
	dlgedit_Label_50->setText( "Phone Numbers" );
	dlgedit_Label_50->setAlignment( 292 );
	dlgedit_Label_50->setMargin( -1 );

	QLabel* dlgedit_Label_51;
	dlgedit_Label_51 = new QLabel( this, "Label_51" );
	dlgedit_Label_51->setGeometry( 20, 200, 100, 20 );
	dlgedit_Label_51->setMinimumSize( 10, 10 );
	dlgedit_Label_51->setMaximumSize( 32767, 32767 );
	dlgedit_Label_51->setText( "Primary Phone:" );
	dlgedit_Label_51->setAlignment( 290 );
	dlgedit_Label_51->setMargin( -1 );

	QLabel* dlgedit_Label_52;
	dlgedit_Label_52 = new QLabel( this, "Label_52" );
	dlgedit_Label_52->setGeometry( 20, 220, 100, 20 );
	dlgedit_Label_52->setMinimumSize( 10, 10 );
	dlgedit_Label_52->setMaximumSize( 32767, 32767 );
	dlgedit_Label_52->setText( "Alternate Phone:" );
	dlgedit_Label_52->setAlignment( 290 );
	dlgedit_Label_52->setMargin( -1 );

	QLabel* dlgedit_Label_53;
	dlgedit_Label_53 = new QLabel( this, "Label_53" );
	dlgedit_Label_53->setGeometry( 20, 240, 100, 20 );
	dlgedit_Label_53->setMinimumSize( 10, 10 );
	dlgedit_Label_53->setMaximumSize( 32767, 32767 );
	dlgedit_Label_53->setText( "Fax:" );
	dlgedit_Label_53->setAlignment( 290 );
	dlgedit_Label_53->setMargin( -1 );

	companyName = new QLineEdit( this, "LineEdit_15" );
	companyName->setGeometry( 130, 20, 240, 20 );
	companyName->setMinimumSize( 10, 10 );
	companyName->setMaximumSize( 32767, 32767 );
	companyName->setText( "" );
	companyName->setMaxLength( 60 );
	companyName->setEchoMode( QLineEdit::Normal );
	companyName->setFrame( TRUE );

	contactName = new QLineEdit( this, "LineEdit_16" );
	contactName->setGeometry( 130, 50, 240, 20 );
	contactName->setMinimumSize( 10, 10 );
	contactName->setMaximumSize( 32767, 32767 );
	contactName->setText( "" );
	contactName->setMaxLength( 60 );
	contactName->setEchoMode( QLineEdit::Normal );
	contactName->setFrame( TRUE );

	altContact = new QLineEdit( this, "LineEdit_17" );
	altContact->setGeometry( 510, 50, 240, 20 );
	altContact->setMinimumSize( 10, 10 );
	altContact->setMaximumSize( 32767, 32767 );
	altContact->setText( "" );
	altContact->setMaxLength( 60 );
	altContact->setEchoMode( QLineEdit::Normal );
	altContact->setFrame( TRUE );

	address1 = new QLineEdit( this, "LineEdit_18" );
	address1->setGeometry( 130, 100, 240, 20 );
	address1->setMinimumSize( 10, 10 );
	address1->setMaximumSize( 32767, 32767 );
	address1->setText( "" );
	address1->setMaxLength( 60 );
	address1->setEchoMode( QLineEdit::Normal );
	address1->setFrame( TRUE );

	address2 = new QLineEdit( this, "LineEdit_19" );
	address2->setGeometry( 130, 120, 240, 20 );
	address2->setMinimumSize( 10, 10 );
	address2->setMaximumSize( 32767, 32767 );
	address2->setText( "" );
	address2->setMaxLength( 60 );
	address2->setEchoMode( QLineEdit::Normal );
	address2->setFrame( TRUE );

	city = new QLineEdit( this, "LineEdit_20" );
	city->setGeometry( 130, 140, 125, 20 );
	city->setMinimumSize( 10, 10 );
	city->setMaximumSize( 32767, 32767 );
	city->setText( "" );
	city->setMaxLength( 60 );
	city->setEchoMode( QLineEdit::Normal );
	city->setFrame( TRUE );

	state = new QLineEdit( this, "LineEdit_21" );
	state->setGeometry( 255, 140, 30, 20 );
	state->setMinimumSize( 10, 10 );
	state->setMaximumSize( 32767, 32767 );
	state->setText( "" );
	state->setMaxLength( 2 );
	state->setEchoMode( QLineEdit::Normal );
	state->setFrame( TRUE );

	zip = new QLineEdit( this, "LineEdit_22" );
	zip->setGeometry( 285, 140, 85, 20 );
	zip->setMinimumSize( 10, 10 );
	zip->setMaximumSize( 32767, 32767 );
	zip->setText( "" );
	zip->setMaxLength( 16 );
	zip->setEchoMode( QLineEdit::Normal );
	zip->setFrame( TRUE );

	checkName = new QLineEdit( this, "LineEdit_24" );
	checkName->setGeometry( 505, 100, 245, 20 );
	checkName->setMinimumSize( 10, 10 );
	checkName->setMaximumSize( 32767, 32767 );
	checkName->setText( "" );
	checkName->setMaxLength( 60 );
	checkName->setEchoMode( QLineEdit::Normal );
	checkName->setFrame( TRUE );

	accountNo = new QLineEdit( this, "LineEdit_25" );
	accountNo->setGeometry( 505, 120, 245, 20 );
	accountNo->setMinimumSize( 10, 10 );
	accountNo->setMaximumSize( 32767, 32767 );
	accountNo->setText( "" );
	accountNo->setMaxLength( 60 );
	accountNo->setEchoMode( QLineEdit::Normal );
	accountNo->setFrame( TRUE );

	phone = new QLineEdit( this, "LineEdit_30" );
	phone->setGeometry( 130, 200, 180, 20 );
	phone->setMinimumSize( 10, 10 );
	phone->setMaximumSize( 32767, 32767 );
	phone->setText( "" );
	phone->setMaxLength( 16 );
	phone->setEchoMode( QLineEdit::Normal );
	phone->setFrame( TRUE );

	altPhone = new QLineEdit( this, "LineEdit_31" );
	altPhone->setGeometry( 130, 220, 180, 20 );
	altPhone->setMinimumSize( 10, 10 );
	altPhone->setMaximumSize( 32767, 32767 );
	altPhone->setText( "" );
	altPhone->setMaxLength( 16 );
	altPhone->setEchoMode( QLineEdit::Normal );
	altPhone->setFrame( TRUE );

	fax = new QLineEdit( this, "LineEdit_32" );
	fax->setGeometry( 130, 240, 180, 20 );
	fax->setMinimumSize( 10, 10 );
	fax->setMaximumSize( 32767, 32767 );
	fax->setText( "" );
	fax->setMaxLength( 16 );
	fax->setEchoMode( QLineEdit::Normal );
	fax->setFrame( TRUE );

	QLabel* dlgedit_Label_28;
	dlgedit_Label_28 = new QLabel( this, "Label_28" );
	dlgedit_Label_28->setGeometry( 400, 20, 100, 20 );
	dlgedit_Label_28->setMinimumSize( 10, 10 );
	dlgedit_Label_28->setMaximumSize( 32767, 32767 );
	dlgedit_Label_28->setText( "Vendor ID:" );
	dlgedit_Label_28->setAlignment( 290 );
	dlgedit_Label_28->setMargin( -1 );

	vendorID = new QLineEdit( this, "LineEdit_33" );
	vendorID->setGeometry( 510, 20, 100, 20 );
	vendorID->setMinimumSize( 10, 10 );
	vendorID->setMaximumSize( 32767, 32767 );
	vendorID->setText( "" );
	vendorID->setMaxLength( 16 );
	vendorID->setEchoMode( QLineEdit::Normal );
	vendorID->setFrame( TRUE );

	active = new QCheckBox( this, "CheckBox_1" );
	active->setGeometry( 685, 20, 65, 20 );
	active->setMinimumSize( 10, 10 );
	active->setMaximumSize( 32767, 32767 );
	active->setText( "Active" );
	active->setAutoRepeat( FALSE );
	active->setAutoResize( FALSE );

	QLabel* dlgedit_Label_29;
	dlgedit_Label_29 = new QLabel( this, "Label_29" );
	dlgedit_Label_29->setGeometry( 395, 80, 125, 20 );
	dlgedit_Label_29->setMinimumSize( 10, 10 );
	dlgedit_Label_29->setMaximumSize( 32767, 32767 );
	dlgedit_Label_29->setText( "Account Information" );
	dlgedit_Label_29->setAlignment( 292 );
	dlgedit_Label_29->setMargin( -1 );

	QLabel* dlgedit_Label_30;
	dlgedit_Label_30 = new QLabel( this, "Label_30" );
	dlgedit_Label_30->setGeometry( 400, 180, 100, 20 );
	dlgedit_Label_30->setMinimumSize( 10, 10 );
	dlgedit_Label_30->setMaximumSize( 32767, 32767 );
	dlgedit_Label_30->setText( "Tax ID:" );
	dlgedit_Label_30->setAlignment( 290 );
	dlgedit_Label_30->setMargin( -1 );

	taxID = new QLineEdit( this, "LineEdit_34" );
	taxID->setGeometry( 505, 180, 120, 20 );
	taxID->setMinimumSize( 10, 10 );
	taxID->setMaximumSize( 32767, 32767 );
	taxID->setText( "" );
	taxID->setMaxLength( 16 );
	taxID->setEchoMode( QLineEdit::Normal );
	taxID->setFrame( TRUE );

	vendorType = new QComboBox( FALSE, this, "ComboBox_1" );
	vendorType->setGeometry( 505, 140, 245, 20 );
	vendorType->setMinimumSize( 10, 10 );
	vendorType->setMaximumSize( 32767, 32767 );
	vendorType->setSizeLimit( 10 );
	vendorType->setAutoResize( FALSE );

	terms = new QComboBox( FALSE, this, "ComboBox_2" );
	terms->setGeometry( 505, 160, 245, 20 );
	terms->setMinimumSize( 10, 10 );
	terms->setMaximumSize( 32767, 32767 );
	terms->setSizeLimit( 10 );
	terms->setAutoResize( FALSE );

	use1099 = new QCheckBox( this, "CheckBox_2" );
	use1099->setGeometry( 645, 180, 105, 20 );
	use1099->setMinimumSize( 10, 10 );
	use1099->setMaximumSize( 32767, 32767 );
	use1099->setText( "Needs 1099" );
	use1099->setAutoRepeat( FALSE );
	use1099->setAutoResize( FALSE );

	QLabel* dlgedit_Label_31;
	dlgedit_Label_31 = new QLabel( this, "Label_31" );
	dlgedit_Label_31->setGeometry( 400, 200, 100, 20 );
	dlgedit_Label_31->setMinimumSize( 10, 10 );
	dlgedit_Label_31->setMaximumSize( 32767, 32767 );
	dlgedit_Label_31->setText( "Credit Limit:" );
	dlgedit_Label_31->setAlignment( 290 );
	dlgedit_Label_31->setMargin( -1 );

	creditLimit = new QLineEdit( this, "LineEdit_35" );
	creditLimit->setGeometry( 505, 200, 120, 20 );
	creditLimit->setMinimumSize( 10, 10 );
	creditLimit->setMaximumSize( 32767, 32767 );
	creditLimit->setText( "" );
	creditLimit->setMaxLength( 12 );
	creditLimit->setEchoMode( QLineEdit::Normal );
	creditLimit->setFrame( TRUE );

	QLabel* dlgedit_Label_32;
	dlgedit_Label_32 = new QLabel( this, "Label_32" );
	dlgedit_Label_32->setGeometry( 400, 230, 100, 20 );
	dlgedit_Label_32->setMinimumSize( 10, 10 );
	dlgedit_Label_32->setMaximumSize( 32767, 32767 );
	dlgedit_Label_32->setText( "Balance:" );
	dlgedit_Label_32->setAlignment( 290 );
	dlgedit_Label_32->setMargin( -1 );

	balance = new QLabel( this, "Label_33" );
	balance->setGeometry( 505, 230, 245, 20 );
	balance->setMinimumSize( 10, 10 );
	balance->setMaximumSize( 32767, 32767 );
	balance->setText( "" );
	balance->setAlignment( 289 );
	balance->setMargin( -1 );

	QPushButton* dlgedit_PushButton_1;
	dlgedit_PushButton_1 = new QPushButton( this, "PushButton_1" );
	dlgedit_PushButton_1->setGeometry( 620, 280, 65, 30 );
	dlgedit_PushButton_1->setMinimumSize( 10, 10 );
	dlgedit_PushButton_1->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_1, SIGNAL(clicked()), SLOT(saveVendor()) );
	dlgedit_PushButton_1->setText( "&Save" );
	dlgedit_PushButton_1->setAutoRepeat( FALSE );
	dlgedit_PushButton_1->setAutoResize( FALSE );

	QPushButton* dlgedit_PushButton_2;
	dlgedit_PushButton_2 = new QPushButton( this, "PushButton_2" );
	dlgedit_PushButton_2->setGeometry( 690, 280, 65, 30 );
	dlgedit_PushButton_2->setMinimumSize( 10, 10 );
	dlgedit_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_2, SIGNAL(clicked()), SLOT(cancelVendor()) );
	dlgedit_PushButton_2->setText( "&Cancel" );
	dlgedit_PushButton_2->setAutoRepeat( FALSE );
	dlgedit_PushButton_2->setAutoResize( FALSE );

	resize( 770,320 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


VendorEditData::~VendorEditData()
{
}
void VendorEditData::saveVendor()
{
}
void VendorEditData::cancelVendor()
{
}
