/**********************************************************************

	--- Qt Architect generated file ---

	File: VendorEditData.h
	Last generated: Thu Dec 25 23:50:24 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef VendorEditData_included
#define VendorEditData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qchkbox.h>
#include <qlined.h>
#include <qcombo.h>

class VendorEditData : public QWidget
{
    Q_OBJECT

public:

    VendorEditData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~VendorEditData();

public slots:


protected slots:

    virtual void saveVendor();
    virtual void cancelVendor();

protected:
    QLineEdit* companyName;
    QLineEdit* contactName;
    QLineEdit* altContact;
    QLineEdit* address1;
    QLineEdit* address2;
    QLineEdit* city;
    QLineEdit* state;
    QLineEdit* zip;
    QLineEdit* checkName;
    QLineEdit* accountNo;
    QLineEdit* phone;
    QLineEdit* altPhone;
    QLineEdit* fax;
    QLineEdit* vendorID;
    QCheckBox* active;
    QLineEdit* taxID;
    QComboBox* vendorType;
    QComboBox* terms;
    QCheckBox* use1099;
    QLineEdit* creditLimit;
    QLabel* balance;

};

#endif // VendorEditData_included
