/**********************************************************************

	--- Dlgedit generated file ---

	File: VendorTypeEditData.h
	Last generated: Tue Sep 16 20:54:21 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef VendorTypeEditData_included
#define VendorTypeEditData_included

#include <qwidget.h>
#include <qcombo.h>
#include <qlined.h>

class VendorTypeEditData : public QWidget
{
    Q_OBJECT

public:

    VendorTypeEditData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~VendorTypeEditData();

public slots:


protected slots:

    virtual void saveVendType();
    virtual void cancelVendType();

protected:
    QLineEdit* vendTypeEnt;
    QComboBox* subTypeList;

};

#endif // VendorTypeEditData_included
