/**********************************************************************

	--- Dlgedit generated file ---

	File: VendorTypeEditData.cpp
	Last generated: Tue Sep 16 20:54:21 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#include "VendorTypeEditData.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qpushbt.h>

VendorTypeEditData::VendorTypeEditData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name )
{
	QLabel* tmpQLabel;
	tmpQLabel = new QLabel( this, "Label_1" );
	tmpQLabel->setGeometry( 20, 20, 90, 30 );
	tmpQLabel->setText( "Vendor Type:" );
	tmpQLabel->setAlignment( 290 );
	tmpQLabel->setMargin( -1 );

	vendTypeEnt = new QLineEdit( this, "LineEdit_1" );
	vendTypeEnt->setGeometry( 120, 20, 370, 30 );
	vendTypeEnt->setText( "" );
	vendTypeEnt->setMaxLength( 60 );
	vendTypeEnt->setEchoMode( QLineEdit::Normal );
	vendTypeEnt->setFrame( TRUE );

	tmpQLabel = new QLabel( this, "Label_2" );
	tmpQLabel->setGeometry( 10, 60, 100, 30 );
	tmpQLabel->setText( "Sub type of:" );
	tmpQLabel->setAlignment( 290 );
	tmpQLabel->setMargin( -1 );

	subTypeList = new QComboBox( FALSE, this, "ComboBox_1" );
	subTypeList->setGeometry( 120, 60, 370, 30 );
	subTypeList->setSizeLimit( 10 );
	subTypeList->setAutoResize( FALSE );

	QPushButton* tmpQPushButton;
	tmpQPushButton = new QPushButton( this, "cancelBut" );
	tmpQPushButton->setGeometry( 320, 130, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(cancelVendType()) );
	tmpQPushButton->setText( "Cancel" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	tmpQPushButton = new QPushButton( this, "saveBut" );
	tmpQPushButton->setGeometry( 110, 130, 100, 30 );
	connect( tmpQPushButton, SIGNAL(clicked()), SLOT(saveVendType()) );
	tmpQPushButton->setText( "Save" );
	tmpQPushButton->setAutoRepeat( FALSE );
	tmpQPushButton->setAutoResize( FALSE );

	resize( 550, 180 );
}


VendorTypeEditData::~VendorTypeEditData()
{
}
void VendorTypeEditData::cancelVendType()
{
}
void VendorTypeEditData::saveVendType()
{
}
