/**********************************************************************

	--- Dlgedit generated file ---

	File: VendorTypesData.h
	Last generated: Wed Sep 17 15:43:49 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef VendorTypesData_included
#define VendorTypesData_included

#include <qwidget.h>
#include <qlistbox.h>
#include <qmenubar.h>

class VendorTypesData : public QWidget
{
    Q_OBJECT

public:

    VendorTypesData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~VendorTypesData();

public slots:


protected slots:

    virtual void editVendorTypeL(int);
    virtual void Hide();
    virtual void deleteVendorType();
    virtual void newVendorType();
    virtual void editVendorType();

protected:
    QListBox* list;
    QMenuBar* menu;

};

#endif // VendorTypesData_included
