/**********************************************************************

	--- Qt Architect generated file ---

	File: WipedAccountsData.h
	Last generated: Thu Nov 12 16:15:23 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef WipedAccountsData_included
#define WipedAccountsData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qlistview.h>
#include <qprogbar.h>
#include <qradiobt.h>

class WipedAccountsData : public QDialog
{
    Q_OBJECT

public:

    WipedAccountsData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~WipedAccountsData();

public slots:


protected slots:

    virtual void processSelections();
    virtual void cancelOverdue();
    virtual void selectNone();
    virtual void selectAll();

protected:
    QRadioButton* noAction;
    QRadioButton* actionOne;
    QRadioButton* actionTwo;
    QLabel* accountsOverdue;
    QLabel* accountsSelected;
    QLabel* amountOverdue;
    QLabel* selectedOverdue;
    QProgressBar* progress;
    QLabel* progressLabel;
    QListView* list;

};

#endif // WipedAccountsData_included
