/**********************************************************************

	--- Qt Architect generated file ---

	File: WipedAccountsData.cpp
	Last generated: Thu Nov 12 16:15:23 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "WipedAccountsData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qbttngrp.h>
#include <qpushbt.h>

WipedAccountsData::WipedAccountsData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, FALSE, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_3;
	qtarch_ButtonGroup_3 = new QButtonGroup( this, "ButtonGroup_3" );
	qtarch_ButtonGroup_3->setGeometry( 5, 285, 295, 105 );
	qtarch_ButtonGroup_3->setMinimumSize( 10, 10 );
	qtarch_ButtonGroup_3->setMaximumSize( 32767, 32767 );
	qtarch_ButtonGroup_3->setFocusPolicy( QWidget::NoFocus );
	qtarch_ButtonGroup_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ButtonGroup_3->setFrameStyle( 49 );
	qtarch_ButtonGroup_3->setTitle( "Summary Information" );
	qtarch_ButtonGroup_3->setAlignment( 1 );

	QButtonGroup* qtarch_ButtonGroup_2;
	qtarch_ButtonGroup_2 = new QButtonGroup( this, "ButtonGroup_2" );
	qtarch_ButtonGroup_2->setGeometry( 310, 285, 185, 105 );
	qtarch_ButtonGroup_2->setMinimumSize( 10, 10 );
	qtarch_ButtonGroup_2->setMaximumSize( 32767, 32767 );
	qtarch_ButtonGroup_2->setFocusPolicy( QWidget::NoFocus );
	qtarch_ButtonGroup_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ButtonGroup_2->setFrameStyle( 49 );
	qtarch_ButtonGroup_2->setTitle( "Action" );
	qtarch_ButtonGroup_2->setAlignment( 1 );

	QLabel* qtarch_Label_2;
	qtarch_Label_2 = new QLabel( this, "Label_2" );
	qtarch_Label_2->setGeometry( 5, 10, 260, 25 );
	qtarch_Label_2->setMinimumSize( 10, 10 );
	qtarch_Label_2->setMaximumSize( 32767, 32767 );
	qtarch_Label_2->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_2->setText( "Select the accounts to be affected." );
	qtarch_Label_2->setAlignment( 1313 );
	qtarch_Label_2->setMargin( -1 );

	noAction = new QRadioButton( this, "RadioButton_3" );
	noAction->setGeometry( 325, 310, 100, 20 );
	noAction->setMinimumSize( 10, 10 );
	noAction->setMaximumSize( 32767, 32767 );
	noAction->setFocusPolicy( QWidget::TabFocus );
	noAction->setBackgroundMode( QWidget::PaletteBackground );
	noAction->setText( "Non&e" );
	noAction->setAutoRepeat( FALSE );
	noAction->setAutoResize( FALSE );
	noAction->setChecked( TRUE );

	actionOne = new QRadioButton( this, "RadioButton_4" );
	actionOne->setGeometry( 325, 335, 125, 20 );
	actionOne->setMinimumSize( 10, 10 );
	actionOne->setMaximumSize( 32767, 32767 );
	actionOne->setFocusPolicy( QWidget::TabFocus );
	actionOne->setBackgroundMode( QWidget::PaletteBackground );
	actionOne->setText( "&Send Final Notice" );
	actionOne->setAutoRepeat( FALSE );
	actionOne->setAutoResize( FALSE );

	actionTwo = new QRadioButton( this, "RadioButton_5" );
	actionTwo->setGeometry( 325, 360, 145, 20 );
	actionTwo->setMinimumSize( 10, 10 );
	actionTwo->setMaximumSize( 32767, 32767 );
	actionTwo->setFocusPolicy( QWidget::TabFocus );
	actionTwo->setBackgroundMode( QWidget::PaletteBackground );
	actionTwo->setText( "S&end to collection" );
	actionTwo->setAutoRepeat( FALSE );
	actionTwo->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_1;
	qtarch_PushButton_1 = new QPushButton( this, "PushButton_1" );
	qtarch_PushButton_1->setGeometry( 510, 340, 80, 25 );
	qtarch_PushButton_1->setMinimumSize( 10, 10 );
	qtarch_PushButton_1->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_1, SIGNAL(clicked()), SLOT(processSelections()) );
	qtarch_PushButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_1->setText( "C&ontinue" );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );
	qtarch_PushButton_1->setAutoDefault( TRUE );

	QPushButton* qtarch_PushButton_2;
	qtarch_PushButton_2 = new QPushButton( this, "PushButton_2" );
	qtarch_PushButton_2->setGeometry( 510, 370, 80, 25 );
	qtarch_PushButton_2->setMinimumSize( 10, 10 );
	qtarch_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_2, SIGNAL(clicked()), SLOT(cancelOverdue()) );
	qtarch_PushButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_2->setText( "&Cancel" );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_3;
	qtarch_PushButton_3 = new QPushButton( this, "PushButton_3" );
	qtarch_PushButton_3->setGeometry( 510, 310, 80, 25 );
	qtarch_PushButton_3->setMinimumSize( 10, 10 );
	qtarch_PushButton_3->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_3, SIGNAL(clicked()), SLOT(selectAll()) );
	qtarch_PushButton_3->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_3->setText( "Select &All" );
	qtarch_PushButton_3->setAutoRepeat( FALSE );
	qtarch_PushButton_3->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_4;
	qtarch_PushButton_4 = new QPushButton( this, "PushButton_4" );
	qtarch_PushButton_4->setGeometry( 510, 280, 80, 25 );
	qtarch_PushButton_4->setMinimumSize( 10, 10 );
	qtarch_PushButton_4->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_4, SIGNAL(clicked()), SLOT(selectNone()) );
	qtarch_PushButton_4->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_4->setText( "Select &None" );
	qtarch_PushButton_4->setAutoRepeat( FALSE );
	qtarch_PushButton_4->setAutoResize( FALSE );

	QLabel* qtarch_Label_4;
	qtarch_Label_4 = new QLabel( this, "Label_4" );
	qtarch_Label_4->setGeometry( 10, 305, 135, 20 );
	qtarch_Label_4->setMinimumSize( 10, 10 );
	qtarch_Label_4->setMaximumSize( 32767, 32767 );
	qtarch_Label_4->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_4->setText( "Accounts Overdue:" );
	qtarch_Label_4->setAlignment( 290 );
	qtarch_Label_4->setMargin( -1 );

	QLabel* qtarch_Label_5;
	qtarch_Label_5 = new QLabel( this, "Label_5" );
	qtarch_Label_5->setGeometry( 10, 325, 135, 20 );
	qtarch_Label_5->setMinimumSize( 10, 10 );
	qtarch_Label_5->setMaximumSize( 32767, 32767 );
	qtarch_Label_5->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_5->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_5->setText( "Account Selected:" );
	qtarch_Label_5->setAlignment( 290 );
	qtarch_Label_5->setMargin( -1 );

	QLabel* qtarch_Label_6;
	qtarch_Label_6 = new QLabel( this, "Label_6" );
	qtarch_Label_6->setGeometry( 10, 345, 135, 20 );
	qtarch_Label_6->setMinimumSize( 10, 10 );
	qtarch_Label_6->setMaximumSize( 32767, 32767 );
	qtarch_Label_6->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_6->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_6->setText( "Total Amount Overdue:" );
	qtarch_Label_6->setAlignment( 290 );
	qtarch_Label_6->setMargin( -1 );

	QLabel* qtarch_Label_7;
	qtarch_Label_7 = new QLabel( this, "Label_7" );
	qtarch_Label_7->setGeometry( 10, 365, 135, 20 );
	qtarch_Label_7->setMinimumSize( 10, 10 );
	qtarch_Label_7->setMaximumSize( 32767, 32767 );
	qtarch_Label_7->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_7->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_7->setText( "Total from Selected:" );
	qtarch_Label_7->setAlignment( 290 );
	qtarch_Label_7->setMargin( -1 );

	accountsOverdue = new QLabel( this, "Label_8" );
	accountsOverdue->setGeometry( 150, 305, 145, 20 );
	accountsOverdue->setMinimumSize( 10, 10 );
	accountsOverdue->setMaximumSize( 32767, 32767 );
	accountsOverdue->setFocusPolicy( QWidget::NoFocus );
	accountsOverdue->setBackgroundMode( QWidget::PaletteBackground );
	accountsOverdue->setFrameStyle( 50 );
	accountsOverdue->setText( "" );
	accountsOverdue->setAlignment( 290 );
	accountsOverdue->setMargin( -1 );

	accountsSelected = new QLabel( this, "Label_9" );
	accountsSelected->setGeometry( 150, 325, 145, 20 );
	accountsSelected->setMinimumSize( 10, 10 );
	accountsSelected->setMaximumSize( 32767, 32767 );
	accountsSelected->setFocusPolicy( QWidget::NoFocus );
	accountsSelected->setBackgroundMode( QWidget::PaletteBackground );
	accountsSelected->setFrameStyle( 50 );
	accountsSelected->setText( "" );
	accountsSelected->setAlignment( 290 );
	accountsSelected->setMargin( -1 );

	amountOverdue = new QLabel( this, "Label_10" );
	amountOverdue->setGeometry( 150, 345, 145, 20 );
	amountOverdue->setMinimumSize( 10, 10 );
	amountOverdue->setMaximumSize( 32767, 32767 );
	amountOverdue->setFocusPolicy( QWidget::NoFocus );
	amountOverdue->setBackgroundMode( QWidget::PaletteBackground );
	amountOverdue->setFrameStyle( 50 );
	amountOverdue->setLineWidth( 2 );
	amountOverdue->setText( "" );
	amountOverdue->setAlignment( 290 );
	amountOverdue->setMargin( -1 );

	selectedOverdue = new QLabel( this, "Label_11" );
	selectedOverdue->setGeometry( 150, 365, 145, 20 );
	selectedOverdue->setMinimumSize( 10, 10 );
	selectedOverdue->setMaximumSize( 32767, 32767 );
	selectedOverdue->setFocusPolicy( QWidget::NoFocus );
	selectedOverdue->setBackgroundMode( QWidget::PaletteBackground );
	selectedOverdue->setFrameStyle( 50 );
	selectedOverdue->setLineWidth( 2 );
	selectedOverdue->setText( "" );
	selectedOverdue->setAlignment( 290 );
	selectedOverdue->setMargin( -1 );

	progress = new QProgressBar( 100, this, "ProgressBar_1" );
	progress->setGeometry( 430, 10, 165, 20 );
	progress->setMinimumSize( 10, 10 );
	progress->setMaximumSize( 32767, 32767 );
	progress->setFocusPolicy( QWidget::NoFocus );
	progress->setBackgroundMode( QWidget::PaletteBackground );
	progress->setFrameStyle( 51 );
	progress->setLineWidth( 2 );
	progress->setProgress( -1 );

	progressLabel = new QLabel( this, "Label_12" );
	progressLabel->setGeometry( 290, 10, 135, 20 );
	progressLabel->setMinimumSize( 10, 10 );
	progressLabel->setMaximumSize( 32767, 32767 );
	progressLabel->setFocusPolicy( QWidget::NoFocus );
	progressLabel->setBackgroundMode( QWidget::PaletteBackground );
	progressLabel->setText( "Searching..." );
	progressLabel->setAlignment( 290 );
	progressLabel->setMargin( -1 );

	list = new QListView( this, "List_1" );
	list->setGeometry( 10, 40, 585, 235 );
	list->setMinimumSize( 585, 235 );
	list->setMaximumSize( 585, 235 );
	list->setFocusPolicy( QWidget::TabFocus );
	list->setBackgroundMode( QWidget::PaletteBackground );
	list->setResizePolicy( QScrollView::Manual );
	list->setVScrollBarMode( QScrollView::Auto );
	list->setHScrollBarMode( QScrollView::Auto );
	list->setTreeStepSize( 20 );
	list->setMultiSelection( FALSE );
	list->setAllColumnsShowFocus( FALSE );
	list->setItemMargin( 1 );
	list->setRootIsDecorated( FALSE );
	list->addColumn( "Cust ID", -1 );
	list->setColumnWidthMode( 0, QListView::Maximum );
	list->setColumnAlignment( 0, 1 );
	list->addColumn( "Customer Name", -1 );
	list->setColumnWidthMode( 1, QListView::Maximum );
	list->setColumnAlignment( 1, 1 );
	list->addColumn( "Primary Login", -1 );
	list->setColumnWidthMode( 2, QListView::Maximum );
	list->setColumnAlignment( 2, 1 );
	list->addColumn( "Balance", -1 );
	list->setColumnWidthMode( 3, QListView::Maximum );
	list->setColumnAlignment( 3, 2 );
	list->addColumn( "Overdue", -1 );
	list->setColumnWidthMode( 4, QListView::Maximum );
	list->setColumnAlignment( 4, 2 );
	list->addColumn( "Newest", -1 );
	list->setColumnWidthMode( 5, QListView::Maximum );
	list->setColumnAlignment( 5, 2 );
	list->addColumn( "Oldest", -1 );
	list->setColumnWidthMode( 6, QListView::Maximum );
	list->setColumnAlignment( 6, 2 );
	list->addColumn( "Notes", -1 );
	list->setColumnWidthMode( 7, QListView::Maximum );
	list->setColumnAlignment( 7, 2 );


	qtarch_ButtonGroup_2->insert( noAction );
	qtarch_ButtonGroup_2->insert( actionOne );
	qtarch_ButtonGroup_2->insert( actionTwo );

	resize( 600,400 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


WipedAccountsData::~WipedAccountsData()
{
}
void WipedAccountsData::processSelections()
{
}
void WipedAccountsData::cancelOverdue()
{
}
void WipedAccountsData::selectAll()
{
}
void WipedAccountsData::selectNone()
{
}
