#!/bin/sh

BUILDNUM=`cat .buildnum`
NEWBUILD=`expr $BUILDNUM + 1`
BUILDDATE=`date +"%m-%d-%Y"`
echo $NEWBUILD
echo $NEWBUILD > .buildnum
echo "#ifndef BUILDNUM" > include/buildnum.h
echo "const char *BUILDNUM(void);" >> include/buildnum.h
echo "#endif" >> include/buildnum.h
echo "const char *BUILDNUM(void)" > lib/buildnum.cpp
echo "{ return \"$NEWBUILD, $BUILDDATE\";}" >> lib/buildnum.cpp
